Add storybook test github action
opendatahub-io/odh-dashboard pull request #1039
Opened 2023-03-22 22:30 UTC by Gkrumbach07

closes: https://github.com/opendatahub-io/odh-dashboard/issues/984
## Description

This adds storybook ci testing as a github action. The action will build storybook, run the build, run the test-runner, and if all passes, will pass the ci

## How Has This Been Tested?

1. fork the repo
2. make a not breaking pr
3. check that the storybook ci runs asn passes
4. make another pr with a change that breaks the test 
5. check that storybook ci runs and fails

## Test Impact

im not going to test the test

## Request review criteria:

- [x] The commits have meaningful messages (squashes happen on merge by the bot).
- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

2023-03-23 08:57 UTC, lucferbux requested changes

2023-03-23 09:04 UTC, lucferbux requested changes

2023-03-23 11:58 UTC, Gkrumbach07 commented on .github/workflows/storybook-tests.yml
> +on: push
i can change it to on pr. makes more sense

2023-03-23 11:59 UTC, Gkrumbach07 commented on .github/workflows/storybook-tests.yml
> +      - uses: actions/checkout@v2
reason: this is what storybooks docs gave as an example. Im sure v3 would be fine. will make the switch

2023-03-23 11:59 UTC, Gkrumbach07 commented on .github/workflows/storybook-tests.yml
> +          node-version: '18.x'
do we need that now or is keeping it at 18 fine?

2023-03-23 17:09 UTC, Gkrumbach07 commented
command is failing in the github action... investigating

2023-03-23 19:29 UTC, Gkrumbach07 commented
everything is caching properly now. and looks like it is working via the checkmark in the actions list

2023-03-24 16:07 UTC, andrewballantyne requested changes

2023-03-24 16:07 UTC, andrewballantyne commented on .github/workflows/storybook-tests.yml
> +        run: npx playwright install --with-deps
Is there a reason this is not covered as part of the install dependencies?

2023-03-24 16:29 UTC, Gkrumbach07 commented on frontend/src/pages/projects/screens/projects/ProjectView.stories.tsx
> +  const nameInput = body.getByRole('textbox', { name: 'Name' });
hmm i must have done a merge without looking. my bad. i will revert that chunk back

2023-03-24 16:40 UTC, merged