Update README and CONTRIBUTING formatting
opendatahub-io/odh-dashboard pull request #1050
Opened 2023-03-29 08:27 UTC by lucferbux

## Description

Closes #1034 

## How Has This Been Tested?

## Test Impact

## Request review criteria:

- [X] The commits have meaningful messages (squashes happen on merge by the bot).
- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

2023-03-30 09:15 UTC, lucferbux commented on CONTRIBUTING.md
> +- [OpenShift CLI](https://docs.openshift.com/enterprise/3.2/cli_reference/get_started_cli.html#installing-the-cli)
Yeah, you are right, completely missed this!

2023-03-30 12:14 UTC, andrewballantyne requested changes
Some thoughts -- all optional.

2023-03-30 12:14 UTC, andrewballantyne commented on CONTRIBUTING.md
> +npm run dev
This is good in a pinch -- but it sucks for actual development. You can't stop the server and client independently... so if you want to clear a cache or need to restart the frontend or backend independently you have to drop everything.

Did we want to note you can start them via `npm run start:dev` in the frontend and backend folders?

2023-03-30 12:14 UTC, andrewballantyne commented on README.md
> +- [Quay.io](https://quay.io/)
Should we really be duplicating? Can the CONTRIB point at this?

2023-03-30 18:30 UTC, lucferbux commented on CONTRIBUTING.md
> +- and have access to [Quay.io](https://quay.io/)
Yes, that's a great idea, I'm gonna add it into another section though.

2023-03-31 03:26 UTC, DaoDaoNoCode approved these changes
lgtm!

2023-03-31 13:03 UTC, andrewballantyne approved these changes

2023-03-31 13:06 UTC, merged