Create model serving page skeleton (#1006)
opendatahub-io/odh-dashboard pull request #1054
Opened 2023-03-29 21:50 UTC by alexcreasy

Closes: #1006 

## Description
Adds a tab interface to the Model Serving page in preparation for adding the explainability: fairness and bias charts.  
![localhost_4010_modelServing_metrics_aardvark_test (1)](https://user-images.githubusercontent.com/4092230/228673644-677fc0ec-362f-4da6-96fd-656a336c7b2f.png)

![localhost_4010_modelServing_metrics_aardvark_test (2)](https://user-images.githubusercontent.com/4092230/228673651-710aac60-51e1-4f6a-ae9a-e22e6e2ad9eb.png)

## How Has This Been Tested?
1. Open the model serving page
2. Click between tabs and watch the content change

## Test Impact
No tests yet, will look to add these as part of the wider tracker containing this issue.

## Request review criteria:

- [ x] The commits have meaningful messages (squashes happen on merge by the bot).
- [ x] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.
- [x ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ x] The developer has manually tested the changes and verified that the changes work
- [ x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

2023-03-30 11:20 UTC, andrewballantyne requested changes
Just a code review -- need a cluster.

2023-03-30 11:49 UTC, andrewballantyne reviewed
Works and looks great.

@vconzola Question. This is a template set of stuff, so no need to "review" per se... but do you know how you feel about the "Refresh dropdown" being sync'ed between tabs? Is that desired? It's below the tabs, so should it have a state on its own?

2023-03-30 13:24 UTC, vconzola commented
@andrewballantyne Hmm...good question. I don't really know if users will be looking at performance and quality as part of the same workflow. It kinda makes sense that they would, don't you think? If you agree, let's sync state between the tabs. Ideally, we'd move the dropdown and the refresh button above the tabs. But for now, let's leave them where they are in case I'm wrong and we learn later that users want to look at different timeframes for performance and quality for some reason. I don't think anyone will get too bent out of shape by the control placement.

2023-03-30 17:00 UTC, alexcreasy commented on frontend/src/pages/modelServing/screens/metrics/MetricsPageTabs.tsx
> +  // Toggle currently active tab
yeah, this got pasted in from the patternfly example - it can go for sure

2023-03-31 14:19 UTC, alexcreasy commented on frontend/src/pages/modelServing/screens/metrics/MetricsPageTabs.tsx
> +        aria-label="Default content - performance"
Yeah I copied the PatternFly example and thought this was maybe some best practice, but I guess it was just a placeholder they used with no special meaning :D

2023-04-11 09:43 UTC, lucferbux requested changes

2023-04-11 09:43 UTC, lucferbux commented on frontend/src/pages/modelServing/screens/metrics/MetricsPage.tsx
>    children: React.ReactNode;
+1

2023-04-11 09:43 UTC, lucferbux commented on frontend/src/pages/modelServing/screens/metrics/MetricsPageTabs.scss
> +// This is a hack to get around a bug in PatternFly TabContent.
I bumped into a similar issue, in the example sections of Tab they suggest a different approach which allows you to avoid adding custom CSS.

2023-04-11 09:43 UTC, lucferbux commented on frontend/src/pages/modelServing/screens/metrics/MetricsPageTabs.tsx
> +export default MetricsPageTabs;
This is the suggested layout from the patternfly examples:

```suggestion
import React from 'react';
import {
  Tabs,
  Tab,
  TabTitleText,
  PageSection,
  TabContent,
  TabContentBody,
} from '@patternfly/react-core';
import PerformanceTab from './PerformanceTab';
import QualityTab from './QualityTab';

const MetricsPageTabs: React.FC = () => {
  const [activeTabKey, setActiveTabKey] = React.useState<string | number>(0);

  const handleTabClick = (tabIndex: number) => setActiveTabKey(tabIndex);

  return (
    <>
      <PageSection type="tabs">
        <Tabs
          activeKey={activeTabKey}
          onSelect={(_event, tabIndex) => handleTabClick(Number(tabIndex))}
          usePageInsets
          id="nested-tabs-example-tabs-list"
        >
          <Tab
            eventKey={0}
            title={<TabTitleText>Performance</TabTitleText>}
            tabContentId={`tabContent${0}`}
          />
          <Tab
            eventKey={1}
            title={<TabTitleText>Quality</TabTitleText>}
            tabContentId={`tabContent${1}`}
          />
        </Tabs>
      </PageSection>
      <PageSection isFilled padding={{ default: 'noPadding' }}>
        <TabContent
          key={0}
          eventKey={0}
          id={`tabContent${0}`}
          activeKey={activeTabKey}
          hidden={0 !== activeTabKey}
        >
          <TabContentBody>
            <PerformanceTab />
          </TabContentBody>
        </TabContent>
        <TabContent
          key={1}
          eventKey={1}
          id={`tabContent${1}`}
          activeKey={activeTabKey}
          hidden={1 !== activeTabKey}
        >
          <TabContentBody>
            <QualityTab />
          </TabContentBody>
        </TabContent>
      </PageSection>
    </>
  );
};

export default MetricsPageTabs;
```

2023-04-25 17:40 UTC, andrewballantyne commented
Completed by https://github.com/opendatahub-io/odh-dashboard/pull/1093

2023-04-25 17:40 UTC, closed without merging