fixed data connection flow
opendatahub-io/odh-dashboard pull request #1140
Opened 2023-04-17 21:02 UTC by Gkrumbach07

closes: https://github.com/opendatahub-io/odh-dashboard/issues/1071

## Description

fixed the spawner form data connection section submit flow. Issue was that there was no check to remove the existing data connection when a new connection was added. It only checked when an existing connection was used.

Now the flow is:
- use new data connection var: only defined when data connections are enabled and new data connection is selected 
- use existing data connection var: only defined when data connections are enabled and existing data connection is selected and that data connection is not equal to the old data connection

So now we remove the old data connection if a new var is defined, existing var is defined or data connection have been disabled

## How Has This Been Tested?

- create a new workbench with a data connection
- edit workbench
    - create new data connection in form section
    - submit
- there should be two data connections with only the new data connection assigned to the workbench. The old one should of had its connection removed
- you can also test that replacing data connections and disabling data connections work as well

## Test Impact

test coverage is already here/ no changes (this is also an e2e test so we cant test it with unit testing)

## Request review criteria:

- [x] The commits have meaningful messages (squashes happen on merge by the bot).
- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

2023-04-18 20:48 UTC, andrewballantyne requested changes
(deleted comment)

Very odd -- okay, so I was on the wrong branch somehow, must have fat fingered something and not vetted before I started up my server.

I had some issues the first pass trying to modify the workbench -- but it works now (and I can't seem to reproduce the issue). LGTM I guess... Waiting on someone else to test it.

2023-04-18 21:33 UTC, andrewballantyne requested changes
Ah, very specific flow too 😕 Weird.
1. New Project
1. New Workbench
    1. Name it something
    1. Doesn’t seem image impacts it, select one (I selected the first one, Minimal Python)
    1. Data connection the same name as the workbench
    1. Create
1. Disable Workbench
1. Edit Workbench
    1. Create a new data connection — obv different name
    1. Update

That seems to have done it. I named my project `Test` - the workbench & first data connection `Solar Predictions` - the second data connection `New Data`. Not sure what is specific about this, but that's what I did.
![image](https://user-images.githubusercontent.com/8126518/232910083-5b18ba03-8e91-481e-b69e-f2b4623d0aa5.png)

2023-04-18 22:06 UTC, Gkrumbach07 commented
> Ah, very specific flow too 😕 Weird.
> 
> 1. New Project
> 2. New Workbench
>    
>    1. Name it something
>    2. Doesn’t seem image impacts it, select one (I selected the first one, Minimal Python)
>    3. Data connection the same name as the workbench
>    4. Create
> 3. Disable Workbench
> 4. Edit Workbench
>    
>    1. Create a new data connection — obv different name
>    2. Update
> 
> That seems to have done it. I named my project `Test` - the workbench & first data connection `Solar Predictions` - the second data connection `New Data`. Not sure what is specific about this, but that's what I did. ![image](https://user-images.githubusercontent.com/8126518/232910083-5b18ba03-8e91-481e-b69e-f2b4623d0aa5.png)



> Ah, very specific flow too 😕 Weird.
> 
> 1. New Project
> 2. New Workbench
>    
>    1. Name it something
>    2. Doesn’t seem image impacts it, select one (I selected the first one, Minimal Python)
>    3. Data connection the same name as the workbench
>    4. Create
> 3. Disable Workbench
> 4. Edit Workbench
>    
>    1. Create a new data connection — obv different name
>    2. Update
> 
> That seems to have done it. I named my project `Test` - the workbench & first data connection `Solar Predictions` - the second data connection `New Data`. Not sure what is specific about this, but that's what I did. ![image](https://user-images.githubusercontent.com/8126518/232910083-5b18ba03-8e91-481e-b69e-f2b4623d0aa5.png)

I am able to reproduce it as well. This also occurs on all environment variables, not just data connections. I logged a bug for this.

2023-04-19 05:39 UTC, DaoDaoNoCode approved these changes
LGTM. Tested and didn't even meet the issue mentioned above, really weird. I guess some changes are still happening to the Notebook CR by the operator when you first create a workbench and disable it, but I don't know because I didn't see the issue.

2023-04-19 11:59 UTC, merged