pipelines modal use up top date data connections
opendatahub-io/odh-dashboard pull request #1322
Opened 2023-05-31 19:05 UTC by Gkrumbach07

closes: https://github.com/opendatahub-io/odh-dashboard/issues/1307

## Description

using context data connection instead of using hook as it was always stale. also passing data connection into form section so it always has the same data

## How Has This Been Tested?

1. Create a project
2. Create a data connection
3. Attempt to create the Pipeline Server

## Test Impact

pipelines tests are in an issue already

## Request review criteria:

- [x] The commits have meaningful messages (squashes happen on merge by the bot).
- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

2023-06-01 12:30 UTC, lucferbux approved these changes
/lgtm

2023-06-02 13:02 UTC, Gkrumbach07 commented
@andrewballantyne this should fix the issue

2023-06-02 15:03 UTC, andrewballantyne requested changes

2023-06-02 15:03 UTC, andrewballantyne commented on frontend/src/concepts/pipelines/content/configurePipelinesServer/ConfigurePipelinesServerModal.tsx
> +  } = React.useContext(ProjectDetailsContext);
This breaks being able to add it with an existing connection on the global pages...

2023-06-02 15:59 UTC, andrewballantyne approved these changes

2023-06-02 16:05 UTC, merged