Default and restrict threshold, add tooltips, default duplicate name and set feature flag
opendatahub-io/odh-dashboard pull request #1390
Opened 2023-06-14 21:30 UTC by DaoDaoNoCode

Closes #1383 #1384 

## Description

Do the following things:
1. Set the default value of threshold delta based on the metric type
2. Limit the threshold delta based on the metric type (there will be no error message or helper text, but the creation will be disabled if the user input invalid values)
3.  **[WIP]** Add tooltips and descriptions, documentation: https://docs.google.com/document/d/1qq0lobOJQpXD1IowclSWaKhTT_qEPz56IMzvCeOfczY/edit
4. When duplicating the configuration, set the default duplicated name as mentioned in the issue
5. Add `disableBiasMetrics` feature flag in the dashboard config. When the flag is `true`, we do following:
a. Hide the bias tab
b. Disable all the routes related to bias metrics
c. Disabled all the trusty API network calls

## How Has This Been Tested?

To test description 1:
Go to bias metrics configuration modal, change the metric type and see how the threshold delta value changes

To test description 2:
Go to bias metrics configuration modal, try to input some invalid batch size and threshold delta to see if the submit button is disabled

To test description 4:
Duplicate one bias configuration, see if the name field is set as expected

To test description 5:
1. Go to dashboard config CR
2. Set `disableBiasMetrics` to `true`
3. Go to the global model serving page, click on one of the models
4. There should be only the performance tab on the page, no bias tab
5. Change the tab in the URL from `performance` to `bias`, it should navigate you back to `performance`
6. Access the configuration page from the URL, it should navigate you back to `performance`
7. Check the network calls to make sure there is no call for the trusty AI server
8. Repeat every step from 4-7 on the project details page (because they have different URLs), and make sure the results are the same
9. Set Set `disableBiasMetrics` to `false`
10. Wait for 2 mins (or whenever the dashboard re-fetch the dashboard config again)
11. Repeat 3-8, make sure you can use bias metrics as normal

## Test Impact

TBD

## Request review criteria:

- [ ] The commits have meaningful messages (squashes happen on merge by the bot).
- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

2023-06-15 15:10 UTC, alexcreasy commented
Found one small bug with the modal:

* When you first open the Configure bias metric modal - SPD is selected by default but no default violation is supplied - see screenshot. It works great once you change the value via the dropdown though.
<img width="851" alt="image" src="https://github.com/opendatahub-io/odh-dashboard/assets/4092230/79a1d8c2-aa52-46b4-a783-327d6d10e77d">

Otherwise the modal features are great, I'll test the feature flag now.

2023-06-15 15:12 UTC, DaoDaoNoCode commented
This is super weird @alexcreasy because it should be no selection by default.
<img width="1789" alt="Screenshot 2023-06-15 at 11 12 37 AM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/3d0c4d2c-fef6-48f8-bfe7-22aa82071613">

2023-06-15 15:13 UTC, DaoDaoNoCode commented
ok, I see the issue. I forgot to clear the metrics type selection when they close the modal.

2023-06-16 10:30 UTC, alexcreasy commented
Tested and only found one potential issue. When the feature flag is disabled, the service still makes call to prometheus for trusty data. Other than that it works well, doing a code review now.

2023-06-16 11:00 UTC, alexcreasy requested changes
There's the issue I mentioned above regarding prometheus calls when the feature flag is disabled. Otherwise there's just a few small code issues.

2023-06-16 14:33 UTC, alexcreasy commented
All good, thanks Juntao!

2023-06-16 14:37 UTC, merged