Rename configure to add
opendatahub-io/odh-dashboard pull request #1398
Opened 2023-06-15 13:11 UTC by manaswinidas

Fixes #1357 

## Description

<img width="836" alt="Screenshot 2023-06-15 at 6 38 41 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/22885912/8e0103f0-84ce-4081-a066-1af17761f547">
<img width="848" alt="Screenshot 2023-06-15 at 6 38 28 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/22885912/59d1be21-f0dc-4ceb-9c1c-258923b20791">

## How Has This Been Tested?

You can see the changes by going to the "Models and Model Servers" section of a Project

## Test Impact

## Request review criteria:

- [X] The commits have meaningful messages (squashes happen on merge by the bot).
- [X] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

2023-06-15 15:04 UTC, DaoDaoNoCode requested changes

2023-06-15 15:04 UTC, DaoDaoNoCode commented on frontend/src/pages/modelServing/screens/projects/ServingRuntimeListButtonAction.tsx
You might also need to update the `aria-label` and text in the Tooltip and text in the Button when `emptyTemplates` is true in this file.

2023-06-15 17:19 UTC, DaoDaoNoCode approved these changes
lgtm

2023-06-16 10:24 UTC, lucferbux reviewed
/lgtm

2023-06-16 10:28 UTC, merged