Improve performance of showing partial Pipelines and runs
opendatahub-io/odh-dashboard pull request #1452
Opened 2023-06-30 11:30 UTC by uidoyen

Closes #1248

## Description
Improve performance of showing partial Pipelines / associated Pipeline Runs by enabling pagination and limit the items. Also sort the pipelines and runs by `created_at`.

## How Has This Been Tested?
Created few sample pipelines on a different time frame to see the item order

## Test Impact

Pipelines:

<img width="1715" alt="Screenshot 2023-06-30 at 4 54 47 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/2117670/be190e13-10f7-4ade-a974-adfcaa1a6235">

Pipeline runs:
<img width="1724" alt="Screenshot 2023-06-30 at 4 54 12 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/2117670/a0f84ac4-23ec-4809-b776-477689f0288f">

## Request review criteria:

- [ ] The commits have meaningful messages (squashes happen on merge by the bot).
- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

2023-07-06 11:57 UTC, lucferbux requested changes
I think you are missing the point of the change.
The issue describes that we need to filter the pipelines k8s call but I think part of the goal of this issue is to improve performance by not fetching all the calls right?

2023-07-06 11:57 UTC, lucferbux commented on frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTable.tsx
> +import { sortByCreatedAt } from '~/utilities/sortByCreatedAt';
nit: Leave an empty space between imports and declaration

2023-07-06 11:57 UTC, lucferbux commented on frontend/src/utilities/sortByCreatedAt.ts
> +export const sortByCreatedAt = (pipeline) =>
pipeline is missing the type

2023-07-06 11:57 UTC, lucferbux commented on frontend/src/utilities/sortByCreatedAt.ts
> +  pipeline.sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
If this method is targeted only for pipelines, add it in the `utils` file within pipelines, if not, make this method generic.

2023-07-06 11:57 UTC, lucferbux commented
@uidoyen Can you rebase to get latest changes, there's a bug fix for an issue present in this PR (was in our codebase before)

2023-07-10 15:58 UTC, andrewballantyne requested changes
There are three views here:

* Projects Pipelines
* Global Pipelines
* Global Runs (scheduled and triggered)

There are two types of changes needed:

* Project Pipelines needs to limit to "5" because we fetching 20 has no value since we only want to show 5
* Project Pipelines & Global Pipelines show the last 5 runs inside the expanded section -- but fetch 20 and truncate client side

So we need to handle this truncation via **API** on the Project Pipelines for Pipelines & Runs. Global Pipelines we need to truncate via **API** for the expanded row's runs. Global Runs does not need to be changed for this issue.

We want to improve our fetching so we can get the "latest" from the API without having to fetch 15 more than we need. We can fetch 6 instead of 5 that we show if that's the easiest way to show the related "show more" links that take you to the Global Pipelines or Global Runs page (depending on what link you click on). 

This effort is to just limit fetching in _some_ cases for _some_ resources. We want our Global pages to show as much as it can for that given type. 

Hope this all makes sense, let me know if you have any questions.

2023-07-10 15:58 UTC, andrewballantyne commented on frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTableRow.tsx
> +  const runsFetchState = usePipelineRunsForPipeline(pipeline, 6);
No magic numbers

2023-07-10 15:58 UTC, andrewballantyne commented on frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx
> +        minPageSize={5}
Don't do this -- data should be limited if we need to truncate the data... don't force the tables to be smaller.

2023-07-10 17:27 UTC, andrewballantyne commented
@uidoyen Can you fix up your screenshots in your description?

2023-07-10 17:27 UTC, andrewballantyne requested changes
Couple notes

2023-07-10 17:27 UTC, andrewballantyne commented on frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTableExpandedRow.tsx
> +import { TABLE_CONTENT_LIMIT } from '~/const';
This is Pipeline specific, no need to make this global. We should keep things isolated as much as we can. 

Perhaps use `~/concepts/pipelines` instead?

2023-07-10 17:27 UTC, andrewballantyne commented on frontend/src/const.ts
> +export const LIMIT_MAX_ITEM_COUNT = 6;
```suggestion
// Get one more than the limit to help know if there are more than we want to show
export const LIMIT_MAX_ITEM_COUNT = TABLE_CONTENT_LIMIT + 1;
```

2023-07-10 20:05 UTC, andrewballantyne reviewed
Looks good code-wise and screenshot wise -- I have not tested it. 

/lgtm

2023-07-11 04:29 UTC, uidoyen commented
@pnaik1 @manaswinidas Can you guys test it please?

2023-07-11 05:22 UTC, pnaik1 commented
Okay @uidoyen

2023-07-11 09:58 UTC, pnaik1 commented
/lgtm

2023-07-11 11:21 UTC, lucferbux commented
Im gonna trigger again the checks and review it. Let's see if this time it doesn't fail

2023-07-11 15:58 UTC, lucferbux commented
Code looks great, requests have the query params that we wanted, I only have a nit, but I think is fine as it is right now.

<img width="789" alt="Screenshot 2023-07-11 at 17 53 10" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/8ee1ee22-c995-47ff-b400-4cbf3593e3c7">


As you can see in the response, the request return the total runs that you have, so `LIMIT_MAX_ITEM_COUNT` is not needed to show expanded, it can be achieved just fetching 5 and then checking if `total_size` is greater than `TABLE_CONTENT_LIMIT`.

I can imagine we haven't implemented this since `total_size` is optional and it might be missing in some scenarios right?

2023-07-11 15:58 UTC, lucferbux commented
But im gonna approve it anyways cause code looks great.

2023-07-11 15:58 UTC, lucferbux approved these changes
/lgtm

2023-07-11 16:08 UTC, lucferbux commented
I'm sorry @uidoyen I think you need to rebase interactively your PR to squash all the commits beforehand, we need to do this for ever pr for now own, please do that before merging

2023-07-13 10:51 UTC, pnaik1 commented
/lgtm

2023-07-13 14:45 UTC, manaswinidas approved these changes
The changes work fine for me.

/lgtm

2023-07-14 14:24 UTC, andrewballantyne approved these changes

2023-07-14 14:29 UTC, merged