Notebook Spawner reachable when disabled
opendatahub-io/odh-dashboard pull request #1505
Opened 2023-07-12 07:29 UTC by pnaik1

Closes: #1462 

## Description
#1462 
Not to be able to find a route to the notebookController part of the app when it is disabled.
![NotebookSpawner](https://github.com/opendatahub-io/odh-dashboard/assets/99238909/8a61ebd2-49d6-407c-a356-24e7fa9c7239)

## How Has This Been Tested?
Modifying the OdhDashboardConfig is required to test this.
Enable DS Projects spec.dashboardConfig.disableProjects = false
Disable NotebookController spec.notebookController.enable = false 
You can see in DS project , you cannot find a route to notebookController

## Test Impact
no test coverage

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2023-07-12 13:34 UTC, andrewballantyne requested changes
> Navigate to the DS Projects view, and click on the launch notebook button (both empty state and list state has the button)

You only got half of this no 3 point from the issue. Please get the empty state too.

2023-07-12 14:19 UTC, pnaik1 commented
@andrewballantyne my bad , I totally missed it

2023-07-12 15:19 UTC, pnaik1 commented
@andrewballantyne made the changes

2023-07-12 15:32 UTC, andrewballantyne commented
> @andrewballantyne made the changes

@pnaik1 please update your description with another screenshot

2023-07-12 15:39 UTC, pnaik1 commented
@andrewballantyne updated with screenshot

2023-07-12 18:36 UTC, andrewballantyne commented
@pnaik1 so you want to be on the lookout for text that is confusing if we don't have that functionality. We don't have Jupyter notebook and your screenshot says to the user they can use it -- which is not true.

@kywalker-rh @kaedward thoughts on the text -- We also have [two sets of text](https://github.com/opendatahub-io/odh-dashboard/blob/4c898c76d121c4f90d07902297aec5ebe08327d3/frontend/src/pages/projects/screens/projects/EmptyProjects.tsx#L31-L33), so I bet we need to update both scenarios (with and without self provision abilities).

2023-07-12 20:08 UTC, andrewballantyne commented
> Unless its disabled by something else, I think we should have the "Launch Jupyter" link button, then the text will make sense. Is it not included for a reason?

@kywalker-rh this is the issue, https://github.com/opendatahub-io/odh-dashboard/issues/1462 -- If you disable the tile, we still link to it from DS Projects. This issue is addressing that gap. We shouldn't link to something if you disable the Jupyter Tile.

2023-07-12 20:13 UTC, kywalker-rh commented
Thanks... now I know to click all the links in a PR. In this case I think we should simply remove the `or launch a notebook with Jupyter` text for both options of the page.

2023-07-13 08:12 UTC, pnaik1 commented
@andrewballantyne @kywalker-rh  I have  made the changes

2023-07-13 12:35 UTC, manaswinidas approved these changes
/lgtm

2023-07-13 12:39 UTC, andrewballantyne approved these changes
Das tested this... the code looks good to me.

I'm going to approve. My only remark is when we get to translations, we'll have to handle this text chunking better -- but that's an unknown distant future.

2023-07-13 12:42 UTC, merged