[WIP]Prevent No-Folder or root S3 model access
opendatahub-io/odh-dashboard pull request #1512
Opened 2023-07-13 09:54 UTC by manaswinidas

Fixes #1423 

## Description

1. Renamed "Folder Path" to "Path" 
2. Make "Path" a required field
3. Add helper text to "Path" field
<img width="818" alt="Screenshot 2023-07-13 at 3 15 19 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/22885912/14ea1684-b56a-4b40-950e-622d6e69845c">

## How Has This Been Tested?

1. Create a Model Server
2. Click on Deploy Modal
3. Fill out the data

## Test Impact

## Request review criteria:

Self checklist (all need to be checked):
- [X] The developer has manually tested the changes and verified that the changes work
- [X] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [X] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2023-07-18 13:26 UTC, manaswinidas commented
@vconzola @kywalker-rh @kaedward Is the text "Can either be a folder path or the path to a single model" alright?

Also, as discussed, I haven't added any inline alerts. Just enabling and disabling the "Deploy" button if the "Path" is a valid path as shown in the GIF. 

Here are the other alternatives:

With inline alert and validating tick in case of wrong input:

https://github.com/opendatahub-io/odh-dashboard/assets/22885912/9cc6173f-428d-4e32-8ad4-eb1597b1aac3

With a validating tick(without inline alert):

https://github.com/opendatahub-io/odh-dashboard/assets/22885912/fe3e9a25-952f-4772-a32a-b7eac5be5b4a

Let me know if any of these are a better option in place of the above GIF.

2023-07-18 15:19 UTC, DaoDaoNoCode requested changes

2023-07-18 15:25 UTC, DaoDaoNoCode commented
BTW, when editing, I can still see the `/` path.

<img width="940" alt="Screenshot 2023-07-18 at 11 24 35 AM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/61727214-42f0-4920-94c9-add3bb9abfd9">

2023-07-18 15:53 UTC, vconzola commented
@manaswinidas There are three allowable inputs, correct: (1) a model name in the root folder, (2) a folder path with no model name, or (3) a folder path + model name? If that's true, I prefer more specific helper text without the validation tick and only showing the error helper text when Deploy is selected. I find the helper text and tick changes while typing to be confusing.

I'd like @kaedward to share her opinion, but I think helper text that says something like, "This must be a model name, a folder path, or a folder path and model name." would work. If the input is invalid when the user selects deploy we would show error helper text that says something like, "Not a valid model name or folder path." in red with the error icon displayed in the field as shown here: https://www.patternfly.org/v4/components/helper-text/design-guidelines#when-to-use-helper-text.

2023-07-18 16:57 UTC, andrewballantyne commented
> There are three allowable inputs, correct: (1) a model name in the root folder, (2) a folder path with no model name, or (3) a folder path + model name? If that's true...

@vconzola yes that is correct

2023-07-18 17:52 UTC, manaswinidas commented
> BTW, when editing, I can still see the `/` path.
> 
> <img alt="Screenshot 2023-07-18 at 11 24 35 AM" width="940" src="https://user-images.githubusercontent.com/37624318/254313613-61727214-42f0-4920-94c9-add3bb9abfd9.png">

@DaoDaoNoCode Edit seems to work for me, let me know if I'm missing something

https://github.com/opendatahub-io/odh-dashboard/assets/22885912/550b3b19-761f-4681-9d90-c0a33c8436bd

2023-07-18 18:06 UTC, DaoDaoNoCode commented
@manaswinidas What if you had a model mounted with the empty path before? Try to edit that one.

2023-07-18 18:14 UTC, DaoDaoNoCode commented
Hmm, sounds fair. @andrewballantyne WDYT, do we need to consider the previously created models which could possibly mount on the root dir?

2023-07-18 18:17 UTC, andrewballantyne commented
> Hmm, sounds fair. @andrewballantyne WDYT, do we need to consider the previously created models which could possibly mount on the root dir?

I made a [thread in slack](https://redhat-internal.slack.com/archives/C043A9D5DMW/p1689704209069959) -- What is important to note is we need to consider how the flow impacts existing models.

What is the downside from having an "invalid" model deployed against the root `/`? If it locks up the mode from accepting any other inputs, we should address that with UX.

2023-07-18 21:00 UTC, kaedward commented
@andrewballantyne For the helper text, how about "Enter the path to a folder or single model."?

2023-07-19 14:36 UTC, andrewballantyne commented
> @andrewballantyne For the helper text, how about "Enter the path to a folder or single model."?

@kaedward Yeah, I guess we can go with that -- my only concern is technically I'd view `/` as a folder path heh... Could you sneak an extra couple words in there?

> Enter the path to a non-root folder or single model.

Feels weird still... but it's more technically accurate

2023-07-19 17:50 UTC, kaedward commented
@andrewballantyne does this sound any better? 
"Enter a path to a model or folder. This path cannot point to a root folder."

2023-07-19 19:20 UTC, andrewballantyne commented
Thanks @kaedward fits my mental model better... @manaswinidas please implement the last text noted by Katie.

> "Enter a path to a model or folder. This path cannot point to a root folder."

2023-07-19 19:26 UTC, manaswinidas commented
@andrewballantyne any other changes regarding the error helperText? I can see some comments above: https://github.com/opendatahub-io/odh-dashboard/pull/1512#issuecomment-1640498421

2023-07-19 19:43 UTC, andrewballantyne commented
> Also, a suggestion: it will be great if we can check whether the folderPath exists from the backend side(if it's not too far-fetched).

- https://github.com/opendatahub-io/odh-dashboard/issues/1271 🙂 

> @andrewballantyne any other changes regarding the error helperText? I can see some comments above: https://github.com/opendatahub-io/odh-dashboard/pull/1512#issuecomment-1640498421 or we stick to enabling the Deploy button when the input is valid?

@manaswinidas I don't follow what you're asking here -- if you're asking for more wording, pitch the scenario to @kaedward -- if you're asking for what we should do, I think Vince answered that 🤔 Let me know how I can help!

2023-07-19 19:50 UTC, manaswinidas commented
>If the input is invalid when the user selects deploy we would show error helper text that says something like, "Not a valid >model name or folder path." in red with the error icon displayed in the field as shown here: >https://www.patternfly.org/v4/components/helper-text/design-guidelines#when-to-use-helper-text.

@andrewballantyne I was just confirming whether there is a need for an error helperText as shown in the comment here. I think I confused Vince with the GIFs 😅

2023-07-19 21:08 UTC, kaedward commented
@manaswinidas I think error help text would be useful. Can we detect when an invalid path is entered, or only if the user enters a root folder?

2023-07-19 21:25 UTC, manaswinidas commented
We are preventing inputs like `/` or `/////` It needs to be some text that can contain `/` but not only `/`. As of now, I'm enabling the `Deploy` button if the `Path` is valid. Here's a GIF for your reference. Does this look good or it still needs an error helperText?

https://github.com/opendatahub-io/odh-dashboard/assets/22885912/e43c2e5b-9bea-4aa4-9bad-b7cb9bb99c6d

2023-07-20 08:46 UTC, manaswinidas commented
Also, @kaedward @andrewballantyne is there a need to mention the link to the docs for why we are preventing the root folder path? Here is the link to the docs: https://docs.openvino.ai/2023.0/ovms_docs_models_repository.html

2023-07-20 18:13 UTC, kaedward commented
@manaswinidas If it's not too much trouble, I think adding an error helper text would be helpful, even if it is only for when a root folder is entered. Maybe "The path must not point to a root folder."

I'm not sure the doc link is necessary here, but I'm open to including it.

2023-07-20 18:29 UTC, andrewballantyne commented
Let us not link to any docs -- if they break, we are on the hook to fixing it. We can document this through product documentation downstream and in the new website upstream -- we don't need to address this at the code level.

Works for me Katie -- on the error when root folder. cc @vconzola FYI we are shifting again on this.

2023-07-20 20:32 UTC, vconzola commented
@kaedward I don't understand where/when you're suggesting that error be displayed?

2023-07-21 11:10 UTC, manaswinidas commented
We have 2(or 3) options:
1. Show the error message while the user is typing the input. Do we still disable the "Deploy" button when the error is getting displayed? Or enable the "Deploy" button and make the user try to send the wrong input, and after they click on "Deploy"- show them the error. 
(My concerns in the first case: Changing the helperText to the error helperText while typing might confuse the user coz it draws attention

My concerns for the second case(disputed opinion): I've found it annoying a user when I get an error after clicking on the "Submit" button when the form/field could have shown the error while doing it, thus saving me time.)

2. Disable the "Deploy" button when the user types `/` or `/////` and enable it when the user types the correct input. 

Would you like me to send GIFs for some or all of these scenarios?

2023-07-21 13:01 UTC, andrewballantyne commented
> @kaedward I don't understand where/when you're suggesting that error be displayed?

@vconzola @manaswinidas @kaedward okay, let me step in here and cap this off. 

My suggested state of this modal is this, let me know if you agree.

For the folder field...
1. Empty initial state => show the empty field, deploy button is disabled (invalid input)
    * the red asterisk will help the user know the field is needed
    * the help text of "Enter a path to a model or folder. This path cannot point to the root folder."
3. If the user types `/` we show them the error under the field "The path must not point to a root folder."
    * The error goes away (and the button enables -- if the rest of the modal is good) when they continue `/<any character>` -- eg `/a`
    * We stay in error if they type more than 1 `/` -- `///////` scenario; even if they type `////<any character>`
    * We show the error using PF field validation ([link](https://www.patternfly.org/v4/components/form#invalid))
4. If the user straight up types a non slash character, we don't show anything in the field but we enable the button (if the rest of the modal is good)
    * I think it's important we don't use success validation here because we are not validating the validity of the path

Does that make sense to everyone? If not, let us take this to slack (or a meeting), and it'll likely need more back and forth.

2023-07-24 19:45 UTC, vconzola commented
@andrewballantyne @manaswinidas @kaedward I'm OK with everything @andrewballantyne suggested with one exception. i think it's going to look weird if we immediately show the error as soon as the user types"/". It could cause the error message to flash briefly if they don't type the next, non-/ character quickly enough. Can we add a short (500 ms to 1 s - will probably need to play around with it to see what feels right) delay before displaying the error below the field?

2023-07-25 13:31 UTC, manaswinidas commented
@kaedward @vconzola Do we have a success helperText too or just the default helperText "Enter a path to a model or folder. This path cannot point to the root folder." will do?

2023-07-25 13:50 UTC, vconzola commented
@manaswinidas We don't need any success helperText - only if there's an error.

2023-07-25 15:20 UTC, manaswinidas commented
@vconzola @kaedward Final GIF:

https://github.com/opendatahub-io/odh-dashboard/assets/22885912/b8637985-b489-4a67-b107-e3cbf6c537a3

2023-07-25 15:39 UTC, vconzola commented
lgtm

2023-07-26 13:28 UTC, manaswinidas commented
> For what it is worth -- don't put success intentionally. We are not validating the value, we are just helping them avoid known failure points. Success would mislead the user to think we know if their folder path is accurate -- which we do not.

I was reiterating the same yesterday, we don't have a success helperText and the check mark in the textbox for the same reason. Also, I've added a 1s delay, let me know if that needs to be changed. [This comment](https://github.com/opendatahub-io/odh-dashboard/pull/1512#issuecomment-1650046750) has the latest GIF.

2023-07-26 13:34 UTC, andrewballantyne requested changes

2023-07-26 13:34 UTC, andrewballantyne commented on frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionFolderPathField.tsx
> +  type validate = 'success' | 'warning' | 'error' | 'default';
Types are always PascalCase

Also, why do you need this? Infer the data from PF. 

```
React.ComponentProps<typeof FormGroup>['validated']
```

That should get you the value behind the prop of FormGroup's prop `validated`.

2023-07-26 13:34 UTC, andrewballantyne commented on frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionFolderPathField.tsx
> +      } else if (folderPath === '/' || folderPath.includes('//')) {
If you get into an error -- I think you're going to not get out of it on `paste`... can you switch your logic around `if` this, `else` set back to default?

2023-07-27 14:04 UTC, andrewballantyne reviewed
Thanks for making the changes -- you really should use PascalCase for your Type variables... but this solves the real problem I saw. 

/approve

Give me a moment to spin up my UI to test it, but should work fine.

2023-07-27 15:22 UTC, lucferbux approved these changes
/lgtm

2023-07-27 15:35 UTC, merged

2023-07-27 18:02 UTC, manaswinidas commented
Issue logged for changes discussed in https://github.com/opendatahub-io/odh-dashboard/pull/1512#issuecomment-1652037627 : https://github.com/opendatahub-io/odh-dashboard/issues/1601