Update modals and generate meaningful k8s name for images
opendatahub-io/odh-dashboard pull request #1529
Opened 2023-07-17 20:57 UTC by DaoDaoNoCode

Closes #1433 #1435 #1388 

## Description

This PR did the following things:
1. Add the comment back as mentioned in https://github.com/opendatahub-io/odh-dashboard/pull/1506#discussion_r1265789708 since we are not going to fix it in this phase and I removed it by mistake
2. Enhance the status toggle of `Enable` column in the table, for the error images, it will set default to disabled and the user cannot enable it. Also, add the sort to the `Enable` column as @vconzola requested here https://github.com/opendatahub-io/odh-dashboard/pull/1506#issuecomment-1633095279

<img width="698" alt="Screenshot 2023-07-17 at 4 38 58 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/36117267-7fd2-4f3d-a12c-e7ca666c3f12">

3. Generate a meaning k8s name for the image stream that user imports, before the change, it was `byon-${timestamp}`, but now it's `custom-${translated-k8s-name}` where `translated-k8s-name` is the translation of the display name that user inputs. Also, add a tooltip next to the image name so the user could easily locate the image stream resource on the cluster.

<img width="698" alt="Screenshot 2023-07-17 at 4 45 23 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/74381bfb-f995-407c-9877-0c6b1c1854d4">

4. Refactor the Import/Update modal of the custom notebook images, change the labels, and add helper text/tooltips based on the mockups

<img width="940" alt="Screenshot 2023-07-17 at 4 47 59 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/698e89b1-5bb9-45ae-9684-9dc54d073242">

Highlights: Refactor the table for adding/editing packages and software in the modal. Take the software as an example, when the user starts to add software or edit software, he will be in the edit mode, which only allows the user to confirm or abandon the current change (the user cannot edit multiple lines at the same time and cannot submit or exit the modal). 

What's more, when the user hits `Enter` in the edit mode, it will automatically confirm the current row and move to the next row. If the row is already the last row, it will create a new entry, which helps the user to quickly input and move on without clicking with the mouse every time. When the user hits `Esc` in the edit mode, it will abandon the current change of the row and exit the edit mode.

## How Has This Been Tested?

1. Try to create some images with the correct path (like `quay.io/opendatahub/workbench-images:jupyter-minimal-ubi8-python-3.8-pr-89`) and incorrect path (like `quay.io/opendatahub/workbench-images:invalid-tag`) and you could check the status of the toggle on the `Enable` column. Try to create more and sort by the `Enable` column
2. Try to import/edit the image in every situation, play around with the edit mode of the software/packages

## Test Impact

TBD

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2023-07-17 21:01 UTC, DaoDaoNoCode commented
@vconzola Could you please check the UX updates in this PR? Thanks!

2023-07-18 18:05 UTC, vconzola commented
lgtm

2023-07-18 19:38 UTC, manaswinidas approved these changes
Tested all changes on my end, looks fine.

/lgtm

2023-07-19 19:00 UTC, andrewballantyne requested changes
Some changes needed

2023-07-19 19:00 UTC, andrewballantyne commented on frontend/src/pages/BYONImages/utils.ts
> +  image.visible && !image.error ? 1 : image.error ? -1 : 0;
Please use an enum -- magic numbers, especially ones you want to type a comment about, should be handled with descriptive code (like enums)

2023-07-19 19:23 UTC, DaoDaoNoCode commented on frontend/src/pages/BYONImages/BYONImageModal/ManageBYONImageModal.tsx
> +  const [editIndex, setEditIndex] = React.useState<number>();
I considered that actually... I was just trying to refactor less for the first round 😁 but I can change it to use that hook if you think it's necessary.

2023-07-19 19:24 UTC, andrewballantyne commented on frontend/src/pages/BYONImages/BYONImageModal/ManageBYONImageModal.tsx
> +  const [editIndex, setEditIndex] = React.useState<number>();
Entirely up to you -- this was a throwaway comment, I just thought it was funny given we worked on that effort together and it was to solve this *exact* case lol

2023-07-19 19:27 UTC, DaoDaoNoCode commented on frontend/src/pages/BYONImages/BYONImageModal/ManageBYONImageModal.tsx
> +  const [editIndex, setEditIndex] = React.useState<number>();
I forget things so easily... 🥲 I will try to pay more attention in the future to hope something crash into my mind when implementing a feature

2023-07-19 20:12 UTC, DaoDaoNoCode commented on frontend/src/concepts/dashboard/DashboardSmallTextList.tsx
Yeah maybe I will just make this into a component instead of the `DashboardSmallTextList` as the component, I only need to add an inline style for the text so I think maybe the generic component is not needed.

2023-07-21 15:32 UTC, DaoDaoNoCode commented on frontend/src/concepts/dashboard/DashboardInlineHelpIcon.tsx
After a discussion with @Gkrumbach07, this feature will be implemented in his PR https://github.com/opendatahub-io/odh-dashboard/pull/1561. I will remove this generic component here and go with the `Popover` + `HelpIcon` for now and look for a replacement in the future.

2023-07-25 15:30 UTC, andrewballantyne reviewed
Looking good... let me run a few visual tests. One question...

2023-07-25 15:30 UTC, andrewballantyne commented on frontend/src/pages/BYONImages/BYONImagesTableRow.tsx
>            </Flex>
This seems like you'll not get spacing, why this change?

2023-07-25 15:48 UTC, andrewballantyne commented
I think this works great overall. 

However, we should have a sit down with UX and get feedback on the keyboard actions. I'm not sure I like the escape/enter action flows -- double escape closes the modal without warning. Keyboard flow doesn't really get you back in once you escape out (we should probably focus the "add software" at that point -- but it is the next tab index so it's reasonable)

I think we are already are aware of the issue with a bad image -- I just worry it tosses _everything_ away and it's not just inconvenient for an image name. Which I think now with the added flow of keyboard actions, one could quickly lose more.

Probably useful to incubate these and get feedback across the board on them though.

2023-07-25 15:49 UTC, andrewballantyne approved these changes

2023-07-26 21:26 UTC, andrewballantyne reviewed
FYI

2023-07-26 21:26 UTC, andrewballantyne commented on frontend/src/pages/BYONImages/BYONImagesTableRow.tsx
>            </Flex>
FYI, you're going to run into a conflict -- Gage kept the `FlexItem`s. Perhaps you should match his implementation to avoid conflicts

2023-07-27 14:28 UTC, DaoDaoNoCode commented on backend/src/routes/api/images/imageUtils.ts
> +};
Actually, I find I don't need this `||` at all, it will return `''` or `undefined` anyway. I will update it.

2023-07-27 17:50 UTC, andrewballantyne commented on backend/src/routes/api/images/imageUtils.ts
> +};
I provided my feedback to Juntao on slack... this change is a NPE waiting to happen (although it does seem unlikely in the current form of the code)

2023-07-27 20:24 UTC, andrewballantyne commented
/approve

@DaoDaoNoCode get someone else on the team to verify it again, I unfortunately lost my window to test the code again. Looks good though, thanks for making the desired changes.

2023-07-27 20:29 UTC, DaoDaoNoCode commented
@andrewballantyne Sure, let me squash the commits first.

2023-07-28 19:54 UTC, Gkrumbach07 reviewed
it all works as described. few UX related issues though, not breaking.
- invalid images will show enabled but be greyed out, you have to refresh for the UI to correct itself and show it to be not enabled and greyed out.
- when adding software/packages, in edit mode for a row
     1. make edits in one of the text boxes
     2. cancel with either the X button or ESC 
     3. edit the row again
     4. the last edits that were canceled are still there

2023-07-31 19:45 UTC, Gkrumbach07 commented
/lgtm

2023-07-31 19:49 UTC, merged