Show error message correctly in manage storage modal
opendatahub-io/odh-dashboard pull request #1679
Opened 2023-08-15 17:52 UTC by DaoDaoNoCode

Closes #1565 

## Description

As I commented in the original issue, there is nothing we can do with the PVC storage update, but we did wrongly digest the error message which would cause confusion to the users. The way is just to correctly show the error message in the modal.

<img width="1726" alt="Screenshot 2023-08-15 at 1 48 46 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/dc11e17e-d0c9-4015-852e-0421fb1101e8">

## How Has This Been Tested?

1. Go to a data science project
2. Create a cluster storage
3. Don't connect it to any notebook, and try to increase the capacity
4. You should be able to see the error message

## Test Impact

N/A, it's a fix to show the network failure call, which is commonly used across all the modals

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2023-08-16 20:41 UTC, christianvogt requested changes
Error shows up as expected. 

Without performing dry runs, there's now a slightly odd behavior when the user encounters the error when changing the PVC size. If they also changed the name or description along with the PVC size, the error will occur but the name and description changes will have gone through already. If the user now closes the modal, these new values are not reflected in the UI. They continue to see the old values. This wasn't the case before.

Ideally a dry run could be performed for the k8s changes to weed out known errors in the data before performing a full submission. However such changes are a bit beyond the scope of the issue at hand.

2023-08-16 20:41 UTC, christianvogt commented on frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.tsx
> +            pvcPromises.push(attachNotebookPVC(notebookName, namespace, pvcName, mountPath.value));
Shouldn't you return the promise from `attachNotebookPVC` ?
```suggestion
            return attachNotebookPVC(notebookName, namespace, pvcName, mountPath.value);
```

2023-08-16 20:41 UTC, christianvogt commented on frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.tsx
> +            attachNotebookPVC(notebookName, namespace, createdPvc.metadata.name, mountPath.value);
Same question:
```suggestion
            return attachNotebookPVC(notebookName, namespace, createdPvc.metadata.name, mountPath.value);
```

2023-08-29 13:49 UTC, DaoDaoNoCode commented
Close this PR because the issue will be fixed in #1714 along with the comments above.

2023-08-29 13:49 UTC, closed without merging