Missing Duplicate Run from Triggered Action Menu
opendatahub-io/odh-dashboard pull request #1715
Opened 2023-08-29 14:26 UTC by dpanshug

Closes #1568

## Description
Action menu of Runs triggered page updated with "Stop run" & "Duplicate run" which is same as in Pipeline Run detail page.

![image](https://github.com/opendatahub-io/odh-dashboard/assets/97534722/a5cb12e6-48c0-4ba6-959a-59e7926b9bd5)

## How Has This Been Tested?
1. Create workbench and upload a pipeline.
2. Create run with Run type: Run once immediately after creation
3. Move back to Runs page, on Triggered tab.
4. Click on action menu on any row.
5. New actions added "Stop run", "Duplicate run".
6. "Stop run" is disabled when pipeline not running.
7. Click on both actions to run them.

## Test Impact

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2023-08-29 14:32 UTC, dpanshug commented
There is no alert that appears after clicking on the "Stop run" action, which could be confusing for users and they may try to click again on it. Would you like me to add an alert popover to provide more clarity? This issue also seems to be present on the Pipeline run details page.

2023-08-29 14:40 UTC, lucferbux commented
@dpanshug Can you fix the linting issues please?

2023-08-29 14:40 UTC, dpanshug commented
> @dpanshug Can you fix the linting issues please?

Yes, I already did it, pls refresh.

2023-08-31 11:03 UTC, lucferbux commented
> There is no alert that appears after clicking on the "Stop run" action, which could be confusing for users and they may try to click again on it. Would you like me to add an alert popover to provide more clarity? This issue also seems to be present on the Pipeline run details page.

If you have this kind of questions, just ping UX, you can check who [here](https://github.com/opendatahub-io/odh-dashboard/commit/28315f8525f691815ed79445a19ff4a31fa1a2c4) in this case @yannnz

2023-08-31 11:10 UTC, lucferbux commented
@dpanshug After checking the code, it seems that we don't show a modal in the details page of the run, not sure if intentionally, but it would be safer to ask to @andrewballantyne too

2023-08-31 12:53 UTC, andrewballantyne commented
> @dpanshug After checking the code, it seems that we don't show a modal in the details page of the run, not sure if intentionally, but it would be safer to ask to @andrewballantyne too.

@lucferbux @dpanshug can one of you post a screenshot and tag Yan for followup. Your PR description lacks any modal images 🤔

2023-09-01 06:51 UTC, yannnz commented
- For the Kebab options, the only concern are the content. Under the Scheduled runs, we call `Duplicate` without `Run`, so I think to follow suit, we can name the two options `Duplicate` and `Stop`for consistency. 

<img width="1276" alt="Screenshot 2023-09-01 at 14 34 20" src="https://github.com/opendatahub-io/odh-dashboard/assets/10469467/4a9071db-2135-4b75-8d9a-881a0ef52019">

- The other thing I realized when checking the Implemented UI is that there is a responsive problem of the Triggered Run tag. I didn't see the kebabs when I firstly landed this tab. See the screenshot below. I need to stretch my browser wide enough to realize there are kebabs of the table rows, but then I cannot see the navigation in my screen. 
- 
<img width="1539" alt="Screenshot 2023-09-01 at 14 33 20" src="https://github.com/opendatahub-io/odh-dashboard/assets/10469467/15c3d476-4f1d-45fb-81ff-aec5ad90ea91">
<img width="1710" alt="Screenshot 2023-09-01 at 14 41 54" src="https://github.com/opendatahub-io/odh-dashboard/assets/10469467/4b3c029c-592f-48dc-afdb-d6b31d30498c">

- For the notification, what happened after the user clicked `Stop`? Will we have a modal to ask the user to confirm they are stopping a run? How long does it take to stop a run in general? Will we allow the user to retry a stopped run. We will also need to updat the status icon of a stopped run. 
Some screenshots from KBF to explain my questions:
<img width="1286" alt="Screenshot 2023-09-01 at 14 45 45" src="https://github.com/opendatahub-io/odh-dashboard/assets/10469467/b6c58873-91c0-49f2-9a63-e53da9f7f919">
<img width="1511" alt="Screenshot 2023-09-01 at 14 46 17" src="https://github.com/opendatahub-io/odh-dashboard/assets/10469467/a3f121cc-018f-4fe4-aa1d-f6edb8fed4b7">

2023-09-01 08:08 UTC, dpanshug commented
@yannnz Answering your questions.

1. Yes we can remove `run` to keep consistency.
2. I also found this issue, when pipeline name is too long. I will report another issue for it.
3. Having a model will be good for `Stop` action, @andrewballantyne wdyt?

2023-09-01 14:13 UTC, andrewballantyne commented
@dpanshug https://github.com/opendatahub-io/odh-dashboard/issues/1182 is the issue we had for the table. I found it during development and then couldn't find it after the fact. We should probably reopen that one and detail out any information you have to help narrow the reproduce use-case.

2023-09-01 18:54 UTC, andrewballantyne commented
> Having a model will be good for Stop action, @andrewballantyne wdyt?

@yannnz @dpanshug Interesting, I guess I never thought about it. Stopping a Pipeline isn't something I'd waste time saying "are you sure?". But also not something I think would be too problematic if it did take a moment. Only downside with the modal is "I want to stop it, but it takes 3 seconds because I need to deal with the modal". We have a stop workbench modal too -- but it has the option to be fully disabled (indefinitely).

Do you feel it's needed right now? Can we swing back and figure out if it's needed / what features are needed? We don't have the functionality today to use a modal afaik.

2023-09-04 03:52 UTC, yannnz commented
It brings up the 3rd question I have. Will we allow the user to retry/restart a stopped run?  I don't find it in KBF somehow. I think if we allow the user to restart a stopped run, it will prevent an stop action triggered by accident. Allowing the user to retry the stopped run would be better than a confirmation modal, which the run might already finished when they finished dealing with the modal. WDYT?  


> 
> @yannnz @dpanshug Interesting, I guess I never thought about it. Stopping a Pipeline isn't something I'd waste time saying "are you sure?". But also not something I think would be too problematic if it did take a moment. Only downside with the modal is "I want to stop it, but it takes 3 seconds because I need to deal with the modal". We have a stop workbench modal too -- but it has the option to be fully disabled (indefinitely).
> 
> Do you feel it's needed right now? Can we swing back and figure out if it's needed / what features are needed? We don't have the functionality today to use a modal afaik.

2023-09-06 18:28 UTC, andrewballantyne commented
Added #1282 to the PR and assigned you @dpanshug -- you don't need to do anything, both issues are related to the work you are doing here.

2023-09-06 18:31 UTC, andrewballantyne commented
> Will we allow the user to retry/restart a stopped run?

@yannnz we sorta can -- I imagine code-wise it should be a matter of just running it through the dupe flow. Biggest concern is "what do we call the run?" -- everything else is more-or-less just going to be duplicated. 

Essentially though, this is a duplicate flow. There is no way to "restart" a completed or on-going resource -- stopped or not. 

So if duplicate is not enough for your desired flow, could you log a feature request asking for a specific "restart" flow. Essentially the biggest code question would be, what do we name it if we don't just push them through the duplicate flow.

2023-09-12 11:22 UTC, manaswinidas requested changes
Can you squash both the commits? Is this an empty file `frontend/src/concepts/pipelines/content/StopPipelineRunModal.tsx`? Is this WIP?

2023-09-12 12:05 UTC, dpanshug commented
> Can you squash both the commits? Is this an empty file `frontend/src/concepts/pipelines/content/StopPipelineRunModal.tsx`? Is this WIP?

That was an error, i've removed the file now.

2023-09-12 12:08 UTC, dpanshug commented
As [discussed](https://redhat-internal.slack.com/archives/C043A9D5DMW/p1694509294772539?thread_ts=1693319674.006859&cid=C043A9D5DMW) with @yannnz, the modal for stopping run will be decided in separate issue. cc @andrewballantyne

2023-09-13 03:18 UTC, yannnz commented
@christianvogt  Yes thanks for reminding it. We had discussion above that the terminologies need to be consistent with the table row kebab menu. cc: @dpanshug

> @yannnz Answering your questions.
> 
> 1. Yes we can remove `run` to keep consistency.
> 2. I also found this issue, when pipeline name is too long. I will report another issue for it.
> 3. Having a model will be good for `Stop` action, @andrewballantyne wdyt?

2023-09-22 14:06 UTC, christianvogt commented
@dpanshug - As requested, could you make updates to `PipelineRunDetailsActions` for `Stop run` and `Duplicate run` for consistency with the kebab menu actions.

As for the confirmation modal, we can make those changes in a followup PR since the current actions don't currently display any modal. This request also needs to still be confirmed by @andrewballantyne and @yannnz. Therefore I do not want to hold up this PR.

2023-09-22 14:33 UTC, andrewballantyne commented
Definitely omit the concern about the stop modal from this PR -- see https://github.com/opendatahub-io/odh-dashboard/issues/1848 for the followup.

2023-09-25 07:41 UTC, dpanshug commented
> @dpanshug - As requested, could you make updates to `PipelineRunDetailsActions` for `Stop run` and `Duplicate run` for consistency with the kebab menu actions.

Changes made :heavy_check_mark: @christianvogt

2023-09-25 13:12 UTC, christianvogt commented
/lgtm
/approve

2023-09-25 13:15 UTC, merged