Adapt custom serving runtimes to KServe
opendatahub-io/odh-dashboard pull request #1969
Opened 2023-10-16 19:34 UTC by DaoDaoNoCode

Closes #1912 

## Description

The PR did the following things:
1. Add a required select dropdown when adding/editing custom serving runtimes, you can not click submit without selecting a value

<img width="1727" alt="Screenshot 2023-10-16 at 3 28 19 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/55387dc6-d3e3-4006-9c1b-e562cb3cc8ec">

2. Add a column to show the supported platform of the custom serving runtimes

<img width="1727" alt="Screenshot 2023-10-16 at 3 28 33 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/b9640078-9bde-45fc-a328-301587e6e366">

**TODO:**
1. Add the search input to the table view
2. Add the labels and popover in the page header along with https://github.com/opendatahub-io/odh-dashboard/issues/1913 because we need the logic there

## How Has This Been Tested?

1. Go to the custom serving runtimes page
3. Make sure the OOTB serving runtimes have both labels shown because they don't have the `opendatahub.io/modelServingSupport` annotation
4. Try to duplicate one of the serving runtimes, make sure you cannot submit without selecting a platform
5. Select a platform and create one
6. Make sure the label is correct
7. Try to edit the serving runtime again, choose a different option, and submit
8. Make sure the label is changed too

## Test Impact

Add the storybook test for the custom serving runtimes page and check the labels, more tests to be added along with the feature development.

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2023-10-16 19:35 UTC, DaoDaoNoCode commented
@vconzola Can you check the screenshots when you are available? Thanks!

2023-10-17 12:47 UTC, lucferbux commented
@DaoDaoNoCode first of all, I've approved https://github.com/opendatahub-io/odh-dashboard/pull/1936 can you then rebase it and check the integration is working?

2023-10-17 12:48 UTC, lucferbux commented
I'm gonna update something of the requirements, just to do the follow up

2023-10-17 12:59 UTC, lucferbux commented
Ok, @DaoDaoNoCode I've created https://github.com/opendatahub-io/odh-dashboard/issues/1973 to do a follow up, let's just get this and then get the other section so we are unblocked asap.

2023-10-17 16:21 UTC, lucferbux requested changes
Just small nits, i think you can get this in no time

2023-10-17 16:21 UTC, lucferbux commented on frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAddTemplate.tsx
> +            <CustomServingRuntimePlatformsSelector
Mmmmmm I'm trying to follow the logic, but somehow when clonning the Serving Runtime it doesn't update the platform selected

2023-10-17 16:21 UTC, lucferbux commented on frontend/src/__tests__/integration/pages/customServingRuntimes/CustomServingRuntimes.stories.tsx
> +                  platforms: [ServingRuntimePlatform.MULTI],
Add one example more with no annotations to cover the state of a template not having platforms.

2023-10-17 16:21 UTC, lucferbux commented on frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeListView.tsx
> +  // TODO: add search functions
Don't add the TODO here, let's just control that with tickets, im gonna start a conversation to track this cause im not sure if we want that.

2023-10-18 21:18 UTC, DaoDaoNoCode commented
I updated this PR so #1973 will be also implemented here, I updated the screenshot in the description. Also, I addressed all the comments above, could you check it again? @lucferbux

2023-10-19 07:58 UTC, merged