Model status will never update if the runtime pod is unschedulable
opendatahub-io/odh-dashboard pull request #2004
Opened 2023-10-23 10:23 UTC by pnaik1

Closes: #1548  

## Description

## How Has This Been Tested?

## Test Impact

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2023-12-18 08:22 UTC, dpanshug requested changes

2023-12-18 08:22 UTC, dpanshug commented on frontend/src/pages/modelServing/screens/global/utils.ts
> +export const checkModelStatus = (model: PodKind) => {
Add return type

2023-12-18 08:22 UTC, dpanshug commented on frontend/src/pages/modelServing/screens/global/utils.ts
> +export const useModelStatus = (namespace: string, name: string, isKserve: boolean) => {
Move this hook to separate file and add return type to function

2023-12-18 08:22 UTC, dpanshug commented on frontend/src/pages/modelServing/__tests__/modelPod.spec.ts
> +  FailedToSchedule: status,
```suggestion
  failedToSchedule: status,
```
make this in camel case

2023-12-18 08:22 UTC, dpanshug commented on frontend/src/pages/modelServing/screens/global/utils.ts
> +  FailedToSchedule: boolean;
also here, make this camel case

2023-12-22 10:32 UTC, lucferbux requested changes
Logic works really great, I've tried with both kserve and modelmesh and it's working as expected, just take a look at the mocking data, we can improve that part a little bit, once that's done we can merge it!

2023-12-22 10:32 UTC, lucferbux commented on frontend/src/__mocks__/mockPodK8sResource.ts
> +export const mockUnscheduledPodK8sResource = ({
Just use the other one and parametrize the attributes there.

2024-01-03 13:10 UTC, lucferbux approved these changes
/lgtm

Great work!

2024-01-03 13:14 UTC, merged