[WIP] Move RoleBinding DSPO Role to Notebook Service Account to Server
opendatahub-io/odh-dashboard pull request #2028
Opened 2023-10-30 09:16 UTC by pnaik1

Closes: #1420 

## Description

## How Has This Been Tested?

## Test Impact

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2023-11-07 05:25 UTC, pnaik1 commented
@andrewballantyne , Can you please take a look at this , whenever you find some time?

2023-11-17 18:15 UTC, andrewballantyne requested changes
Please fix the linter issue:
![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/822103a7-e640-4e96-b25d-751a8206f2dc)

---

@pnaik1 we should be talking on slack before posting a PR like this. You don't seem to really have gone after addressing the issue. You copied some stuff to the server, added a odd endpoint and then wrote tests to make sure axios is called in a method that just calls axios?

Also, waiting for me specifically for a review is a poor way to get your code reviewed. I've not been available for real reviews for many months.

2023-11-17 18:15 UTC, andrewballantyne commented on backend/src/routes/api/notebooks/utils.ts
> +export const getElyraServiceAccountRoleBindingName = (notebookName: string): string =>
You duplicated the logic? Why didn't you just move the logic? The frontend code is no longer used now.

2023-11-17 18:15 UTC, andrewballantyne commented on frontend/src/concepts/pipelines/elyra/__tests__/utils.spec.ts
Why did you write a test to verify axios triggered a request? Where are the tests for the utils you moved to the backend? I'm confused at why you didn't use the `__mocks__ ` for notebook?

2023-11-17 18:15 UTC, andrewballantyne commented
I feel this PR should require more conversations before posting. I'm going to close it and we can readdress this effort from Slack.

2023-11-17 18:15 UTC, closed without merging