Inconsistent behaviour when model name is too long in Model Serving
opendatahub-io/odh-dashboard pull request #2029
Opened 2023-10-30 13:29 UTC by dpanshug

Closes: #1550 

## Description
Added warning and made Deploy button disable when model name exceeds 63 chars.

![Screenshot from 2023-10-30 18-21-52](https://github.com/opendatahub-io/odh-dashboard/assets/97534722/a5a2f779-9d22-421c-bec0-dfd0c56400c0)

## How Has This Been Tested?
1. Create project and add a model server.
2. In the Models and model server section click "Deploy model"
3. Enter model name with more than 63 chars eg: (Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod) and you can see the error mentioned and deploy button disabled.

## Test Impact
Integration testing: Added case in Model Serving Global test to check if the model name is no more than 63 chars.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

@vconzola

2023-10-30 18:26 UTC, vconzola commented
@dpanshug The error text should simply say, "Cannot exceed 63 characters." And ideally the interaction would be to stop accepting input at 63 characters and display the error as soon as the user tries to type the 64th character. Is that the way it works? I can't tell from a screenshot.

2023-10-31 06:04 UTC, dpanshug commented
> And ideally the interaction would be to stop accepting input at 63 characters and display the error as soon as the user tries to type the 64th character. Is that the way it works?

@vconzola Yes.

[Screencast from 2023-10-31 11-31-49.webm](https://github.com/opendatahub-io/odh-dashboard/assets/97534722/542c06f7-3a05-4315-85cb-34a972779a5c)

2023-10-31 12:53 UTC, manaswinidas reviewed
@dpanshug Can you update the screenshot in the PR description?

2023-10-31 13:48 UTC, manaswinidas commented
/lgtm

Works fine for me.

2023-10-31 15:20 UTC, vconzola commented
@dpanshug One more, small thing. Since we're restricting character input to 63 characters, it's not really an error. The field state and text should be Info, if that's available. If Info is not an option, it should be Warning.

2023-11-06 12:15 UTC, dpanshug commented
> @dpanshug One more, small thing. Since we're restricting character input to 63 characters, it's not really an error. The field state and text should be Info, if that's available. If Info is not an option, it should be Warning.

Info is not available, the fields available are only `'success' | 'warning' | 'error' | 'default'` so making this as a warning. Screenshot updated

2023-11-06 14:48 UTC, manaswinidas reviewed
/lgtm

2023-11-06 14:56 UTC, manaswinidas requested changes

2023-11-06 14:56 UTC, manaswinidas commented on frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
> +  const isNameWithinLimit = createData.name.trim().length <= 63;
last nit: `Name` is generic. Can you change it to `InferenceServiceName` ?

2023-11-06 16:11 UTC, lucferbux requested changes

2023-11-06 16:11 UTC, lucferbux commented on frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
> +  const isInferenceServiceNameWithinLimit = createData.name.trim().length <= 63;
shouldn't be this checked with `translateDisplayNameForK8s`, since the k8s resource would add hyphens right?

2024-01-09 10:53 UTC, lucferbux approved these changes
/lgtm

2024-01-10 14:00 UTC, lucferbux commented
@dpanshug check out the issue here:

`/home/runner/work/odh-dashboard/odh-dashboard/frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceNameSection.tsx
Error:   39:15  error  Curly braces are unnecessary here  react/jsx-curly-brace-presence`

2024-01-10 14:41 UTC, lucferbux commented
/lgtm

Let's see if this works

2024-01-10 14:44 UTC, merged