Display error message on enabling TrustyAI via UI
opendatahub-io/odh-dashboard pull request #2036
Opened 2023-10-31 14:31 UTC by ppadti

Closes: #1996 

## Description
This PR aims to display error message on enabling TrustyAI via UI.

![Screenshot from 2023-10-31 19-21-23](https://github.com/opendatahub-io/odh-dashboard/assets/99261071/9c71ded3-7ada-4bbe-8680-d3d0e01e2e64)

## How Has This Been Tested?
1) Create a Data Science Project
2) Navigate to DSP page
3) Click Settings
4) Check the Enable TrustyAI checkbox, you will show the error (only if  TrustyAIService CRD not installed on your cluster)

## Test Impact
NA

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2023-10-31 18:25 UTC, manaswinidas reviewed
/lgtm

this works fine

2023-10-31 20:02 UTC, pnaik1 commented
Works fine
/lgtm
![Screenshot from 2023-11-01 01-29-33](https://github.com/opendatahub-io/odh-dashboard/assets/99238909/6ac93159-7802-418f-85b0-4fd0f5722e12)

2023-10-31 20:26 UTC, andrewballantyne commented
@alexcreasy this might be benefited from us making use of my #2032 PR to just straight up hide the checkbox.

We'll need to probably pivot to that over time, this may be okay for now if you approve of it.

2023-11-01 13:39 UTC, alexcreasy requested changes

2023-11-01 13:39 UTC, alexcreasy commented on frontend/src/pages/projects/projectSettings/ModelBiasSettingsCard.tsx
> -          {error?.message}
You need to check that the error code is a 404 before displaying this message - if the error code is anything else you should display the message as the service would have failed for a different reason.

2023-11-01 13:44 UTC, alexcreasy commented
> @alexcreasy this might be benefited from us making use of my #2032 PR to just straight up hide the checkbox.
> 
> We'll need to probably pivot to that over time, this may be okay for now if you approve of it.

@andrewballantyne thanks for the comment, if I'd read it earlier it would have bypassed a whole slack conversation lol. I'm still going to approve this PR (pending changes) as it fixes a flaw in the current implementation and at least makes this usable for now. I'd like to look at utilising your PR as a priority afterwards when possible.

2023-11-06 11:23 UTC, alexcreasy requested changes

2023-11-06 11:23 UTC, alexcreasy commented on frontend/src/pages/projects/projectSettings/ModelBiasSettingsCard.tsx
> +          {error?.message.includes('404')
```suggestion
         // This is a temporary fix, this should be updated to incorporate work from https://github.com/opendatahub-io/odh-dashboard/pull/2032 in the future to provide a better experience.
          {error?.message.includes('404')
```

2023-11-06 11:23 UTC, alexcreasy commented on frontend/src/pages/projects/projectSettings/ModelBiasSettingsCard.tsx
> +          {error?.message.includes('404')
Hey Pushpa, could you add the requested change above to include the comment? I think you should just be able to click "Commit suggestion" here. Thanks!

2023-11-07 16:32 UTC, alexcreasy approved these changes

2023-11-07 16:33 UTC, alexcreasy commented
/approve

2023-11-07 16:35 UTC, merged

2023-12-06 12:29 UTC, sthundat commented
@andrewballantyne This feature  is not  available in 2.5.We have Components and Permissions tab on data science project page,No Settings tab.

2023-12-07 14:38 UTC, andrewballantyne commented
@sthundat This is not in 2.5, you won't see it there.