Provide a better experience when on the project settings tab when Bia…
opendatahub-io/odh-dashboard pull request #2042
Opened 2023-11-01 08:33 UTC by pnaik1

Closes: #2024 

## Description
Hide the settings tab on the project details page when bias metrics are disabled by feature flag

## How Has This Been Tested?
diable the BiasMetrics feature flag and check whether the the setting tab is hidden

![Screenshot from 2023-11-01 13-59-24](https://github.com/opendatahub-io/odh-dashboard/assets/99238909/6ae75afc-c48b-42e8-8855-3421302ed164)

## Test Impact
No test here are no tests as yet for this feature.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [X] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2023-11-01 14:01 UTC, ppadti commented
working fine.
/lgtm

![Screenshot from 2023-11-01 19-00-02](https://github.com/opendatahub-io/odh-dashboard/assets/99261071/55ed1e3f-89c5-45c2-8c4e-2f9898c7527f)

2023-11-02 17:49 UTC, DaoDaoNoCode commented
Might be related to #2032, not sure which one will be merged first, but the other one will need to use its work.

2023-11-06 11:33 UTC, alexcreasy requested changes
Looks good, one change requested though.

2023-11-06 11:33 UTC, alexcreasy commented on frontend/src/pages/projects/projectSharing/utils.ts
> +export const isBiasMetricsEnabled = (dashboardConfig: DashboardConfig) =>
This function isn't necessary, we already have the `useBiasMetricsEnabled` hook[1] please could you update the PR to use this?

[1] https://github.com/alexcreasy/odh-dashboard/blob/e2f799d38ee6b18c2d224722a6a6fd875a1dd6ca/frontend/src/concepts/explainability/useBiasMetricsEnabled.ts

2023-11-06 11:40 UTC, alexcreasy commented on frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
> +  const biasMetricsEnabled = isBiasMetricsEnabled(dashboardConfig);
@christianvogt Thank for raising this. We're looking to merge `f/mserving-metrics` into incubation tomorrow (7th November), so as this is against that branch, I'd propose we merge this as is (after Purva makes the requested updates to use the existing hook you mentioned).

As #2032 target's main, they won't immediately conflict, I propose I create an issue to update the `f/mserving-metrics` features once #2032 is merged? 

Any objections?

2023-11-06 16:20 UTC, christianvogt commented on frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
> +  const biasMetricsEnabled = isBiasMetricsEnabled(dashboardConfig);
No issues with your work going first. I assumed the #2032 might get in first.

2023-11-07 15:48 UTC, alexcreasy approved these changes

2023-11-07 15:49 UTC, alexcreasy commented
/approve

2023-11-07 15:51 UTC, merged