Edge Model Registry - Sidebar and EmptyState
opendatahub-io/odh-dashboard pull request #2131
Opened 2023-11-13 18:08 UTC by Sara4994

Github issue: https://github.com/opendatahub-io/odh-dashboard/issues/2061

## Description

## How Has This Been Tested?

## Test Impact

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2023-11-13 18:11 UTC, Gkrumbach07 commented
@Sara4994 Make sure you fill out all the template information, including the checkboxes

2023-11-14 16:09 UTC, Gkrumbach07 requested changes

2023-11-14 16:09 UTC, Gkrumbach07 commented on frontend/src/app/AppRoutes.tsx
> +        <Route path="/modelRegistry" element={<EdgeModelRegistry />} />
these should all go under a route for `/edge/*`

2023-11-14 16:09 UTC, Gkrumbach07 commented on frontend/src/utilities/NavData.tsx
> +const useEdgeMVPNav = (): NavDataItem[] => [
this needs to use feature flags

2023-11-14 16:09 UTC, Gkrumbach07 commented on frontend/src/pages/edgeMVP/EdgeModelRegistry.tsx
> +  const { loaded } = useWatchComponents(true);
why are you using useWatchComponents here?

This should be fetching the created models

2023-11-16 01:11 UTC, Gkrumbach07 commented
waiting on tests

2023-11-16 19:02 UTC, Gkrumbach07 approved these changes
/lgtm

@christianvogt can you give the final look at this to merge

for context this is just the feature flag and the first empty state for the edge feature

2023-11-16 19:05 UTC, Gkrumbach07 commented
waiting on UX as well.

@vconzola This is just for the navbar on the side and one empty state. The wording can change in future PRs if you dont have one now. This is just so we can start putting in a foundation for the architecture of the feature

2023-11-21 07:03 UTC, dpanshug requested changes

2023-11-21 07:03 UTC, dpanshug commented on frontend/src/pages/edge/EmptyModelRegistry.tsx
> +      <Title headingLevel="h2" size="lg" style={{ marginBottom: '10px' }}>
```suggestion
      <Title headingLevel="h1" size="lg" style={{ marginBottom: '10px' }}>
```

2023-11-21 12:51 UTC, dpanshug approved these changes
/lgtm

2023-11-21 13:04 UTC, dpanshug approved these changes
/lgtm

2023-11-21 22:10 UTC, vconzola commented
@Sara4994 After discussions with Gage and the RHOAI dashboard team I've updated the mockups, including the navigation and the empty state.

1. Edge will appear in the navigation above Settings and Resources
2. We'll only have two subheadings under Edge - Models and ML Ops Pipelines (this second one might change)
3. Text on the empty state has been updated. (Still not final, but close enough for now.)

Mockups here: https://docs.google.com/presentation/d/1W9wHeASZsxz4W1UzyN-HfQCqeMhI0dm4IpyxnPBALLo/edit?usp=sharing   Only the mockups with the red dots will be included for December.

cc: @Gkrumbach07

2023-11-22 11:13 UTC, Sara4994 commented
Thanks @vconzola for providing updated mockups. I have updated the UI as per the suggestions. please have a look if that looks good.

2023-11-22 11:35 UTC, dpanshug commented
@Sara4994 Can you update the screenshot in description, easy to review by UX. Also the linting test is failing.

2023-11-22 11:50 UTC, dpanshug commented on frontend/src/utilities/NavData.tsx
> +        { id: 'edge-model-registry', label: 'Model registry', href: '/edge/modelRegistry' },
```suggestion
        { id: 'edge-model-registry', label: 'Models', href: '/edge/modelRegistry' },
```

2023-11-22 12:01 UTC, dpanshug commented
/lgtm

2023-11-22 12:58 UTC, vconzola commented
LGTM.

2023-11-23 19:17 UTC, christianvogt requested changes

2023-11-23 19:17 UTC, christianvogt commented on frontend/src/pages/edge/EmptyEdgeModels.tsx
> +      <EmptyStateBody style={{ margin: 'auto', width: '50%' }}>
Avoid all custom styles. We must adhere to what PF provides or updates to PF will create inconsistencies in our application.

```suggestion
    <EmptyState variant={EmptyStateVariant.large}>
      <EmptyStateIcon icon={PlusCircleIcon} />
      <Title headingLevel="h1" size="lg">
        No models added
      </Title>
      <EmptyStateBody>
```

2023-11-24 14:30 UTC, christianvogt commented
/lgtm
/approve

2023-11-24 18:20 UTC, christianvogt approved these changes

2023-11-24 18:20 UTC, merged