Accelerator profile table filter
opendatahub-io/odh-dashboard pull request #2155
Opened 2023-11-15 20:36 UTC by dpanshug

Closes: #1374

## Description
Added filter to accelerator profile table.

<img src="https://github.com/opendatahub-io/odh-dashboard/assets/97534722/ed888a42-c5a5-47b8-82ce-f82c4358284e" width="500px" />

![Screenshot from 2023-11-16 02-02-18](https://github.com/opendatahub-io/odh-dashboard/assets/97534722/56a352b0-f76f-4b28-9dfb-f383c25aa099)

![Screenshot from 2023-11-16 02-01-55](https://github.com/opendatahub-io/odh-dashboard/assets/97534722/f9d4b002-d069-4415-86ac-361158f7ebd7)

## How Has This Been Tested?
1. Add accelerator profile CR.
2. Settings < accelerator profiles
3. On accelerator profile table page, try filter some accelerators.

## Test Impact
Added some integration test within List accelerator profile tests.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

@yannnz

2023-11-15 20:44 UTC, dpanshug commented
Upon assigning Gage as the reviewer, other review requests are removed automatically.

2023-11-15 23:16 UTC, Gkrumbach07 approved these changes
/lgtm

Tested and works

2023-11-15 23:17 UTC, Gkrumbach07 commented
@yannnz pending a quick review from you on the UX

2023-11-16 09:59 UTC, manaswinidas requested changes

2023-11-16 09:59 UTC, manaswinidas commented on frontend/src/pages/acceleratorProfiles/screens/list/AcceleratorProfilesTable.tsx
> +      emptyTableView={<DashboardEmptyTableView onClearFilters={resetFilters} />}
Can you inline this? Just like what you've done for `onSearchTypeChange` and `onSearchValueChange`.

2023-11-16 11:59 UTC, manaswinidas reviewed
/lgtm

2023-11-16 15:14 UTC, yannnz commented
> @yannnz pending a quick review from you on the UX

Looks good. Thanks. @dpanshug @Gkrumbach07

2023-11-16 15:40 UTC, merged