Create pipeline and pipeline version selector and change pipeline run creation page
opendatahub-io/odh-dashboard pull request #2267
Opened 2023-12-04 22:18 UTC by DaoDaoNoCode

JIRA:
[RHOAIENG-266](https://issues.redhat.com/browse/RHOAIENG-266)
[RHOAIENG-268](https://issues.redhat.com/browse/RHOAIENG-268)

## Description

This PR creates a selector for both pipeline and pipeline versions that could be used in many places. Here in this PR, we add this selector to the pipeline runs creation form.

When no pipeline is selected, the version selector is disabled

<img width="1726" alt="Screenshot 2023-12-04 at 4 59 23 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/5b3fd5bb-7108-4ab7-a6cd-e62cb89eef1e">

Now you could select the pipeline, if the number is less than 10, we will not show the `View more` button

<img width="1726" alt="Screenshot 2023-12-04 at 5 00 18 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/fa3ca1f1-6877-4c01-9975-a88d4ac5e3e2">

After the pipeline is selected, the default version will be automatically selected

<img width="1726" alt="Screenshot 2023-12-04 at 5 01 27 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/eee7eba5-4896-4370-ab7c-7da61826399f">

If the number is more than 10, it will show the badge of the visible options and the total size

<img width="1726" alt="Screenshot 2023-12-04 at 5 01 46 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/f06f85ac-6ce4-4a63-bc6a-fb9328b63ae5">

Clicking on it will load more options

<img width="1726" alt="Screenshot 2023-12-04 at 5 03 17 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/429dc1c9-8834-4131-a49b-6cabccdd837d">

If the name is truncated, the tooltip will show up. If the version has a description, another tooltip will show on the side

<img width="1726" alt="Screenshot 2023-12-04 at 5 04 08 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/164eee4c-8526-4618-87f4-ce394b015caf">

The `Updated` column is sortable, the sort is based on *ALL* options, but not only the visible options

<img width="1726" alt="Screenshot 2023-12-04 at 5 05 02 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/ae4f7788-20da-44db-baa7-25f162e45b41">

The search input could be used to filter the pipelines or pipeline versions

<img width="1726" alt="Screenshot 2023-12-04 at 5 06 56 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/ab054a1c-961c-495d-9e5b-26d920abb2e2">

<img width="1726" alt="Screenshot 2023-12-04 at 5 07 06 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/0bc948b2-9ca6-473f-90c0-da9d697a36a6">

## How Has This Been Tested?

1. Upload several versions to one pipeline (better to be more than 10 to test the `View more` function). If you don't know how to upload, you could enable the kubeflow pipeline UI following the instructions here https://github.com/opendatahub-io/data-science-pipelines-operator#ml-pipelines-ui. Then you could upload a version to a specific pipeline. A version is the same YAML file as the pipeline you uploaded before.
2. Go to the create run page, and test the dropdowns for both pipeline and pipeline version

## Test Impact

Created a unit test to test the selector to see whether it could show the correct number and badge and search.

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2023-12-04 22:18 UTC, DaoDaoNoCode commented
cc @yannnz Could you please check the UI?

2023-12-05 12:49 UTC, manaswinidas requested changes

2023-12-05 12:49 UTC, manaswinidas commented on frontend/src/concepts/pipelines/content/createRun/RunForm.tsx
> +    <PipelineVersionSection
@yannnz Do we still have the Pipeline version dropdown enabled when we only have 1 version(i.e., the Default one) and that is selected by default? Here's an example. 
<img width="665" alt="Screenshot 2023-12-05 at 6 17 53 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/22885912/01a2ccf6-987b-4414-a465-38d64256df6a">

2023-12-05 13:04 UTC, manaswinidas requested changes

2023-12-05 13:43 UTC, DaoDaoNoCode commented on frontend/src/concepts/pipelines/content/createRun/contentSections/PipelineSection.tsx
> +        searchHelperText="Type a name to search your # pipelines."
Ah, nice catch!! I was also wondering what this means here, now I know :)

2023-12-05 14:48 UTC, DaoDaoNoCode commented
Pipeline with no version:

<img width="1726" alt="Screenshot 2023-12-05 at 9 46 51 AM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/e24fe12f-fdcf-4110-bb7c-f3fd5589208e">

Updated search helper text:

<img width="1726" alt="Screenshot 2023-12-05 at 9 47 32 AM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/5a2c1a90-47e3-45d4-b169-f6af10980d54">

@manaswinidas Could you check again?

2023-12-05 16:17 UTC, manaswinidas approved these changes
/lgtm

Tested. Works fine.

2023-12-05 16:26 UTC, merged