Unable to duplicate a serving runtime
opendatahub-io/odh-dashboard pull request #2339
Opened 2024-01-16 10:16 UTC by dpanshug

Closes: [RHOAIENG-552](https://issues.redhat.com/browse/RHOAIENG-552)

## Description
Changed the label for Duplicating serving runtime

![image](https://github.com/opendatahub-io/odh-dashboard/assets/97534722/27fbad32-40ee-4439-a5bb-23f7e9a3068f)

## How Has This Been Tested?
1. Create an OOTB serving runtime
2. Try duplicating it

## Test Impact
Added integration test to check page headings for Add, Duplicate and Edit.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

@vconzola

2024-01-16 10:44 UTC, lucferbux requested changes
Changes look great, we need testing coverage and we should tag @vconzola to review the changes.

2024-01-16 10:44 UTC, lucferbux commented on frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAddTemplate.tsx
> +                {existingTemplate ? 'Update' : state ? 'Duplicate' : 'Add'}
I think @vconzola commented to change "Add" to create.

2024-01-16 10:45 UTC, lucferbux commented
This is not only a label change, que should add coverage to tests that adding a new SR will display "Add" and if we try to duplicate it will get "Duplicate..."

2024-01-16 14:35 UTC, vconzola commented
The page title change looks OK, but you should also change the description text below the title. The text should say, "Add a new, editable runtime by duplicating and existing runtime."

2024-01-17 10:04 UTC, dpanshug commented
@lucferbux, Cypess test added and also refactored the test file according to [cypress test structure](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Test-Structure)

2024-01-17 17:12 UTC, lucferbux approved these changes
/lgtm

Great job here!

2024-01-17 17:24 UTC, merged