Inconsistent Model Path
opendatahub-io/odh-dashboard pull request #2369
Opened 2024-01-22 10:57 UTC by dpanshug

[RHOAIENG-542](https://issues.redhat.com/browse/RHOAIENG-542)

## Description
Shows error when path name starts with '/'

![Screenshot from 2024-01-22 15-46-09](https://github.com/opendatahub-io/odh-dashboard/assets/97534722/fd791c3c-ff43-4f11-85e2-576b30d21740)

## How Has This Been Tested?
1. Deploy new model KServe or Multi model
2. Enter path name starting with '/' and you can see the error.

## Test Impact
Added case in cypress to check path name starting with '/'

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

@vconzola

2024-01-22 10:58 UTC, dpanshug commented
@vconzola @kaedward pls check the error msg.

2024-01-22 19:28 UTC, vconzola commented
@andrewballantyne @lucferbux @DaoDaoNoCode i thought we addressed this a looong time ago by just ignoring any leading "/" or "/////" that a user typed in the path field?

2024-01-23 06:21 UTC, manaswinidas commented
@vconzola Is this what you are talking about https://github.com/opendatahub-io/odh-dashboard/pull/1512

2024-01-23 06:31 UTC, manaswinidas reviewed
I think this issue is more about whether the backend needs us to prefix or not. And whether the prefix is coming from the backend or from us? please correct me if I'm missing something here. I remember this being discussed in one of the Triage calls.

2024-01-23 06:42 UTC, dpanshug commented
@vconzola This one is different because it introduces additional functionality to raise an error when characters appear after '/'. In the previous version, errors were only triggered for the '/' character itself. Now, errors will also be raised for paths like '/something'."

So for path 
1. '/' error is "The path must not point to a root folder."
2. '/something' error is "The path must not start with /"

2024-01-23 12:05 UTC, lucferbux commented
> > @vconzola @kaedward pls check the error msg.
> 
> How about "Must start with a letter or number"? Can paths start with numbers or other characters, or only letters?

That's a great question, and something that we are not checking cc @Jooho @Xaenalt can you guys help us out here to validate that too?

2024-01-23 12:06 UTC, lucferbux commented
> @andrewballantyne @lucferbux @DaoDaoNoCode i thought we addressed this a looong time ago by just ignoring any leading "/" or "/////" that a user typed in the path field?

It seems that the logic behind it wasn't working well and there was an issue, that's why we had [RHOAIENG-542](https://issues.redhat.com/browse/RHOAIENG-542) in place. But checking a solution for it we realized that we shouldn't allow a leading "/" in any case, so the proposed solution would be error out that rather than silently remove it, what do you think?

2024-01-23 16:12 UTC, vconzola commented
I'm still not sure I understand the issue completely, but in general the more "fault tolerant" we can be for users, the better. So I'm not sure why just ignoring any leading "/" won't work? Regarding [RHOAIENG-542](https://issues.redhat.com/browse/RHOAIENG-542) (if I understand that issue correctly), we should not store any leading "/" so when the path is rendered for editing there will be no leading "/".

2024-01-24 06:38 UTC, dpanshug commented
> So I'm not sure why just ignoring any leading "/" won't work? 

This PR introduces a condition specifically targeting chars following a "/" in a path. Because, previously the error would only be triggered if the path was exactly equal to "/".

> We would still throw an error ("The path must not point to a root folder.") if the user leaves the field blank or inputs only one or more "/" to address the root folder issue.

Yes I also think we should keep the error msg same.

2024-01-24 15:15 UTC, vconzola commented
> For example, what I'm understanding is the following:
> 
> / -> Will fail ❌
> path/model -> Will work and it's correct ✅
> /path/model -> Will work, but we should filter the leading slash and convert it to path/model ⚠️
> 
> Is that right?

@lucferbux Yes, that's what I suggest (assuming it's technically correct).

2024-01-29 09:28 UTC, dpanshug commented
@lucferbux @vconzola made necessary changes :heavy_check_mark:

2024-01-29 11:45 UTC, lucferbux commented
Ok, lat nit, and I think it should be addressed here:

<img width="841" alt="Screenshot 2024-01-29 at 12 41 51" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/72433607-5869-4114-b2a1-a5a8e5c9ecde">

Trying this won't let you input the model, but the message is wrong, since it's not pointing at the root folder, this happens cause we have this in the validation:

`if (folderPath === '/' || folderPath.includes('//'))`

We should do two small changes:

1. Change the validation to test wether it includes ONLY one or several slashes (/ or //// or //)
2. Change your filter method to filter ALL the leading slashes

2024-01-30 11:13 UTC, manaswinidas requested changes

2024-01-30 11:13 UTC, manaswinidas commented on frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
> +    return this.find().findByLabelText('folder-path-error');
I think this should use `test-id`.

2024-01-30 13:46 UTC, manaswinidas approved these changes
/lgtm

2024-02-02 00:24 UTC, lucferbux approved these changes
/lgtm

Great job!!

2024-02-02 00:36 UTC, merged