update cypress and unit test documentation
opendatahub-io/odh-dashboard pull request #2460
Opened 2024-02-05 22:48 UTC by christianvogt

Closes:
https://issues.redhat.com/browse/RHOAIENG-841 
https://issues.redhat.com/browse/RHOAIENG-840

## Description

Added new `testing.md` markdown for all testing related documentation.
Updated various files that contained references to testing.

## How Has This Been Tested?

## Test Impact

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-02-06 05:53 UTC, manaswinidas requested changes

2024-02-06 05:53 UTC, manaswinidas commented on docs/testing.md
> +  - Without prefix (`find()`): Eestablish a scope for command chaining.
Typo: Eestablish -> Establish

2024-02-06 13:28 UTC, christianvogt commented on docs/testing.md
> +Test files must be consistently named based on the name of the source code file being tested. Test files must use the `.spec.ts` file extension and be located in the `__test__` directory adjacent the
Oh that's a bad typo lol

2024-02-06 18:49 UTC, christianvogt commented
Addressed comments. Ready for review again.

2024-02-07 07:29 UTC, manaswinidas approved these changes
/lgtm

2024-02-07 07:43 UTC, pnaik1 requested changes

2024-02-07 09:00 UTC, ppadti commented on docs/testing.md
> +- `cy.findByTestId('<test-id')`
Nit:
```suggestion
- `cy.findByTestId('<test-id>')`
```

2024-02-07 14:10 UTC, christianvogt commented on docs/testing.md
> +Jest is used as the unit test runner. Unit tests should be written for all utility and hook functions; React Components do not require unit tests.
I think the semi colon is appropriate here because the two clauses, while independent, are part of the same idea.

2024-02-07 14:25 UTC, pnaik1 commented
/lgtm

2024-02-07 14:26 UTC, ppadti commented
/lgtm

2024-02-07 19:00 UTC, christianvogt commented
/retest

2024-02-07 19:42 UTC, merged