Add unit test case for pipelines/k8s file
opendatahub-io/odh-dashboard pull request #2463
Opened 2024-02-06 07:39 UTC by ppadti

Closes: [RHOAIENG-2177](https://issues.redhat.com/browse/RHOAIENG-2177)

## Description
Unit test case for: frontend/src/api/pipelines/k8s.ts

## How Has This Been Tested?
`npm run test`

## Test Impact
Coverage:
![Screenshot from 2024-02-06 01-13-58](https://github.com/opendatahub-io/odh-dashboard/assets/99261071/728ad1eb-1e58-4f1e-ae34-0eb6b5cb601f)

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-02-06 14:05 UTC, pnaik1 requested changes

2024-02-07 09:13 UTC, ppadti commented on frontend/src/api/pipelines/__tests__/k8s.spec.ts
> +  const DSPipelinemock: DSPipelineKind = {
yes. In `createPipelinesCR` it is removing some properties from the data that we pass. I don't want to modify the `mockDataSciencePipelineApplicationK8sResource ` while asseting for this test case. So I created one.

2024-02-07 14:33 UTC, christianvogt commented on frontend/src/api/pipelines/__tests__/k8s.spec.ts
> +  const DSPipelinemock: DSPipelineKind = {
I'm confused. It looks to be exactly the same except for the status. Can you not reuse the existing mock util but delete the status. If it's not about the status, can you elaborate on the need for this mock and not the existing one.

2024-02-07 15:19 UTC, ppadti commented on frontend/src/api/pipelines/__tests__/k8s.spec.ts
> +  const DSPipelinemock: DSPipelineKind = {
yes, reason to create a new is for status. I thought of not deleting the status from the mock, so created new one. If you want me to reuse that, I will update this test case.

2024-02-07 15:46 UTC, christianvogt commented on frontend/src/api/pipelines/__tests__/k8s.spec.ts
> +  const DSPipelinemock: DSPipelineKind = {
We have an issue to improve how our mock functions are done: https://issues.redhat.com/browse/RHOAIENG-2412
This is one of those cases where we want to use the mock but configure it to omit the status.

2024-02-08 08:25 UTC, ppadti commented on frontend/src/api/pipelines/__tests__/k8s.spec.ts
> +  const DSPipelinemock: DSPipelineKind = {
Updated the test. Ready for review again.

2024-02-09 16:36 UTC, christianvogt commented
/lgtm
/approve

2024-02-09 16:53 UTC, merged