Unit Test for k8s/Users
opendatahub-io/odh-dashboard pull request #2480
Opened 2024-02-07 20:04 UTC by ashley-o0o

Closes: [RHOAIENG-2175](https://issues.redhat.com/browse/RHOAIENG-2175)

## Description
Unit test case for: frontend/src/api/k8s/users.ts

## How Has This Been Tested?
'npm run test'

## Test Impact
Coverage:
<img width="734" alt="Screenshot 2024-02-07 at 2 57 01 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/123661468/412bedc4-511f-4700-99b1-8b6080492001">

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-02-08 05:23 UTC, pnaik1 commented
@ashley-o0o  the  test looks good but can you please squash the commits?

2024-02-08 07:10 UTC, uidoyen requested changes

2024-02-08 07:10 UTC, uidoyen commented on frontend/src/api/k8s/__tests__/users.spec.ts
> +      model: { apiGroup: 'user.openshift.io', apiVersion: 'v1', kind: 'User', plural: 'users' },
` model: UserModel` can be used instead.

2024-02-08 16:24 UTC, ppadti commented on frontend/src/api/k8s/__tests__/users.spec.ts
> +describe('listUser', () => {
typo:  `listUser `-> `listUsers`

2024-02-08 16:36 UTC, ppadti commented
/lgtm

2024-02-08 17:22 UTC, uidoyen commented
/lgtm

2024-02-08 17:22 UTC, uidoyen approved these changes

2024-02-09 16:33 UTC, christianvogt commented
/approve

2024-02-09 17:10 UTC, merged