[WIP] Story/rhoaieng 2273 convert api list jobs
opendatahub-io/odh-dashboard pull request #2482
Opened 2024-02-07 22:48 UTC by Gkrumbach07

closes: https://issues.redhat.com/browse/RHOAIENG-2273

## Description

- migrates api to render pipeline run jobs table and delete modal

## How Has This Been Tested?

- tests pass
- create scheduled runs via the KF UI.
- test single delete
- test multi delete
- test that versions show up in row
- test enable/disable

## Test Impact

TBD need to right

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-02-07 22:48 UTC, Gkrumbach07 commented
WIP to write more tests via the description of the issue

2024-02-08 23:24 UTC, Gkrumbach07 commented
Added tests

2024-02-09 15:10 UTC, andrewballantyne requested changes
Might need to get rid of the Experiment filter too

![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/7ca24927-55a9-4e57-9dcc-17d43634e35e)

2024-02-09 15:22 UTC, andrewballantyne requested changes
![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/a1f830db-863a-444d-a6df-493fd84cd274)
`"/apis/v2beta1/experiments/cc0d3cff-b612-4550-b393-a8e74dba5745"`

These are all requests for experiment -- the same experiment. Is there something up here that we need to look into? Seems like a bad fetch logic to do so many concurrent requests.

2024-02-09 16:15 UTC, andrewballantyne commented
[We'll address the experiment fetching](https://github.com/opendatahub-io/odh-dashboard/pull/2482#pullrequestreview-1872640606) in another PR -- it is added network noise because of KFPv2 API needing to fetch Experiments. We had this problem with Jobs, we can address it the same way.

2024-02-09 16:17 UTC, andrewballantyne approved these changes

2024-02-09 16:17 UTC, andrewballantyne commented on frontend/src/concepts/pipelines/context/usePipelineNamespaceCR.ts
> +          if (e.statusObject?.code === 404) {
Thanks for cleaning this up in this PR 👍

2024-02-09 16:31 UTC, merged