added eslint rules for allSettledPromises
opendatahub-io/odh-dashboard pull request #2515
Opened 2024-02-16 05:27 UTC by pnaik1

Closes: https://issues.redhat.com/browse/RHOAIENG-1295

## Description
added eslint to restrict using Promise.allSetttled

## How Has This Been Tested?
npm run test

## Test Impact

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-02-16 14:52 UTC, manaswinidas requested changes

2024-02-16 14:52 UTC, manaswinidas commented on frontend/src/utilities/allSettledPromises.ts
> +  // eslint-disable-next-line no-restricted-properties
Any specific reasons why some were disabled and some were replaced?

2024-02-16 15:12 UTC, christianvogt commented on frontend/src/concepts/pipelines/content/DeletePipelineRunsModal.tsx
> +          // eslint-disable-next-line no-restricted-properties
Please add a comment when disabling any rule. In this particular case it was discussed that Andrew would prefer a refactor for the use case to not depend on the index in the delete modal.

2024-02-16 15:12 UTC, christianvogt commented on frontend/.eslintrc
> +        "message": "Avoid using Promise.allSettled use allSettledPromises utility function instead"
```suggestion
        "message": "Avoid using Promise.allSettled, use allSettledPromises utility function instead."
```

2024-02-16 15:12 UTC, christianvogt commented on frontend/src/utilities/allSettledPromises.ts
> +  // eslint-disable-next-line no-restricted-properties
```suggestion
  // Use of `Promise.allSettled` is justified as this utility is a wrapper with type improvements.
  // eslint-disable-next-line no-restricted-properties
```

2024-02-21 18:40 UTC, christianvogt commented
/approve

2024-02-21 19:12 UTC, merged