(Backend) Combine BYON image logic and normal imagestream logic
opendatahub-io/odh-dashboard pull request #254
Opened 2022-06-22 10:51 UTC by maroroman

This PR attempts to combine both BYON images backend and the backend that was used in the old spawner UI.

Main changes: 
The endpoint for both BYON and Imagestreams is now /api/images/:type, for now for BYON the type value should be "byon" for notebook-image labeled imagestreams any type string will do, including empty strings (I think more options can be added later like "other" type which could list all imagestreams and not only labeled ones.
All references to notebooks and notebook iamges have been changed to images and BYON images for clarity. This has been done in frontend as well.
The POST, PUT and DELETE calls work only for BYON images currently, we could add a labels section in the request body to set up what gets created.

All other stuff is mostly the same as PR #197

2022-06-22 18:17 UTC, DaoDaoNoCode requested changes
Overall lgtm! Left some comments to address, and could you also remove the comments in the code?

2022-06-22 18:17 UTC, DaoDaoNoCode commented on frontend/src/pages/notebookImages/NotebookImages.tsx
>  const NotebookImages: React.FC = () => {
Can you also rename the component, file name, and repo name to BYONImages? Also, could you update the other files in this repo?

2022-06-23 06:14 UTC, maroroman commented on backend/src/types.ts
> +};
adding `export type ImageType = "byon" | "jupyter" | "other";`

2022-06-24 23:02 UTC, DaoDaoNoCode approved these changes
Tested, works well, lgtm! Could you squash the commits?

2022-06-27 06:40 UTC, maroroman commented
> Tested, works well, lgtm! Could you squash the commits?

We can do squash on merge, I think it is easier

2022-06-27 08:35 UTC, lucferbux approved these changes
/lgtm

2022-06-27 08:35 UTC, lucferbux commented
Tested and works great!

2022-06-27 08:37 UTC, lucferbux commented
> > Tested, works well, lgtm! Could you squash the commits?
> 
> We can do squash on merge, I think it is easier

Yeah, we can totally do that, although it would be super nice if we can make it into one squashed commit signed off with your gpg key, just to get the git History ordered.

2022-06-27 09:14 UTC, maroroman commented on backend/src/routes/api/images/imageUtils.ts
> +  ImageStreamList,
Resolved all related to Images, but will resolve ones related to notebooks in a refactoring PR later so its in the correct PR.

2022-06-30 10:55 UTC, maroroman commented
Rebased and squashed @lucferbux  @DaoDaoNoCode  @dlabaj  What should be done about the uncooperative tests?

2022-06-30 12:50 UTC, maroroman commented on package.json
> +    "format": "prettier --write \"backend/**/*.ts\" \"frontend/**/*.ts\" \"frontend/**/*.tsx\"",
It seems that didn't help sadly

2022-07-01 07:13 UTC, merged