Fix indentation for labels in serving manifests
opendatahub-io/odh-dashboard pull request #2617
Opened 2024-03-20 17:24 UTC by Xaenalt

Small nit noticed in https://issues.redhat.com/browse/RHOAIENG-4547

2024-03-20 18:00 UTC, jiridanek commented
> Small nit noticed in https://issues.redhat.com/browse/RHOAIENG-4547

If forces me to do

```java
            // WORKAROUND(RHOAIENG-4547) ServingRuntime should not have top level `labels` key
            genericKubernetesResource.getAdditionalProperties().remove("labels");
            return castResource(it, ServingRuntime.class);
```

https://github.com/skodjob/odh-e2e/blob/46c2482fc88daf5ad1d72e5956cbf7b34f5415df/src/test/java/io/odh/test/e2e/standard/ModelServingST.java#L237-L239

and I guess it either means the label is missing where it should be after the template is instantiated, or how do you call it, or that something has to be adding that label. In case of which maybe the label does not have to be specified in the template in the first place.

2024-03-20 18:02 UTC, jiridanek requested changes

2024-03-20 18:02 UTC, jiridanek commented on manifests/modelserving/ovms-kserve-ootd.yaml
> +        opendatahub.io/dashboard: 'true'
please remove the `labels:` on lines 16,17

2024-03-26 19:17 UTC, andrewballantyne approved these changes
Looks good, didn't test this on a cluster but looks good on paper.

2024-03-26 19:22 UTC, merged