added cluster storage cypress test
opendatahub-io/odh-dashboard pull request #2652
Opened 2024-04-01 09:47 UTC by pnaik1

Closes: https://issues.redhat.com/browse/RHOAIENG-3809

## Description
added cypress test for cluster storage page

## How Has This Been Tested?
npm run test

## Test Impact

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-04-01 10:24 UTC, ppadti requested changes

2024-04-01 10:24 UTC, ppadti commented on frontend/src/__tests__/cypress/cypress/e2e/projects/clusterStorage.cy.ts
> +    initInterceptors({});
Could you please add sorting based on Name here

2024-04-01 10:24 UTC, ppadti commented on frontend/src/__tests__/cypress/cypress/e2e/projects/clusterStorage.cy.ts
> +        metadata: {
May be we could use `chai-subset` here after this [PR](https://github.com/opendatahub-io/odh-dashboard/pull/2643) gets merged.

2024-04-01 13:38 UTC, pnaik1 commented
Updated the PR

2024-04-02 11:34 UTC, ppadti commented
/lgtm

2024-04-02 15:37 UTC, christianvogt commented on frontend/src/__tests__/cypress/cypress/pages/clusterStorage.ts
> +    this.find().find('button').should('have.attr', 'aria-label', 'Details').eq(index).click();
I believe you can use `findByRole` and `name` for this selector. Also, why do you need to check the `index` ? Shouldn't there only be one per row?
Ideally we use test
```suggestion
    this.find().findByRole('button', { name: 'Details' }).click();
```

2024-04-02 15:37 UTC, christianvogt commented on frontend/src/__tests__/cypress/cypress/e2e/projects/ClusterStorage.cy.ts
> +  );
Why is this needed?

2024-04-02 19:34 UTC, christianvogt commented
/lgtm
/approve

2024-04-02 19:56 UTC, merged