[RHOAIENG-4852] update to colorful illustrations in project pages
opendatahub-io/odh-dashboard pull request #2656
Opened 2024-04-01 19:38 UTC by nicolethoen

Closes https://issues.redhat.com/browse/RHOAIENG-4852

## Description
Updates to the illustrations on the project UI screens as outlined by [RHOAI UX refresh for Summit 2024 doc](https://docs.google.com/document/d/1UwclZPg3jG891zqrv_Jkwo3IUzprIE0SYYlIJUAHR1M/edit) using the images in this [google drive folder](https://drive.google.com/drive/folders/10tW9AstzobKSs25D-QfCVnQew9l7yGZH).

## How Has This Been Tested?
Ran unit and cypress tests locally, also visually when running the dashboard locally

## Test Impact
N/A

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-04-03 15:07 UTC, jeff-phillips-18 commented
/ok-to-test

2024-04-03 15:24 UTC, jeff-phillips-18 commented
/lgtm

2024-04-03 17:25 UTC, andrewballantyne requested changes
There seems to be a lot of whitespace at play here... is this what we want?

2024-04-03 17:25 UTC, andrewballantyne commented on frontend/src/images/empty-state-cluster-storage.svg
![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/1310dd52-899d-4d7b-975f-95bae2c7541a)

2024-04-03 17:25 UTC, andrewballantyne commented on frontend/src/images/empty-state-data-connections.svg
![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/d6167125-bb8a-4c38-9a05-fccc2b3d3f84)

2024-04-03 17:25 UTC, andrewballantyne commented on frontend/src/images/empty-state-model-serving.svg
Might be for another PR -- but our Single & Multi Model Server doesn't have an infographic?
![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/d569e2dd-507a-4b3d-a1dd-015d0ac74d94)
![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/aa3e7472-c385-4bbe-a99d-2bc63e3c077c)

2024-04-03 17:25 UTC, andrewballantyne commented on frontend/src/images/empty-state-pipelines.svg
![image](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/35f1d25c-6307-4085-b2e0-c641b96eac85)

2024-04-03 17:25 UTC, andrewballantyne commented on frontend/src/images/empty-state-projects-overview.svg
This one is interesting on space... based on how much space you take up -- it either looks weird or not.

Maybe this is another one that has too much white space?

![Screenshot 2024-04-03 at 1 13 07 PM](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/b6886b82-d954-4445-a250-37f30c91b938)
![Screenshot 2024-04-03 at 1 13 17 PM](https://github.com/opendatahub-io/odh-dashboard/assets/8126518/642ace1d-bc2e-46a5-b1ef-3ec262550f2c)

2024-04-03 17:57 UTC, nicolethoen commented
@andrewballantyne I'll take the feedback back to the designer - maybe they can make larger images? Or at least speak to the white space.

2024-04-03 20:17 UTC, jgiardino commented
@andrewballantyne regarding this comment:
> Might be for another PR -- but our Single & Multi Model Server doesn't have an infographic?
We currently don't have an image for those empty states. There is a separate jira to address all the variations of empty states for models: https://issues.redhat.com/browse/RHOAIENG-5083
You can see links to the design document in that jira. Any feedback on these designs are welcome in either that jira or figma file. 

Regarding the issue with image dimensions, I've followed up with the original designer to get help with exporting the images with the original dimensions. Thanks for pointing that out!

2024-04-04 21:07 UTC, nicolethoen commented
Here are some screenshots with the updated images.

<img width="1103" alt="Screenshot 2024-04-04 at 5 04 15 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/26305082/22da1503-2505-476d-952f-1779426a0bb5">
<img width="1115" alt="Screenshot 2024-04-04 at 5 04 44 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/26305082/98a014af-7259-4830-9a26-a0d6ef050697">
<img width="1063" alt="Screenshot 2024-04-04 at 5 05 12 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/26305082/ddb6cbd1-c96e-4b87-8d84-b3632c713df0">
<img width="1048" alt="Screenshot 2024-04-04 at 5 05 30 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/26305082/30831b33-534a-4992-8654-42b0d2b8dad5">

2024-04-04 21:49 UTC, jgiardino commented
👍 Thanks for making these updates and including screencaps! I checked the deleted/added comparison under Files changed and the new illustrations look much more similar to the original.

2024-04-05 20:31 UTC, christianvogt commented
/lgtm
/approve

2024-04-05 20:48 UTC, merged