added workbench cypress test
opendatahub-io/odh-dashboard pull request #2675
Opened 2024-04-04 11:43 UTC by pnaik1

Closes: https://issues.redhat.com/browse/RHOAIENG-3808

## Description
added cypress test for workbench Page

## How Has This Been Tested?
npm run test

## Test Impact

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-04-04 13:01 UTC, pnaik1 commented
/retest

2024-04-05 05:23 UTC, pnaik1 commented
/retest

2024-04-05 09:00 UTC, ppadti requested changes

2024-04-05 14:57 UTC, christianvogt commented on frontend/src/pages/projects/screens/spawner/environmentVariables/GenericKeyValuePairField.tsx
> +            <StackItem key={i} data-testid={`key-value-pair ${i}`}>
Unnecessary to add the index to the test ID as you can use cypress to get the nth matching item.
https://docs.cypress.io/api/commands/eq

2024-04-05 14:57 UTC, christianvogt commented on frontend/src/pages/projects/screens/spawner/environmentVariables/GenericKeyValuePairField.tsx
> +                          aria-label={`value ${i}`}
Why the change to `aria-label` ?

2024-04-05 14:57 UTC, christianvogt commented on frontend/src/pages/projects/screens/spawner/environmentVariables/EnvironmentVariables.tsx
> +          testId={`env-variable ${i}`}
Avoid adding index numbers to test IDs.

2024-04-05 14:57 UTC, christianvogt commented on frontend/src/__tests__/cypress/cypress/pages/workbench.ts
> +    cy.visitWithLogin(`/projects/${projectName}?section=workbenches`);
Use `cy.visit` now because of https://github.com/opendatahub-io/odh-dashboard/pull/2682

2024-04-05 17:33 UTC, pnaik1 commented
Updated the changes

2024-04-08 18:36 UTC, christianvogt commented
/approve

2024-04-08 18:51 UTC, merged