[WIP] Registered model table
opendatahub-io/odh-dashboard pull request #2677
Opened 2024-04-04 14:07 UTC by dpanshug

Closes: [RHOAIENG-2231](https://issues.redhat.com/browse/RHOAIENG-2231) [RHOAIENG-2232](https://issues.redhat.com/browse/RHOAIENG-2232)

## Description
Created Registered model table page

    * Table toolbar
    * Search with keywords
    * Model registry selector
    * Table rows with sortable field
    * Labels popover and modal

## How Has This Been Tested?
Open Model registry section from sidebar

## Test Impact

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-04-04 14:09 UTC, dpanshug commented
Currently WIP, need some tests and review

2024-04-05 13:35 UTC, manaswinidas requested changes

2024-04-05 13:35 UTC, manaswinidas commented on frontend/src/pages/modelRegistry/screens/RegisteredModelListView.tsx
> +                        Registered model
As per the mocks, I think this is `Register model`.

2024-04-05 16:46 UTC, dpanshug commented
/retest

2024-04-08 07:34 UTC, yih-wang commented
@dpanshug Thanks for posting the screenshots! Several comments:
#### Registered model page
![image](https://github.com/opendatahub-io/odh-dashboard/assets/23331885/657dd294-d0b8-4b59-b899-e70c53782ace)
- The padding between the name and description looks larger than other tables in the current console (e.g. pipeline table, projects table). Does it follow the standard layout?
- Row 4 (fraud detection model) shows the case that labels exceed the regular two rows. Could we also incorporate the '2 more' label into the label groups? This way, all labels including those displaying 'x more', won't exceed two rows, ensuring consistent row heights throughout the UI.

#### Table searching with keyword
![image](https://github.com/opendatahub-io/odh-dashboard/assets/23331885/a8957ad4-9fee-4064-949e-ad647c6bf8bb)
- Chip row is missing
- I don't know the search logic being applied here (it's probably already implemented as such) so just a reminder that when searching in the model list, we'll also query the version level. In other words, models with versions containing the search keyword in their name, description, or labels will also be included in the search results.

#### Label modal when greater than or equal to 8
![image](https://github.com/opendatahub-io/odh-dashboard/assets/23331885/b2663642-1974-4ee0-80e5-87d005878fea)
- We won't truncate any labels in this modal

2024-04-08 15:42 UTC, dpanshug commented
@yih-wang, added your suggested changes, thanks

> when searching in the model list, we'll also query the version level.

This will be done in future PRs when we add model version table.

2024-04-09 01:31 UTC, yih-wang commented
One more comment: the primary button has a typo. Should be "Register model"

2024-04-11 15:05 UTC, lucferbux approved these changes
/approve

There are a few things that we need to get back really soon but we can continue

2024-04-11 15:07 UTC, lucferbux commented
/override ci/prow/images ci/prow/odh-dashboard-pr-image-mirror

2024-04-11 15:09 UTC, merged