Adding support for s390x and ppc64le for multi-arch image build
opendatahub-io/odh-dashboard pull request #2681
Opened 2024-04-05 06:15 UTC by satyamg1620

## Description
Provided support for s390x and ppc64le to create multi-arch image

## How Has This Been Tested?
For creating multi-arch build image, use command ``` make docker-buildx ```.  This will build multi-arch images and will push into your provided image repository

## Request review criteria:

Self checklist (all need to be checked):
- [X] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-04-05 10:17 UTC, lucferbux requested changes
Hi Satyam,

Thanks for the PR, tested the command and it seems to be working great, we don't want to change the default container builder, we encourage you to parametrize with docker the command if you want to use it, but don't change the default builder engine.

Thanks a lot!

2024-04-05 10:17 UTC, lucferbux commented on Makefile
> +CONTAINER_BUILDER?=docker
We use `podman` as our default container builder due to license limitation of the docker engine nowadays. We would want to keep it that way in our automations, so we encourage overriding with docker in the local environment filest to the people that need it

2024-04-05 10:17 UTC, lucferbux commented on Makefile
> +PLATFORMS ?= linux/s390x,linux/amd64,linux/ppc64le
And so far this works great, tested with an M1 mack and dockerx and it seems to be working just fine

2024-04-05 15:30 UTC, dpanshug requested changes
@satyamg1620 Can you pls squash all the commits

2024-04-05 15:31 UTC, dpanshug commented
/ok-to-test

2024-04-12 05:27 UTC, satyamg1620 commented
@dpanshug, @christianvogt , @lucferbux Can you please review the requested changes?

2024-04-16 04:35 UTC, satyamg1620 commented
@dpanshug , @christianvogt  , @lucferbux  Can you please review the requested changes?

2024-04-16 15:40 UTC, lucferbux approved these changes
/lgtm

Thanks for the contribution, tested on my machine and it seems to work great!

<img width="369" alt="Screenshot 2024-04-16 at 17 40 31" src="https://github.com/opendatahub-io/odh-dashboard/assets/16117276/e1933d2b-a72c-44b3-8ef0-ed61325a3e52">

2024-04-16 16:17 UTC, merged