Add notebook controller culling
opendatahub-io/odh-dashboard pull request #269
Opened 2022-07-07 13:15 UTC by maroroman

This PR implements this PR: https://github.com/opendatahub-io/odh-manifests/pull/581 into the cluster settings interface.

No changes from UI side should be neccessary. The backend does not set the `IDLENESS_CHECK_PERIOD` and ignores pvc_size values if notebook controller is enabled. It also ignores jupyterhub settings (pvc_size, culler_timeout) and does not patch them if notebook controller is enabled in the DashboardConfig CR.

I added an exception for const because eslint was firing errors at my tuple, let me know if I should revert that.

Resolves:https://github.com/opendatahub-io/odh-dashboard/issues/353

2022-07-07 15:00 UTC, samuelvl approved these changes

2022-07-19 13:49 UTC, DaoDaoNoCode approved these changes
lgtm

2022-07-19 14:56 UTC, samuelvl commented
/hold

Do not merge until https://github.com/opendatahub-io/odh-dashboard/pull/298 is merged before

2022-07-20 10:37 UTC, samuelvl requested changes
When I click on "Save changes" nothing happens:

![image](https://user-images.githubusercontent.com/27858594/179962095-569bc07b-480d-4373-86c4-39a83ced02fa.png)

I can see this error in the dashboard logs:

```
{"level":50,"time":1658313323526,"pid":68,"hostname":"odh-dashboard-d5b58f889-l6qnc","reqId":"req-7g","err":{"type":"FastifyError","message":"Promise may not be fulfilled with 'undefined' when statusCode is not 204","stack":"FastifyError: Promise may not be fulfilled with 'undefined' when statusCode is not 204\n    at /opt/app-root/src/backend/node_modules/fastify/lib/wrapThenable.js:30:30\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","name":"FastifyError","code":"FST_ERR_PROMISE_NOT_FULFILLED","statusCode":500},"msg":"Promise may not be fulfilled with 'undefined' when statusCode is not 204"}
```

2022-07-25 15:23 UTC, maroroman commented
Latest changes should address your comment @samuelvl

2022-07-25 19:34 UTC, andrewballantyne commented
What is our ticket backing this @maroroman -- https://github.com/opendatahub-io/odh-manifests/pull/581 is closed.

We need a ticket to track the work for this PR. Either we can reopen 581 or we need to log a new one and update your description.

2022-07-26 07:07 UTC, maroroman commented
> What is our ticket backing this @maroroman -- [opendatahub-io/odh-manifests#581](https://github.com/opendatahub-io/odh-manifests/pull/581) is closed.
> 
> We need a ticket to track the work for this PR. Either we can reopen 581 or we need to log a new one and update your description.

Linked this PR to a new issue https://github.com/opendatahub-io/odh-dashboard/issues/353

2022-07-26 17:03 UTC, samuelvl requested changes
- The `notebook-controller-culler-config` configmap shouldn't be automatically created when I open the `Cluster settings` tab:

![image](https://user-images.githubusercontent.com/27858594/181065644-c6c411eb-42fe-44c4-b596-1892893ca6b4.png)

"Do not stop idle notebooks" should be chosen by default until I select "Stop idle notebooks after".

- When I select a different culling configuration I get the following error:

![image](https://user-images.githubusercontent.com/27858594/181066064-a6e86b81-ee69-4f16-9748-dbf41f8db621.png)

- The `notebook-controller-culler-config` configmap is not deleted when "Do not stop idle notebooks" is selected and I save changes:

![image](https://user-images.githubusercontent.com/27858594/181067612-ada76c83-bfda-454b-ac6a-bcc49b5b2181.png)


``` $ oc get cm notebook-controller-culler-config                  
NAME                                DATA   AGE
notebook-controller-culler-config   3      11m
```

2022-07-26 17:32 UTC, andrewballantyne requested changes

2022-07-26 17:32 UTC, andrewballantyne commented on backend/src/routes/api/cluster-settings/clusterSettingsUtils.ts
> +  );
Recommend you do a `.then` on this and normalize your data away from the kube library's response.

Eg something like:
```
.then((response) => response.body)
```

That way your variable `jupyterhubCfgResponse` can just be a `ConfigMap`.

2022-07-26 17:32 UTC, andrewballantyne commented on backend/src/routes/api/cluster-settings/clusterSettingsUtils.ts
> +  const pvcSize = Number(jupyterhubCfgResponse.body.data.singleuser_pvc_size.replace('Gi', ''));
Same issue here, what if it is less than a gig?

2022-07-27 12:44 UTC, maroroman commented on backend/.eslintrc
> +    "prefer-const": "warn",
There was an issue I was having with a tuple, but it was just new syntax for me, removed the warn.

2022-07-27 13:02 UTC, maroroman commented on backend/src/routes/api/cluster-settings/clusterSettingsUtils.ts
>        if (jupyterhubCM.body.data.singleuser_pvc_size.replace('Gi', '') !== query.pvcSize) {
The UI doesn't seem to allow any size lower than 1Gi so I assumed Gi here

2022-07-27 14:04 UTC, andrewballantyne commented on backend/src/routes/api/cluster-settings/clusterSettingsUtils.ts
>        if (jupyterhubCM.body.data.singleuser_pvc_size.replace('Gi', '') !== query.pvcSize) {
I'm not entirely sure if that's the case. We'll be adding configurations in to allow for custom notebooks, I'd imagine they have the power to do whatever they want. But we can go with this for now if it's not possible to adjust it any lower.

I know this one is on JH config map, so maybe it's not the same restriction for KFNBC?

2022-07-27 14:09 UTC, erwangranger commented on backend/src/routes/api/cluster-settings/clusterSettingsUtils.ts
>        if (jupyterhubCM.body.data.singleuser_pvc_size.replace('Gi', '') !== query.pvcSize) {
this drives the PVC size. On AWS, these PVCs are backed by EBS volumes. (sorry for the acronym soup). 
An EBS volume cannot be less that 1 GiB.

2022-07-27 14:12 UTC, andrewballantyne commented on backend/src/routes/api/cluster-settings/clusterSettingsUtils.ts
>        if (jupyterhubCM.body.data.singleuser_pvc_size.replace('Gi', '') !== query.pvcSize) {
Well, that sounds pretty safe to assume Gi then. I appreciate you jumping in here @erwangranger -- seemed like a logical fallacy to assume gig, glad there is something preventing us from worrying about it.

2022-07-28 09:34 UTC, maroroman commented on backend/src/routes/api/cluster-settings/clusterSettingsUtils.ts
> +        await coreV1Api.patchNamespacedConfigMap(
Wrapped the patch into a function.

2022-07-28 13:53 UTC, andrewballantyne requested changes

2022-07-28 13:53 UTC, andrewballantyne commented on backend/src/routes/api/cluster-settings/clusterSettingsUtils.ts
> +      console.log(e.response.body.message);
Please remove debug code

2022-07-29 17:09 UTC, samuelvl approved these changes
It works great! 

/lgtm

2022-07-29 21:02 UTC, andrewballantyne approved these changes

2022-07-29 21:03 UTC, merged