Fixes Image selection dropdown scroll issue
opendatahub-io/odh-dashboard pull request #2696
Opened 2024-04-10 13:54 UTC by manaswinidas

Closes: https://issues.redhat.com/browse/RHOAIENG-3412

## Description

Fixes the image selection dropdown scroll issue. Created a separate PF5 variant of `SimpleDropdown` component. Need to test other components using this before migrating completely to PF5.

<img width="1301" alt="Screenshot 2024-04-10 at 7 23 06 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/22885912/2e834813-9712-4275-b6b2-f4927d5c8d80">

https://github.com/opendatahub-io/odh-dashboard/assets/22885912/3d8af954-c3cf-4d6c-8702-b14b5096b359

## How Has This Been Tested?

Try creating a workbench after creating many custom images using the `Notebook images` section in the `Settings` section in the Dashboard. You should see a scroll bar while trying to select images in the `Image selection` and this doesn't break the layout. 

## Test Impact

The current tests pass. This is a layout issue. Manually tested. 

## Request review criteria:

Self checklist (all need to be checked):
- [X] The developer has manually tested the changes and verified that the changes work
- [X] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [X] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-04-10 16:41 UTC, lucferbux requested changes
Ok a couple of things here:

Have you tested wether this fix the issue? I would think it's still happening if we still have the css.

We should have coverage with mockup data that might be recreating the issue, we can talk about that async if you want.

Is this refactor gonna help other instances of this? Maybe we should just fix the issue of the height and do the refactor in another issue OR just do the refactor in all the instances, but it's not a great idea having both components.

2024-04-12 13:57 UTC, dpanshug approved these changes
/lgtm

2024-04-12 13:58 UTC, manaswinidas commented
@lucferbux Fixed all test failures arising due to the migration. Added a new test to test scrollable dropdown selection as requested. Even manually tested the views on the pages, seems to work fine. The CSS file you mentioned seems to fix some width issues instead of height and I think it's required coz the extra padding persists if we remove that CSS. This is ready for review.

2024-04-12 15:09 UTC, manaswinidas commented
/lgtm Readding the label coz the last force-push only included a Cypress function name change from `findDropdownItemById` to `findByDropdownId`

2024-04-12 15:25 UTC, christianvogt commented on frontend/src/__tests__/cypress/cypress/support/commands/application.ts
> +      findByDropdownItemId(testId: string): Cypress.Chainable<JQuery>;
```suggestion
      findDropdownItemByTestId(testId: string): Cypress.Chainable<JQuery>;
```

2024-04-12 17:07 UTC, lucferbux approved these changes
/lgtm

Had to check the part of `testId` prop, but I think that's the only solution we can go for now, since that's how patternfly recommends using the testing id.

2024-04-12 17:37 UTC, merged