Cypress test for Administration tab
opendatahub-io/odh-dashboard pull request #2724
Opened 2024-04-18 15:00 UTC by ppadti

Closes: [RHOAIENG-3919](https://issues.redhat.com/browse/RHOAIENG-3919)

## Description
This PR aims to add cypress test for administration tab.

## How Has This Been Tested?
`npm run test`

## Test Impact

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-04-19 11:31 UTC, pnaik1 requested changes

2024-04-19 11:31 UTC, pnaik1 commented on frontend/src/__tests__/cypress/cypress/e2e/applications/Administration.cy.ts
> +describe('Administration Page', () => {
Since this is a tab
```suggestion
describe('Administration Tab', () => {
```

2024-04-19 11:31 UTC, pnaik1 commented on frontend/src/__tests__/cypress/cypress/e2e/applications/Administration.cy.ts
> +    administration.findReturnToAdminViewButton().click();
Can you please add  test cases for `Stop all server` button

2024-04-19 20:36 UTC, christianvogt commented
This PR may be impacted by https://github.com/opendatahub-io/odh-dashboard/pull/2727 which changes the default user to be a project admin.

2024-04-22 12:22 UTC, ppadti commented
> This PR may be impacted by #2727 which changes the default user to be a project admin.

Once #2727 is merged, I will update it accordingly.

2024-04-23 12:48 UTC, uidoyen reviewed
tested locally.

2024-04-23 12:49 UTC, uidoyen commented
/lgtm

2024-04-23 12:52 UTC, merged