chore(dw): refactor otherUsage and getWorkloadName
opendatahub-io/odh-dashboard pull request #2735
Opened 2024-04-19 20:32 UTC by gitdallas

As part of https://issues.redhat.com/browse/RHOAIENG-5293

## Description
addressing a couple PR nits, it was already mostly taken care of throughout some other PRs that went in (moving things to utility classes/etc)

## How Has This Been Tested?
ran tests, ran app, made sure it still works

## Test Impact
updated tests with new data structure

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-04-19 20:42 UTC, mturley approved these changes
LGTM

2024-04-22 14:51 UTC, andrewballantyne commented on frontend/src/api/prometheus/distributedWorkloads.ts
> +  { totalUsage: number; topWorkloads: WorkloadWithUsage[]; otherUsage: number | undefined }
I am wondering if we should be looking at making this a type 🤔 I assume this is passed around... it's a type that is at least updated twice in this file alone

2024-04-22 14:52 UTC, andrewballantyne commented on frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/TopResourceConsumingWorkloads.tsx
> +  data: { totalUsage: number; topWorkloads: WorkloadWithUsage[]; otherUsage: number | undefined };
Definitely need a type.

2024-04-22 14:54 UTC, andrewballantyne requested changes

2024-04-22 14:54 UTC, andrewballantyne commented on frontend/src/concepts/distributedWorkloads/utils.tsx
> +  workload === 'other' ? 'Other' : workload.metadata?.name || 'Unnamed';
Correct me if I am wrong here -- but you never pass `other` 🤔

2024-04-22 18:45 UTC, gitdallas commented
@andrewballantyne -resolved

2024-04-25 20:09 UTC, andrewballantyne approved these changes

2024-04-25 20:32 UTC, merged