[WIP] Home page: projects w/ tiles
opendatahub-io/odh-dashboard pull request #2741
Opened 2024-04-23 11:21 UTC by jeff-phillips-18

Closes: [RHOAIENG-5489](https://issues.redhat.com/browse/RHOAIENG-5489)

## Description
Add project tiles to the home page projects section.

## How Has This Been Tested?
Locally tested while turning the home page feature floag on

## Test Impact
Added e2e tests

## Screen shots

### Full tiles w/ self-provisioning access
![image](https://github.com/opendatahub-io/odh-dashboard/assets/11633780/fd490479-4f0c-4aff-b23b-e3999cbcea10)

### Full tiles w/o self-provisioning access
![image](https://github.com/opendatahub-io/odh-dashboard/assets/11633780/96bdc088-f498-4360-810c-8e3b922aa3aa)

### Less tiles w/ self-provisioning access
![image](https://github.com/opendatahub-io/odh-dashboard/assets/11633780/d30e780e-10ad-42a1-8570-55e13ed54548)

### Less tiles w/o self-provisioning access
![image](https://github.com/opendatahub-io/odh-dashboard/assets/11633780/94c5d2e3-f44f-4a93-a95f-df3b451604e2)

## Request review criteria:
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)
- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

/cc @jgiardino

2024-04-23 18:43 UTC, andrewballantyne requested changes

2024-04-24 10:04 UTC, jeff-phillips-18 commented on frontend/src/pages/home/projects/ProjectCard.scss
The issue is the truncated link for the name of the project in the card. I couldn't find styles to make it work due to the need to set the width on a PF created element. I can make a reusable component (concept) but I highly doubt it would ever get reused.

2024-04-24 10:05 UTC, jeff-phillips-18 commented on frontend/src/components/TruncatedText.tsx
> +      WebkitLineClamp: maxLines,
Should work in all browsers. I've tested Chrome, Safari, Firefox, an Edge. This is the same styles that were used in the resource cards descriptions just pulled out into a component that can be reused and used for different numbers of lines.

2024-04-24 15:29 UTC, andrewballantyne commented on frontend/src/components/TruncatedText.tsx
> +      {...rest}
Ah interesting -- FWIW, if you provide `style` in `rest` you'll lose the primary purpose of the component

2024-04-24 15:36 UTC, andrewballantyne approved these changes

2024-04-24 15:39 UTC, merged

2024-04-24 15:42 UTC, jgiardino commented on frontend/src/pages/home/projects/CreateProjectCard.tsx
> +                  <Text component="h3">Need another project?</Text>
This font size looks really large relative to other contents on the page.
I'm also not seeing an `h2` level heading after the `h1` for the "Projects" section header. 

<img width="1210" alt="image" src="https://github.com/opendatahub-io/odh-dashboard/assets/21063328/9d039dbf-f48e-493c-afe6-4f35402c80d3">


One suggestion here is to use the `h2` combined with a utility class for the font size:
```
<Text component="h3" class="pf-v5-u-font-size-sm" >Need another project?</Text>
```
When I look at the current design document, the `sm` size is used for this text.

2024-04-24 15:43 UTC, jgiardino commented
Oh no! I just posted a comment and saw that this PR was merged. 😬 
I was also going to say that these updates look really good. That one comment was the only thing I saw. But it's also really minor.

2024-04-24 17:21 UTC, andrewballantyne commented
@jgiardino if you get to it late you get to it late. @jeff-phillips-18 should still react to your feedback and he can sneak small things into future work or craft a new issue if it's larger. We don't usually wait on UX reviews as there will be more reviews later once the work is more complete.