[RHOAIENG-5496] Landing page: New home page hint
opendatahub-io/odh-dashboard pull request #2752
Opened 2024-04-26 19:12 UTC by jeff-phillips-18

Closes: [RHOAIENG-5496](https://issues.redhat.com/browse/RHOAIENG-5496)

## Description
Adds a hint to the landing page directing users how to find the previous landing page

## How Has This Been Tested?
Tested locally

## Test Impact
Added e2e tests

## Screenshots

![image](https://github.com/opendatahub-io/odh-dashboard/assets/11633780/0965e582-412d-43ee-90b4-681481b106b7)

![image](https://github.com/opendatahub-io/odh-dashboard/assets/11633780/a63544c4-a9c5-4556-b469-c5d3d8e4b619)

## Request review criteria:
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)
- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

/cc @jgiardino

2024-04-26 19:29 UTC, jgiardino commented
The updates look great! There are a few things that would be good to address if possible:
* Can you add the same border radius that we have on the project cards to this card?
* Can there be a max-width of 880px applied to the contents?
* Can the link use the same font size as the surrounding text?

2024-04-29 17:47 UTC, andrewballantyne requested changes

2024-04-29 17:47 UTC, andrewballantyne commented on frontend/src/__tests__/cypress/cypress/e2e/home/home.cy.ts
Can you write another test to ignore this when `notebookController` is disabled. You'll have to update our mock & your code to look at the OdhDashboardConfig `.spec.notebookController.enabled` field (I don't think there is an area for this)

2024-04-29 17:47 UTC, andrewballantyne commented on frontend/src/pages/home/resources/useResourcesSection.tsx
> +                  }}
Hmmm... This feels like a sneaky addition -- can you explain the reason for this change?

2024-04-29 17:48 UTC, andrewballantyne commented on frontend/src/pages/home/resources/useResourcesSection.tsx
> +                  }}
Looks like based on UX's feedback (missed those comments lol) -- this is a fine change -- next time we shouldn't be addressing random unrelated feedback in the PRs as it pollutes the tickets & PRs and makes it hard to trace origins.

2024-04-29 17:56 UTC, jeff-phillips-18 commented on frontend/src/__tests__/cypress/cypress/e2e/home/home.cy.ts
What are you expecting to see differently when `.spec.notebookControoler.enabled` is `false`?

2024-04-29 19:18 UTC, jeff-phillips-18 commented on frontend/src/__tests__/cypress/cypress/e2e/home/home.cy.ts
I have added the check and if notebooks controller is disabled we do not show the hint. Added a test for this functionality.

2024-04-30 14:03 UTC, andrewballantyne approved these changes

2024-04-30 14:05 UTC, merged