Update global pipelines cypress test
opendatahub-io/odh-dashboard pull request #2771
Opened 2024-05-02 07:44 UTC by ppadti

Closes: [RHOAIENG-3820](https://issues.redhat.com/browse/RHOAIENG-3820)

## Description
This PR aims to add additional cypress test to global pipeline page. That includes:
- Configure pipeline server
-  delete pipeline server
- view pipeline configuration
- table sorting, filtering.

## How Has This Been Tested?
`npm run test`

## Test Impact

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-05-02 10:45 UTC, pnaik1 requested changes

2024-05-02 10:45 UTC, pnaik1 commented on frontend/src/__tests__/cypress/cypress/e2e/pipelines/Pipelines.cy.ts
> +    configurePipelineServerModal.findRegionInput().type('us-east-1');
The region field has default value `us-east-1`

2024-05-02 10:45 UTC, pnaik1 commented on frontend/src/__tests__/cypress/cypress/e2e/pipelines/Pipelines.cy.ts
> +  });
Can you please add test cases for prefill from a Data Connection dropdown?

2024-05-02 10:45 UTC, pnaik1 commented on frontend/src/__tests__/cypress/cypress/e2e/pipelines/Pipelines.cy.ts
> +    configurePipelineServerModal.findConfigurePipelineButton().click();
Can you add please test cases for database input as well?

2024-05-03 05:04 UTC, pnaik1 commented
/lgtm

2024-05-03 12:39 UTC, alexcreasy approved these changes
Looks good!
/approve

2024-05-03 13:07 UTC, merged