[WIP] Model Version - View
opendatahub-io/odh-dashboard pull request #2773
Opened 2024-05-02 17:49 UTC by dpanshug

Closes: [RHOAIENG-2238](https://issues.redhat.com/browse/RHOAIENG-2238)

## Description
View for model version detail page with version selector at top

## How Has This Been Tested?

## Test Impact

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-05-02 17:50 UTC, dpanshug commented
To be merged after #2770

2024-05-03 09:00 UTC, manaswinidas requested changes

2024-05-03 09:02 UTC, dpanshug commented on frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetails.tsx
> +          />
yes, correcting it

2024-05-03 11:46 UTC, closed without merging

2024-05-03 11:50 UTC, dpanshug commented
Sorry i've closed this PR by mistake, opened another #2774