Show correct artifact run node details on artifact side drawer panel
opendatahub-io/odh-dashboard pull request #2885
Opened 2024-06-06 19:26 UTC by DaoDaoNoCode

JIRA: https://issues.redhat.com/browse/RHOAIENG-7544

## Description

Updated the way we search for the artifact details for a specific node. Also, I removed the status for the artifact node because an artifact node shouldn't have status. (I checked that in KF UI)

<img width="1728" alt="Screenshot 2024-06-06 at 3 22 58 PM" src="https://github.com/opendatahub-io/odh-dashboard/assets/37624318/acedc1bb-fc1b-4ddf-8be5-55a1a9a22a4c">

## How Has This Been Tested?

1. Import the pipeline listed in the JIRA ticket
2. Create a run using that pipeline
3. Compare the artifact details with the KF UI to make sure the info is correct

## Test Impact

N/A, it's topology side panel details change, hard to write test.

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-06-07 14:52 UTC, Gkrumbach07 commented
@DaoDaoNoCode I think Yan wants artifact nodes to be green if they exist and then grey otherwise

see this mock: https://www.figma.com/design/etbN0ccCcZR1qKCpJXQNAg/Pipeline-phase-2?node-id=1585-97434&t=BZENynAkmHo29x6Z-0

2024-06-07 17:26 UTC, DaoDaoNoCode commented
@Gkrumbach07 Updated PR based on the mockup

2024-06-07 18:20 UTC, Gkrumbach07 requested changes
works fine just one comment

2024-06-07 18:20 UTC, Gkrumbach07 commented on frontend/src/concepts/topology/utils.ts
> +    runStatus: pipelineTask.metadata ? RunStatus.Succeeded : RunStatus.Skipped,
not skipped but just no status

2024-06-07 22:12 UTC, Gkrumbach07 commented
This looks good. we just need one more reviewer to merge

/lgtm

2024-06-11 13:37 UTC, jenny-s51 approved these changes
LGTM @DaoDaoNoCode , tested in UI and against KF - artifact panel renders data as expected.

2024-06-11 14:16 UTC, Gkrumbach07 approved these changes
/approve

2024-06-11 14:30 UTC, merged