[WIP] ]support feature flag overrides via query string
opendatahub-io/odh-dashboard pull request #2945
Opened 2024-06-21 21:49 UTC by christianvogt

https://issues.redhat.com/browse/RHOAIENG-7894

## Description

Once feature flags are overridden in the current session a banner is displayed at the top of the page. From the banner the user can restore their session without the need for closing their browser window. They can also open a modal to more easily adjust the feature flags for the current session.
![image](https://github.com/opendatahub-io/odh-dashboard/assets/14068621/d16e6fb7-5efd-4b5e-9050-f78650a82e62)

The modal lists all available feature flags and their current state. Flags that have been overridden in the session via query string or through this model are annotated as `(overridden)`. If the current dashboard config doesn't contain a valid entry (likely only a dev issue with a mismatched frontend and backend), the checkbox will be in the partially checked state.
![image](https://github.com/opendatahub-io/odh-dashboard/assets/14068621/e15d4f2e-1ef3-49ef-899b-f9363d7e5b79)

Changes to feature flags are immediately reflected in the UI.

Restoring defaults will immediately remove the banner.

To enable this feature, set the query string param to `?devFeatureFlags`.
To adjust the feature flags via the query string, assign a value: `?devFeatureFlags=home,disableInfo,disableAppLauncher=false,enablement=true`
Note that the query string accepts both variants of a flag which has the `disable` prefix or not. eg. `disableHome=true` is the same as `home=false`, or `disableHome=false` is the same as `home` or `home=true`

Some backend end points such as `/api/cluster-settings` reads from the dashboard config cached on the backend. In order to get around this caching, if feature flags are overridden in the front end, a new header is sent along with all requests. See `x-odh-feature-flags`.

## How Has This Been Tested?

Open any page and then change the query string to be `?devFeatureFlags=...` where `...` is either empty or a feature flag of your choice. eg `home`

Play around with the banner and feature flag modal.

As an admin navigate to `Settings => Cluster settings` and inspect the network tab. Look for the `/api/cluster-settings` call and inspect the response such that the enablement matches the front end feature flag settings:
```
    "modelServingPlatformEnabled": {
        "kServe": true,
        "modelMesh": true
    }
```

## Test Impact

Added unit tests.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-06-24 13:41 UTC, andrewballantyne requested changes
Some typos.

I'm a little weary of the reliance on Axios; I had hoped to get rid of it in time as `fetch` can do all the needed items and it is one less dependency. Also, it's going to be interesting how the data only gets to the DashboardConfig on the backend when it is through a request of the frontend -- this will have weird edge cases in upgrades and refreshing the cache of the DashboardConfig. But maybe it won't be too problematic.

This looks great, even if it has potentially some limitations. This is a huge step forward for testing. 

I guess the question is, is this problematic on fully prod clusters 🤔 And I'm thinking no... because the backend DSC flags can still be disabled to stop flows.

2024-06-24 13:41 UTC, andrewballantyne commented on frontend/src/app/__tests__/DevFeatureFlagsBanner.spec.tsx
> +  it('should render not render if no feature flags are overridden', () => {
```suggestion
  it('should not render if no feature flags are overridden', () => {
```

2024-06-24 13:41 UTC, andrewballantyne commented on frontend/src/app/useDevFeatureFlags.ts
> +    // compares against oroginal sessionFlags object on purpose and not the sanitizedSessionFlags
```suggestion
    // compares against original sessionFlags object on purpose and not the sanitizedSessionFlags
```

2024-06-25 13:00 UTC, christianvogt commented on frontend/src/app/App.tsx
> +                {...devFeatureFlags}
Renamed to `devFeatureFlagsProps`

2024-06-25 13:08 UTC, christianvogt commented
> this will have weird edge cases in upgrades and refreshing the cache of the DashboardConfig. But maybe it won't be too problematic.

This is strictly a means for testing so any limitations are ok. That being said, upgrades will always use the config that's found on cluster. A frontend with session dev flags will still pick up any config changes from the cluster so long as they haven't overridden those flags that are changing; the UI will update accordingly.

> I guess the question is, is this problematic on fully prod clusters 🤔 And I'm thinking no... because the backend DSC flags can still be disabled to stop flows.

@andrewballantyne can you elaborate on this question.

2024-06-25 14:29 UTC, andrewballantyne commented
> > this will have weird edge cases in upgrades and refreshing the cache of the DashboardConfig. But maybe it won't be too problematic.
> 
> This is strictly a means for testing so any limitations are ok. That being said, upgrades will always use the config that's found on cluster. A frontend with session dev flags will still pick up any config changes from the cluster so long as they haven't overridden those flags that are changing; the UI will update accordingly.

This is a good point. It just has gaps that won't be able to be used for verification but there should be alternatives to getting around that without too much concern. Thanks.

> > I guess the question is, is this problematic on fully prod clusters 🤔 And I'm thinking no... because the backend DSC flags can still be disabled to stop flows.
> 
> @andrewballantyne can you elaborate on this question.

Well, consider a public hosted OpenShift AI -- allowing users to flip things on may reveal functionality not intended for use and a feature flag is not able to stop it now. Most features are backed by an OpenShift AI backend component, so it being disabled should be enough to stop functionality. 

But if a backend component is available, and the UI is disabled -- this could allow for enabling features not intended for public consumption. Although, I'm not sure that has a huge problem 🤔 Or maybe a flow that is K8s as the backend... that could be problematic too as there is "no way" to turn it off.

2024-06-25 14:33 UTC, andrewballantyne commented on frontend/src/app/useDevFeatureFlags.ts
> + *  - disableHome = true
Oh... I wanna say if I read the code this is a documentation bug not a functionality bug.

```suggestion
 * `devFeatureFlags=disableHome=false,appLauncher,support=true`
 * Results in:
 *  - disableHome = false
```

2024-06-25 14:49 UTC, christianvogt commented
> But if a backend component is available, and the UI is disabled -- this could allow for enabling features not intended for public consumption. Although, I'm not sure that has a huge problem 🤔 Or maybe a flow that is K8s as the backend... that could be problematic too as there is "no way" to turn it off.

The only extra bit of functionality this enables is the ability to supply feature flags to backend points that happen to use them. Today it is already possible for someone to enable all features themselves with dev tools in the browser without the need for changing the dashboard config.

2024-06-25 15:34 UTC, christianvogt commented
@andrewballantyne Thanks for the review. Sorry but just I added an extra feature  :)

While the modal is open, the query param is now visible and updated in real time. This gives the ability to more easily construct the URL, bookmark it and share it. While the modal is closed the query string param is once again removed to best represent a normal user experience.

Do you think we should also include a `hide` banner option so that we can utilize this feature for screenshots without the extra clutter? I can see this as useful and hides the banner until the page refreshes.

2024-06-26 21:00 UTC, mturley approved these changes
LGTM, pulled locally and tested, this is really awesome stuff

2024-06-26 21:16 UTC, merged