Update depricated PF multiselect component
opendatahub-io/odh-dashboard pull request #2975
Opened 2024-07-02 19:40 UTC by ashley-o0o

Closes: [RHOAIENG-421](https://issues.redhat.com/browse/RHOAIENG-421)

## Description
This PR updates the deprecated Patternfly 4 select component with the PF5 [multi select component](https://www.patternfly.org/components/menus/select/#multiple-typeahead-with-chips)

## How Has This Been Tested? 
This is tested with `npm run test` as well as on localhost, and using the Cypress tests in `userManagement.cy.ts`

## Test Impact
No new tests were added as there are no functionality changes 

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-07-04 15:26 UTC, christianvogt commented
- When I first click into the input field, my focus is lost and I need to click again before I can type.
- After using the keyboard to highlight an item in the dropdown, pressing `enter` no longer selects / deselects that item.
- After focusing the text input with the keyboard, pressing an arrow key no longer opens the menu. This behavior works in the PF example.
- Previously I could not focus the arrow dropdown button. This made sense since the menu is controlled by focusing on the input field. Now I can also tab to the toggle button. The toggle button should not be focusable as per the PF example.

2024-07-05 19:04 UTC, jeff-phillips-18 requested changes

2024-07-05 19:04 UTC, jeff-phillips-18 commented on frontend/src/components/MultiSelection.tsx
> +        <SelectList isAriaMultiselectable id="select-multi-typeahead-listbox">
the id should be unique across multiple MultiSelection components

2024-07-05 19:04 UTC, jeff-phillips-18 commented on frontend/src/components/MultiSelection.tsx
> +        id="multi-typeahead-select"
the id should be unique across multiple MultiSelection components

2024-07-05 19:06 UTC, jeff-phillips-18 commented
> * Previously I could not focus the arrow dropdown button. This made sense since the menu is controlled by focusing on the input field. Now I can also tab to the toggle button. The toggle button should not be focusable as per the PF example.

This is a PF issue. Though it works on the documentation page, if you try the code sandbox it does not and the toggle button is in the tab order for focus.

2024-07-05 19:08 UTC, christianvogt commented on frontend/src/components/MultiSelection.tsx
> +          id="multi-typeahead-select-input"
Unless referenced by some aria tag we can likely just remove all `id` attributes.

2024-07-09 19:32 UTC, jeff-phillips-18 approved these changes

2024-07-09 21:46 UTC, jeff-phillips-18 commented on frontend/src/components/MultiSelection.tsx
> +    if (isOpen) {
This is not resovled

2024-07-09 21:48 UTC, jeff-phillips-18 commented on frontend/src/components/MultiSelection.tsx
> +    if (isOpen) {
Since this is back again: if it is not open, it should be opened and just return.

2024-07-09 21:48 UTC, jeff-phillips-18 commented
/lgtm cancel

2024-07-11 15:39 UTC, jeff-phillips-18 approved these changes
/lgtm

2024-07-11 19:35 UTC, jeff-phillips-18 commented
/lgtm cancel

2024-07-16 12:46 UTC, jeff-phillips-18 approved these changes
/lgtm

2024-07-16 20:53 UTC, christianvogt commented
/approve

2024-07-16 21:05 UTC, merged