Remove the DS project list toggle
opendatahub-io/odh-dashboard pull request #3018
Opened 2024-07-19 12:29 UTC by ppadti

Closes: [RHOAIENG-9576](https://issues.redhat.com/browse/RHOAIENG-9576)

## Description
This PR aims to remove the DS project list toggle.

![Screenshot from 2024-07-19 15-55-16](https://github.com/user-attachments/assets/5ba86311-9b7e-4f70-959a-97018c25ad38)

## How Has This Been Tested?
In DS list page, we will not be having a toggle to switch projects.

## Test Impact
Updated cypress test.

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-07-19 12:52 UTC, ppadti commented
@kywalker-rh @xianli123 could you please take a look the UI changes?
One quick question, In project list page we had a image beside DS project name. I removed it in this PR. I just wanted to know that Is it fine to have list of project without that image or you prefer to have it for all the projects. Let me know your thoughts on this.

screenshot of the image I am talking about for ref:

![Screenshot from 2024-07-19 18-21-47](https://github.com/user-attachments/assets/5b42bba7-871e-432d-bc37-f6bbb2d98668)

2024-07-19 14:53 UTC, andrewballantyne requested changes

2024-07-19 14:53 UTC, andrewballantyne commented on frontend/src/pages/projects/screens/projects/ProjectTableRow.tsx
>                      <FlexItem>
I think you can drop the flex, no?

2024-07-19 14:54 UTC, andrewballantyne commented
> @kywalker-rh @xianli123 could you please take a look the UI changes? One quick question, In project list page we had a image beside DS project name. I removed it in this PR. I just wanted to know that Is it fine to have list of project without that image or you prefer to have it for all the projects. Let me know your thoughts on this.
> 
> screenshot of the image I am talking about for ref:
> 
> ![Screenshot from 2024-07-19 18-21-47](https://private-user-images.githubusercontent.com/99261071/350394645-5b42bba7-871e-432d-bc37-f6bbb2d98668.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MDExMTMsIm5iZiI6MTcyMTQwMDgxMywicGF0aCI6Ii85OTI2MTA3MS8zNTAzOTQ2NDUtNWI0MmJiYTctODcxZS00MzJkLWJjMzctZjZiYmIyZDk4NjY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE0NTMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZjhkNjJlNjhhN2FjMDFmNzJjMGU4ZWQwNjZlOTJmMTljNWExMTUyOThmMzkzNDIwZjJjYjI2ZDdjOWZjMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bgx5S5YceM-X55gKA4N8cogVBUMA_krNXowo1N6m-1I)

I'll step in here 🙂 Yes, we do need to get rid of the identifier. We are looking to get so far away from this concept of "Data Science Projects are different" that we are even RFE-ing a rename of this page to just `Projects`. So definitely get rid of it 👍

2024-07-24 21:00 UTC, mturley approved these changes
LGTM and tested locally! Awesome to finally have this weird toggle gone.

2024-07-24 21:07 UTC, gitdallas approved these changes

2024-07-24 21:30 UTC, merged