Add definition of ready and done
opendatahub-io/odh-dashboard pull request #3031
Opened 2024-07-24 14:13 UTC by jessiehuff

Closes https://issues.redhat.com/browse/RHOAIENG-10271 

## Description
We need our [Definition of Done](https://docs.google.com/document/d/1A3Y4P04MVlovOK1XvUZL8SpQ0wY94LwQsxe8DwEGoGE/edit) and [Definition of Ready](https://docs.google.com/document/d/1JP8FlysPrsEH5mfx4Jq6t-jr1XBIORS5PoRpeSMkNt8/edit) docs moved into markdown files in the docs folder and our contribution markdown file updated to point at those

## How Has This Been Tested?
N/A (Non-code change)

## Test Impact
N/A

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-07-24 18:11 UTC, Griffin-Sullivan reviewed
From the perspective of someone new who just went through all of the dev setup and contributing docs: LGTM

2024-07-24 18:11 UTC, Griffin-Sullivan commented on docs/definition-of-done.md
> +- Screenshots of the updated UI should be captured in the jira history/comments (or link to GitHub Pull Request with these screenshots) to illustrate work that was completed.
```suggestion
- Screenshots of the updated UI should be captured in the Jira history/comments (or link to GitHub Pull Request with these screenshots) to illustrate work that was completed.
```
Jira was capitalized everywhere else

2024-07-24 18:11 UTC, Griffin-Sullivan commented on docs/definition-of-ready.md
> +13. Dependencies and backend component apis should be fully ready (including v2 Operator support built-in).  These features could be enabled via DevFlags if needed but should not be installed via scr
```suggestion
13. Dependencies and backend component APIs should be fully ready (including v2 Operator support built-in).  These features could be enabled via DevFlags if needed but should not be installed via scripts or yaml files provided by the backend team.  
```

2024-07-25 20:01 UTC, andrewballantyne requested changes

2024-07-25 20:05 UTC, andrewballantyne commented
@jessiehuff please update the text from @Griffin-Sullivan, we can look to merge this and iterate as needed.

2024-07-25 20:39 UTC, andrewballantyne approved these changes

2024-07-25 20:53 UTC, merged