define the connection type config map typescript types
opendatahub-io/odh-dashboard pull request #3045
Opened 2024-07-30 18:12 UTC by christianvogt

https://issues.redhat.com/browse/RHOAIENG-10310

## Description

Defines the typescript types used to describe connection types. 
A connection type is stored in a config map. 

A connection type is an ordered collection of field descriptors. Each descriptor typed by a unique string identifier which identifies the corresponding field type. The field type is used to associate a rendered which knows how to consume their specific properties.

Note. The current field types are based on a non-finalized version of the UX. Therefore the fields and field properties are subject to change. However the general structure will remain the same.

## How Has This Been Tested?

Manually.
No automated tests. Only new types are contributed.

## Test Impact

N/A

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-07-30 18:13 UTC, christianvogt commented
@andrewballantyne we use annotations for storing display name and descriptions for k8s resources. While that approach continues to work here, it could be argued that these properties should be part of the connection type definition and therefore live within the config map data itself. I'm indifferent to either approach. Do you have an opinion?

2024-07-30 18:39 UTC, andrewballantyne requested changes
One request, we make a concepts area for this effort. Everything else looks good.

2024-07-30 18:39 UTC, andrewballantyne commented on frontend/src/api/connectionTypes/types.ts
Can we put this in concepts? It's going to be the type we use and destrcture everywhere -- it's not just the API transfer structure

2024-07-30 18:45 UTC, christianvogt commented on frontend/src/api/connectionTypes/types.ts
ha, i had it there first and 2nd guessed the location

2024-07-31 15:04 UTC, emilys314 commented
/lgtm seems good to me

2024-07-31 17:51 UTC, emilys314 commented
/lgtm

2024-07-31 17:56 UTC, merged