Translate username in Notebook label and dashboard config user states
opendatahub-io/odh-dashboard pull request #320
Opened 2022-07-18 20:07 UTC by DaoDaoNoCode

Closes #316 
There is an issue to generate a userState entry with username equals to a `''`, I also fixed that in this PR.

2022-07-18 20:23 UTC, andrewballantyne requested changes

2022-07-18 20:29 UTC, DaoDaoNoCode commented on frontend/src/pages/notebookController/SpawnerPage.tsx
> +  }, [dashboardConfig, translatedUsername]);
Updated, thanks!

2022-07-18 20:36 UTC, andrewballantyne requested changes
`useMemo` is just `useEffect` to save in a `useState`... you do still need to get the data out of a `useMemo`.

See the documentation https://reactjs.org/docs/hooks-reference.html#usememo

2022-07-18 20:36 UTC, andrewballantyne commented on frontend/src/pages/notebookController/SpawnerPage.tsx
> +  }, [dashboardConfig, translatedUsername]);
```suggestion
  const userState = React.useMemo(() => {
    if (translatedUsername) {
      const newUserState = dashboardConfig?.spec.notebookControllerState?.find(
        (state) => state.user === translatedUsername,
      );
      return newUserState;
    } else {
      return EMPTY_USER_STATE;
    }
  }, [dashboardConfig, translatedUsername]);
```

2022-07-18 21:30 UTC, DaoDaoNoCode commented on frontend/src/pages/notebookController/SpawnerPage.tsx
> +    }
LOL, I didn't even notice this, thanks for the fix!

2022-07-18 22:03 UTC, andrewballantyne approved these changes
heh, sorry about the typo -- I'll try to write them in my IDE before giving them here

2022-07-18 22:04 UTC, andrewballantyne reviewed
Ah you got a linter failure... it wants to reorganize the import line breaks. Weird that wasn't there before 🤔 run `npm run lint` in the frontend folder and fix the errors.

2022-07-19 10:35 UTC, samuelvl commented
I could spawn a notebook with a normal user and with `kube:admin`:

```
$ oc get pods -l opendatahub.io/user=kube-3aadmin
NAME                        READY   STATUS    RESTARTS   AGE
jupyter-nb-kube-3aadmin-0   2/2     Running   0          75s
```

2022-07-19 10:35 UTC, samuelvl approved these changes

2022-07-19 10:36 UTC, merged