Update frontend to be able to map env vars into notebook container
opendatahub-io/odh-dashboard pull request #331
Opened 2022-07-20 16:32 UTC by DaoDaoNoCode

Closes #324

2022-07-20 16:32 UTC, DaoDaoNoCode commented
/hold until #275 get merged.

2022-07-21 18:18 UTC, andrewballantyne requested changes

2022-07-21 18:18 UTC, andrewballantyne commented on frontend/src/pages/notebookController/SpawnerPage.tsx
> +    );
Do we not want this as a stand alone function and provide it to `checkEnvVarFile` and also use it in createNotebook... looks as if you're doing too many things in `checkEnvVarFile` function to just in the end return the value you want for the notebook.

2022-07-21 19:57 UTC, DaoDaoNoCode commented on frontend/src/pages/notebookController/SpawnerPage.tsx
> +    async (isSecret: boolean, callback: (name: string) => Promise<ConfigMap | Secret>) => {
I will avoid making any generic function for now because this is a particular usage for these two resources currently.

2022-07-22 03:25 UTC, andrewballantyne requested changes
Can you log a tech debt ticket on github for us to look to refactor the SpawnerPage? It's rough to read and I'd like to break it up more -- let us not worry about it now so we don't lose any time / potentially break something.

Also, could you apply this patch and see that you have a type issue RE: patching the dashboard config

```
diff --git a/frontend/config/webpack.common.js b/frontend/config/webpack.common.js
index 477d35d..ce749a7 100644
--- a/frontend/config/webpack.common.js
+++ b/frontend/config/webpack.common.js
@@ -35,7 +35,7 @@ module.exports = env => {
             {
               loader: 'ts-loader',
               options: {
-                transpileOnly: true,
+                transpileOnly: env !== 'development',
                 experimentalWatchApi: true
               }
             }
diff --git a/frontend/config/webpack.dev.js b/frontend/config/webpack.dev.js
index 47fe7c8..1ad63bd 100644
--- a/frontend/config/webpack.dev.js
+++ b/frontend/config/webpack.dev.js
@@ -32,7 +32,7 @@ module.exports = merge(
       inline: true,
       historyApiFallback: true,
       hot: true,
-      overlay: true,
+      overlay: false,
       open: true,
       stats: 'errors-only',
       proxy: {
```

2022-07-22 04:06 UTC, andrewballantyne approved these changes

2022-07-22 16:59 UTC, samuelvl requested changes
I'm trying to inject these environment variables:

![image](https://user-images.githubusercontent.com/27858594/180487484-713e2baf-487b-4cb7-b895-8f2301d493c4.png)

However they are not injected in the notebook object:

```
spec:
  template:
    spec:
      containers:
      - env:
        - name: NOTEBOOK_ARGS
          value: |-
            --ServerApp.port=8888
            --ServerApp.token=''
            --ServerApp.password=''
            --ServerApp.base_url=/notebook/opendatahub/jupyter-nb-openldap-2duser1
        - name: JUPYTER_IMAGE
          value: image-registry.openshift-image-registry.svc:5000/opendatahub/rhods-minimal-notebook:py3.8-rhods
        - name: JUPYTER_NOTEBOOK_PORT
          value: "8888"
```

The secret is created but the configmap is not:

``` 
$ oc get secret jupyterhub-singleuser-profile-openldap-2duser1-envs
NAME                                                  TYPE     DATA   AGE
jupyterhub-singleuser-profile-openldap-2duser1-envs   Opaque   1      5m55s

$ oc get configmap jupyterhub-singleuser-profile-openldap-2duser1-envs
Error from server (NotFound): configmaps "jupyterhub-singleuser-profile-openldap-2duser1-envs" not found
```

We need both to ensure compatibility with JH.

In the `OdhDashboardConfig` we should only store the name of the environment variables, the value should be read from configmap/secret:

```yaml
  notebookControllerState:
  - environmentVariables:
    - key: VARIABLE_CM
      value: random # <-- Remove this value
```

2022-07-26 12:04 UTC, samuelvl commented
Thanks for the comment @DaoDaoNoCode! I just verified it is working as expected:

- Variables are injected into the notebook:

```yaml
        - name: VARIABLE_CM
          valueFrom:
            configMapKeyRef:
              key: VARIABLE_CM
              name: jupyterhub-singleuser-profile-svelosol-40redhat-2ecom-envs
        - name: VARIABLE_SECRET
          valueFrom:
            secretKeyRef:
              key: VARIABLE_SECRET
              name: jupyterhub-singleuser-profile-svelosol-40redhat-2ecom-envs
```

- I can read them inside the notebook server:

![image](https://user-images.githubusercontent.com/27858594/181001463-a55226b7-3504-4cd7-a84f-4a9fc4462cc1.png)

- When I shutdown the notebook server and open the spawner UI I can see the variables values:

![image](https://user-images.githubusercontent.com/27858594/181001644-5480a37e-1e58-4d59-b567-bf6b2c276dc3.png)

/lgtm

2022-07-26 12:05 UTC, samuelvl approved these changes

2022-07-26 12:05 UTC, merged