Add explanation and copy action for the Pod name in the Pipeline run graph execution node drawer
opendatahub-io/odh-dashboard pull request #3312
Opened 2024-10-08 16:47 UTC by dpanshug

Closes: [RHOAIENG-12089](https://issues.redhat.com/browse/RHOAIENG-12089)

## Description
Added copy clipboard and copy button in the Pipeline run graph execution node drawer.

<img width="502" alt="Screenshot 2024-10-08 at 9 22 00 PM" src="https://github.com/user-attachments/assets/0956a4ce-7bff-41ef-b306-a14a94d5b47c">
<img width="501" alt="Screenshot 2024-10-08 at 9 22 05 PM" src="https://github.com/user-attachments/assets/ea5ce8f0-e310-4f3c-87c8-b72e57109099">

## How Has This Been Tested?
Open a pipeline run execution and click on the node to open right drawer. Check the clipboard copy and popover text.

## Test Impact
N/A

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`
@yannnz

2024-10-09 03:27 UTC, yannnz commented
Looking good to me. Thanks.

2024-10-09 10:03 UTC, dpanshug commented
>One thing I want to double check is if this pod name always displays in the UI even the pod has been expired?

@yannnz, yes the pod name is still there.
<img width="498" alt="Screenshot 2024-10-09 at 3 32 01 PM" src="https://github.com/user-attachments/assets/73b1258b-046b-42d2-bbb4-1295b97cbab4">

2024-10-10 19:11 UTC, Gkrumbach07 commented
![Screenshot 2024-10-10 at 2 10 41 PM](https://github.com/user-attachments/assets/3dd8fb99-039b-40af-974a-74b5bb750013)

This should not fully span horizontally.

2024-10-11 03:47 UTC, yannnz commented
> ![Screenshot 2024-10-10 at 2 10 41 PM](https://private-user-images.githubusercontent.com/12587674/375512343-3dd8fb99-039b-40af-974a-74b5bb750013.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MTg3MDYsIm5iZiI6MTcyODYxODQwNiwicGF0aCI6Ii8xMjU4NzY3NC8zNzU1MTIzNDMtM2RkOGZiOTktMDM5Yi00MGFmLTk3NGEtNzRiNWJiNzUwMDEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDAzNDY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NmNhZTM3ZWQxNGRlZWJkYWMwZDA5ZmRlMWU2MjgzODcwNzc4ZmUyMGUyYzcxZDM2ODM0Yjg2NjhhOTdlNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.b0-W_UGU1CzKrjlbMwRs5_c8aJjMl0yQFspl7rv58H0)
> 
> This should not fully span horizontally.

Thanks for pointing this out! Yeap it should keep the length with the content.

2024-10-15 06:41 UTC, dpanshug commented
@Gkrumbach07 @yannnz Fixed that width issue

<img width="1024" alt="Screenshot 2024-10-15 at 12 09 22 PM" src="https://github.com/user-attachments/assets/6032d741-0882-407c-a2a1-58a406bf6071">
<img width="824" alt="Screenshot 2024-10-15 at 12 09 34 PM" src="https://github.com/user-attachments/assets/7c3bc283-7bf5-4501-a62d-48033f5a1ddf">

2024-10-15 16:58 UTC, Gkrumbach07 requested changes

2024-10-15 16:58 UTC, Gkrumbach07 commented on frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerRightContent.tsx
> +              <div style={{ display: 'inline-flex' }}>
please use a patternfly component when you can

https://www.patternfly.org/layouts/flex#inline

2024-10-16 14:03 UTC, merged