mount points in DS projects
opendatahub-io/odh-dashboard pull request #3315
Opened 2024-10-09 09:20 UTC by pnaik1

https://issues.redhat.com/browse/RHOAIENG-426

## Description

- remove add storage button
- Adding icon before storage name
- Rename workbench storage to Cluster storages
- Full mount path
- show all button

![Screenshot 2024-10-09 at 2 42 28 PM](https://github.com/user-attachments/assets/9175e672-7fa3-434b-800e-27892bfaf244)

## How Has This Been Tested?

- Go to Workbenches tab from project page
- Click on one of the notebook/workbench row
- Check whether mount path has full path
- Check show less/all button

## Test Impact
Added cypress test

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-10-09 12:22 UTC, pnaik1 commented on frontend/src/pages/projects/screens/detail/notebooks/ShowAllButton.tsx
> +const ShowAllButton: React.FC<ShowAllButtonProps> = ({
FYI, this separate button component is created  to have identical function for both cluster storage and data connection as mentioned in the mock

2024-10-09 15:22 UTC, DaoDaoNoCode commented on frontend/src/pages/projects/screens/detail/notebooks/NotebookStorageBars.tsx
>      <Stack>
I think you will need a `hasGutter` here after adding the show all button to make the layout look better.

2024-10-10 14:15 UTC, xianli123 commented
Thanks @pnaik1 @DaoDaoNoCode ! LGTM!

2024-10-10 19:29 UTC, Gkrumbach07 requested changes

2024-10-10 19:29 UTC, Gkrumbach07 commented on frontend/src/pages/projects/screens/detail/notebooks/NotebookStorageBars.tsx
> +                        <Text component="small">
these texts should not be small anymore, the mocks show them as the same size as the others

2024-10-11 07:07 UTC, pnaik1 commented
/retest

2024-10-11 20:05 UTC, Gkrumbach07 approved these changes
/lgtm
/approve

2024-10-11 20:55 UTC, merged