Update properties section of model details and version details
opendatahub-io/odh-dashboard pull request #3341
Opened 2024-10-16 14:40 UTC by ppadti

Closes: [RHOAIENG-6996](https://issues.redhat.com/browse/RHOAIENG-6996) and [RHOAIENG-13057](https://issues.redhat.com/browse/RHOAIENG-13057)

## Description
This PR aims to update Properties section of model details page and version details page:
  - Table expands when a user clicks on Add property button
  - New row appears in the properties table with the text input for Key field automatically gets the cursor focus
  
 The description input field of model details and version details pages also get cursor focus.
 Labels of model details and version details page are displayed without truncation.

https://github.com/user-attachments/assets/b9a18b8d-af43-4e47-9d1e-cccc177dd421

## How Has This Been Tested?
1. Try to add new row to Properties table with more than 5 property, so it will expand and the row will autofocus.
2. Make sure the description input field gets auto focus when we click on edit button of description section in model details and version details page.
3. Make sure the labels are not truncated any more in model details and version details page.

## Test Impact
Added and updated cypress tests.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-10-16 14:41 UTC, ppadti commented
@yih-wang Could you please take a look at the above screenshots?

2024-10-17 10:15 UTC, yih-wang commented
LGTM, thanks @ppadti !

2024-10-17 10:58 UTC, manaswinidas requested changes
I didn't find these in this PR while testing:
- The list should follow the creation order (oldest on the top, newest at the bottom), not the alphabetical order
- The fix for [RHOAIENG-13057](https://issues.redhat.com/browse/RHOAIENG-13057) - can't see the tooltip with full content for truncated labels
Otherwise lgtm.

2024-10-17 11:58 UTC, ppadti commented
> I didn't find these in this PR while testing:
> 
> * The list should follow the creation order (oldest on the top, newest at the bottom), not the alphabetical order
> * The fix for [RHOAIENG-13057](https://issues.redhat.com/browse/RHOAIENG-13057) - can't see the tooltip with full content for truncated labels
>   Otherwise lgtm.

1. we can't sort it by creation order, because we only have key/value and decided to not to do it. [Mentioned here in the comment section.](https://issues.redhat.com/browse/RHOAIENG-6996?focusedId=25754903&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-25754903)
2. we decided yesterday during standup to show the label without truncation, so no tooltip required. [comment mentioned](https://issues.redhat.com/browse/RHOAIENG-13057?focusedId=25799531&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-25799531) here in the issue.

2024-10-17 14:03 UTC, manaswinidas approved these changes
Thanks @ppadti 

/lgtm

2024-10-17 14:18 UTC, manaswinidas commented
@ConorOM1 test-id changes in this PR

2024-10-17 17:30 UTC, mturley approved these changes
Good stuff, thanks @ppadti

2024-10-17 17:30 UTC, mturley commented on frontend/src/components/EditableTextDescriptionListGroup.tsx
> +          autoFocus
Nice, I wasn't aware of this prop

2024-10-17 18:32 UTC, merged