feat(14692): default serving runtime args popover
opendatahub-io/odh-dashboard pull request #3419
Opened 2024-11-01 20:24 UTC by gitdallas

closes: https://issues.redhat.com/browse/RHOAIENG-14692

## Description
the label help button and popover to view default serving runtime args for the selected serving runtime

with no selected serving runtime:
![image](https://github.com/user-attachments/assets/6ad4e33c-929b-4350-9691-8aba29ea91df)

after selecting a serving runtime:
![image](https://github.com/user-attachments/assets/415d32f7-16a1-4745-8940-e5a90fc4c14b)

## How Has This Been Tested?
tested locally with no runtime selected and with various runtimes

## Test Impact
added a test that the popover shows up with default serving runtime arg of the selected runtime

## Request review criteria:
check the popover looks correct with various runtimes selected

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-11-01 20:24 UTC, gitdallas commented
@yih-wang

2024-11-04 06:30 UTC, manaswinidas requested changes

2024-11-04 06:30 UTC, manaswinidas commented on frontend/src/pages/modelServing/screens/projects/kServeModal/ServingRuntimeArgsSection.tsx
> +            To <strong>overrwrite</strong> a predefined argument, specify a new value in the{' '}
Typo: overrwrite -> overwrite

2024-11-04 07:00 UTC, yih-wang commented
@gitdallas Looks like there’s some mix-up with the button status here... there are totally three status for that 'view predefined params/args' button.

- Before selecting a serving runtime
  The button is **disabled**, and a **tooltip** displays while **hovering**, see the mockup [here](https://www.figma.com/proto/ahospciKiNxVeqOUZcMPlb/Dynamic-Parameters-for-Serving-Runtime?node-id=2239-3116&node-type=frame&t=nQ4x4aJooxuajKrb-1&scaling=min-zoom&content-scaling=fixed&page-id=2239%3A3105&starting-point-node-id=2253%3A4474)

- After selecting a serving runtime
  The button is **enabled**, **clicking** the button shows a **popover**, and the content within the popover depends...
   - If there **are** predefined args/vars for the selected runtime
   Show the args/vars list
   - If there are **no** predefined args/vars for the selected runtime
   Only show 'no predefined arguments/variables' in the popover body, see the [annotation #5](https://www.figma.com/proto/ahospciKiNxVeqOUZcMPlb/Dynamic-Parameters-for-Serving-Runtime?node-id=2239-3180&node-type=frame&t=nQ4x4aJooxuajKrb-1&scaling=min-zoom&content-scaling=fixed&page-id=2239%3A3105&starting-point-node-id=2253%3A4474) here

2024-11-04 17:25 UTC, gitdallas commented
@yih-wang - sorry that was missed. updated now (including new screenshots)

2024-11-04 19:11 UTC, gitdallas commented on frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
> +                    .flatMap((c) => c.args)
ah ok, i didn't know what the structure might be like and was assuming i'd need to find `args` in any existing container

2024-11-04 20:28 UTC, mturley commented on frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
> +                    .flatMap((c) => c.args)
yeah it's a weirdly arbitrary thing, that's what the model serving team said to do though.

2024-11-04 21:17 UTC, mturley approved these changes
LGTM 🎉

2024-11-04 22:24 UTC, mturley approved these changes

2024-11-04 23:37 UTC, merged