[RHOAIENG-12866] entire project context refreshed when individual resources are deleted
opendatahub-io/odh-dashboard pull request #3437
Opened 2024-11-05 19:38 UTC by jpuzz0

https://issues.redhat.com/browse/RHOAIENG-12866

## Description
Updated usages of project details context to not refresh all resources after certain actions like the one mentioned in this ticket take place (e.g. deletion of data connections).

## How Has This Been Tested?
Inspected browser network - After deleting data connections, additional API requests for other resources (e.g. fetching of notebooks) no longer occur. This can be done to manually test, or the deletion of cluster storage from the project details page.

Since there was no change in functionality, no additional tests were added for this change.

## Request review criteria:
Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 
- [x] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-11-07 18:52 UTC, DaoDaoNoCode approved these changes
Tested and works well, now we don't refresh all project resources and only re-fetch the resources as needed.
/lgtm

2024-11-07 19:02 UTC, DaoDaoNoCode requested changes
Sorry, I missed some issues, see the comments below. I think after that update everything should be good.

2024-11-07 19:02 UTC, DaoDaoNoCode commented on frontend/src/pages/projects/screens/detail/storage/StorageList.tsx
> +              refreshPvcs();
We might still need to refresh notebooks here, otherwise the connected workbench field won't update on the table

2024-11-07 19:02 UTC, DaoDaoNoCode commented on frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsList.tsx
> +              refreshDataConnections();
Same here, we might still want to refresh notebooks.

2024-11-07 21:00 UTC, DaoDaoNoCode approved these changes
Tested, works well
/lgtm

2024-11-08 15:14 UTC, Gkrumbach07 requested changes

2024-11-08 15:14 UTC, Gkrumbach07 commented on frontend/src/pages/projects/screens/detail/storage/StorageList.tsx
> +          <StorageTable pvcs={pvcs} refresh={refreshPvcs} onAddPVC={() => setOpen(true)} />
this also needs to update notebooks
```tsx
refreshPvcs();
refreshNotebooks();
```

2024-11-08 15:14 UTC, Gkrumbach07 commented on frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsList.tsx
> +            refreshData={refreshDataConnections}
this should also update notebooks.

2024-11-08 22:39 UTC, merged