Display the storage class metadata name in the end user UI
opendatahub-io/odh-dashboard pull request #3473
Opened 2024-11-13 16:15 UTC by dpanshug

[RHOAIENG-13984](https://issues.redhat.com/browse/RHOAIENG-13984)

## Description
Added resource tooltip to storage class name in the table.

<img width="491" alt="Screenshot 2024-11-13 at 9 15 43 PM" src="https://github.com/user-attachments/assets/a52fc93f-bb71-42e4-bb61-8ca9b5482e80">

Description and resource name added in select dropdown

<img width="902" alt="Screenshot 2024-11-13 at 9 15 55 PM" src="https://github.com/user-attachments/assets/205557cc-f929-4a0d-a469-a0d3af0b9d4c">

## How Has This Been Tested?
Create a storage class, and check the name, resourcename and description in storage table and create storage modal.

## Test Impact
Added cypress test to check resource name in storage table.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

@xianli123

2024-11-14 01:16 UTC, xianli123 commented
Thanks @dpanshug。 LGTM！

2024-11-14 12:21 UTC, pnaik1 requested changes

2024-11-14 12:21 UTC, pnaik1 commented on frontend/src/__tests__/cypress/cypress/tests/mocked/projects/clusterStorage.cy.ts
> +      cy.findByTestId('resource-kind-text').should('have.text', 'StorageClass');
can you create a function to these and move it to `frontend/src/__tests__/cypress/cypress/pages/clusterStorage.ts`

2024-11-14 22:03 UTC, Gkrumbach07 reviewed
Code looks good, just need all comments resolved and we can merge

2024-11-15 17:07 UTC, Gkrumbach07 approved these changes
/lgtm

2024-11-15 17:50 UTC, merged