Fix hardcoded PVC size
opendatahub-io/odh-dashboard pull request #348
Opened 2022-07-25 14:57 UTC by mlassak

Resolves #341 (WIP)

Adds ```pvcSize``` attribute to ```notebookController``` and utilizes it to replace the hardcoded PVC size value.

2022-07-25 16:03 UTC, DaoDaoNoCode requested changes
Overall it LGTM, leave a small comment.
BTW, can you also update the doc here to add `pvcSize` field? https://github.com/opendatahub-io/odh-dashboard/blob/main/docs/dashboard_config.md#notebook-controller

2022-07-25 16:03 UTC, DaoDaoNoCode commented on frontend/src/pages/notebookController/SpawnerPage.tsx
> +        const defaultPvcSize = '20Gi';
Instead of defining the default PVC size here every time, could you move it to const.ts like `DEFAULT_PVC_SIZE` and import it to this file?

2022-07-25 16:50 UTC, andrewballantyne requested changes
I agree with Juntao, a new constant in the constants file is more preferred than inline. Keeps everything together. One could make an argument to be part of the blankDashboardConfig but I do not think it is needed -- we'd still need to handle the default.

2022-07-25 16:50 UTC, andrewballantyne commented on backend/src/routes/api/status/statusUtils.ts
> +  const rbacAuthorizationApi = fastify.kube.rbac; // eslint-disable-line
remove the line if it's not used.

2022-07-25 16:51 UTC, andrewballantyne commented
@mlassak any reason this is a DRAFT PR?

2022-07-25 16:53 UTC, DaoDaoNoCode commented on frontend/src/pages/notebookController/SpawnerPage.tsx
> +        await createPvc(pvcName, requestedPvcSize ?? defaultPvcSize);
Yeah I think I already refactor this part in my PR here https://github.com/opendatahub-io/odh-dashboard/pull/331/files#diff-9415e5a981134b74b9e1a0fa3a0084ec2fabb9ca5cc0dbd0b98e03c5a009d65dR302-R304

2022-07-26 08:07 UTC, maroroman commented
> @mlassak any reason this is a DRAFT PR?

Sorry, this one is on me. There was previously a workflow such that we created a draft PR first so we can share the changes easily for other colleagues. This Pr was not meant to be reviewed yet, I just told Marek to post it so I could check it out.

2022-07-26 12:17 UTC, maroroman commented
https://github.com/opendatahub-io/odh-dashboard/pull/269 Adds a condition checking for notebook controller being enabled, since it would be duplicate code, me and @mlassak decided to rebase on top of that PR to use those changes in this PR. The backend will include using the pvcSize in the dashboard CR only if the notebook controller is enabled, otherwise it will set the pvcsize value in the jupyterhub-cfg configmap.

2022-08-01 12:10 UTC, maroroman commented
@samuelvl while testing this feature I noticed I had to delete the PVC and PV (or create a notebook for the first time in the cluster)) to get a different volume size, do we fix this behavior in this PR?

2022-08-01 12:22 UTC, samuelvl commented
@maroroman The volume size only applies for the first time the PVC is created

2022-08-01 12:31 UTC, maroroman commented
> @samuelvl while testing this feature I noticed I had to delete the PVC and PV (or create a notebook for the first time in the cluster) to get a different volume size, do we fix this behavior in this PR?

After an offline discussion, the current behavior is correct.

2022-08-02 07:15 UTC, maroroman approved these changes
lgtm

2022-08-02 12:57 UTC, DaoDaoNoCode approved these changes
lgtm

2022-08-02 13:35 UTC, andrewballantyne approved these changes
Approving to undo my requested changes -- I have not reviewed the updated changes but it appears we have enough other approvals to merge.

2022-08-03 00:45 UTC, merged