Reduce Cypress Mock Test Execution Time
opendatahub-io/odh-dashboard pull request #3579
Opened 2024-12-16 12:58 UTC by antowaddle

## Description
![image](https://github.com/user-attachments/assets/82927862-fd87-460d-b622-026eb617e23e)

**Job Separation:**
- The new workflow separates tasks into distinct jobs: Setup, Lint, Unit-Tests, Get-Test-Groups, Cypress-Mock-Tests, and Combine-Results-and-Upload. 
- This separation allows for better parallelization and clearer organization of tasks.
- **Significantly, there is a time execution reduction of ~30-35 mins for the Mock tests to execute, this will increase efficiency and enhance productivity of the team.** 

**Caching Strategy:**
- The new workflow consolidates caching into a single step in the Setup job, caching all node modules at once.

**Linting:**
- A dedicated Lint job has been added, improving code quality checks.

**Unit Testing:**
- Unit tests now have their own job, with improved handling of coverage reports.
- The new workflow explicitly copies coverage results to a specific directory and uploads them as an artifact.

**Cypress Testing:**
- The new workflow introduces dynamic test group generation with the Get-Test-Groups job.
- **Cypress tests are now run in parallel for different test groups, this greatly redused the execution time by around 80%.**

**Results Combination:**
- A new Combine-Results-and-Upload job has been added to merge results from unit tests and Cypress tests.

**Artifact Handling:**
- The new workflow uploads multiple artifacts at different stages (unit tests, Cypress tests, combined results).

**Codecov Integration:**
- The Codecov upload is now part of the Combine-Results-and-Upload job, ensuring it receives the complete test coverage data.

## How Has This Been Tested?
I've executed the PR on a number of builds and checked the results accordingly. 

## How Can This Been Tested?
Pull the code locally, then make a mock commit/push and the Github action will trigger the pipeline. 

## Test Impact
N/A.

## Request review criteria:

Self checklist (all need to be checked):
- [x] The developer has manually tested the changes and verified that the changes work
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [x] Included any necessary screenshots or gifs if it was a UI change.
- [x] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [x] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-12-19 22:43 UTC, Gkrumbach07 commented
kinda fun idea but then you end up with way to many jobs but helps identify what area failed more quickly. Is to dynamically fetch the folders in cypress/mocked and make a job from each of them. then you name the jobs by the area they are in. I spike dit out for fun. https://github.com/Gkrumbach07/odh-dashboard/actions/runs/12421941577/job/34682677262?pr=10

2025-01-13 09:17 UTC, antowaddle commented
@christianvogt @Gkrumbach07 guys can I ask for this PR to be approved?

2025-01-13 09:41 UTC, dpanshug requested changes

2025-01-13 09:41 UTC, dpanshug commented on .github/workflows/test.yml
> +        run: npm run test:fix
Should we fix the lint errors directly within this workflow? Previously, it only checked for lint errors without fixing them. 

```suggestion
        run: npm run test:lint
```

2025-01-13 09:41 UTC, dpanshug commented on .github/workflows/test.yml
> +          if-no-files-found: warn
To avoid confusion, can we rename it to `frontend-unit-coverage` & `backend-unit-coverage`?

2025-01-13 09:59 UTC, dpanshug commented
There is a dependabot suggestion to bump codecov/codecov-action from 4.6.0 to 5.1.2. @antowaddle do you think we should include in this PR? https://github.com/opendatahub-io/odh-dashboard/pull/3608/files

2025-01-13 12:11 UTC, antowaddle commented on .github/workflows/test.yml
> +        run: npm run test:fix
Good spot! Resolved in latest commit.

2025-01-13 12:11 UTC, antowaddle commented on .github/workflows/test.yml
> +          if-no-files-found: warn
Resolved in latest commit

2025-01-13 12:13 UTC, antowaddle commented
> There is a dependabot suggestion to bump codecov/codecov-action from 4.6.0 to 5.1.2. @antowaddle do you think we should include in this PR? https://github.com/opendatahub-io/odh-dashboard/pull/3608/files

@dpanshug I'd like to keep this change isolated, it's a very large change to the Dashboard pipeline and I want to reduce the blast radius.

2025-01-13 17:40 UTC, christianvogt commented on package.json
> +    "lint:test": "cd ./backend && npm run test:lint && cd ../frontend && npm run test:lint",
Why `test:lint` and `lint:test`?
Can we not use `test:lint` and remove `lint:test`?

2025-01-14 10:25 UTC, antowaddle commented on package.json
> +    "lint:test": "cd ./backend && npm run test:lint && cd ../frontend && npm run test:lint",
I've cleaned this up a little:
- lint:frontend:backend utilises test:lint to apply linting.

`"test:lint": "eslint --max-warnings 0 --ext .js,.ts,.jsx,.tsx ./src",
 "lint:frontend:backend": "cd ./backend && npm run test:lint && cd ../frontend && npm run test:lint",`

2025-01-14 16:32 UTC, christianvogt commented on package.json
> +    "test:lint": "eslint --max-warnings 0 --ext .js,.ts,.jsx,.tsx ./src",
what does this do to lint `./src` dir. That dir doesn't exist at the root.

2025-01-15 08:13 UTC, antowaddle commented on package.json
> +    "test:lint": "eslint --max-warnings 0 --ext .js,.ts,.jsx,.tsx ./src",
@christianvogt as per our IM, I've removed the additional test:lint above. These commands are already present in the package.json in both frontend and backend directories.

2025-01-15 16:06 UTC, christianvogt commented
/lgtm
/approve

2025-01-15 16:39 UTC, merged