Add create/edit hardware profile page
opendatahub-io/odh-dashboard pull request #3604
Opened 2024-12-20 19:52 UTC by DaoDaoNoCode

JIRA: [RHOAIENG-16255](https://issues.redhat.com/browse/RHOAIENG-16255)

## Description

Added the page to create/edit hardware profile, which allows you to add/edit/remove node selectors and tolerations. The work for the identifiers(node resources) is implemented in https://github.com/opendatahub-io/odh-dashboard/pull/3565 so this PR doesn't include that part.

On creation:
<img width="1512" alt="Screenshot 2024-12-20 at 2 47 25 PM" src="https://github.com/user-attachments/assets/34b05fe6-a108-43e8-9e90-cde7cd092299" />

On update:
<img width="1512" alt="Screenshot 2024-12-20 at 2 48 00 PM" src="https://github.com/user-attachments/assets/d3d59d6e-b28e-4f66-b869-0fdf91944559" />
<img width="1512" alt="Screenshot 2024-12-20 at 2 48 08 PM" src="https://github.com/user-attachments/assets/fdb06152-3206-441a-aa6b-cd7d9dba3588" />

Node selector modal:
<img width="1512" alt="Screenshot 2024-12-20 at 2 48 34 PM" src="https://github.com/user-attachments/assets/ef58f0bd-7877-4390-87e0-f8ca87253c9b" />
<img width="1512" alt="Screenshot 2024-12-20 at 2 48 45 PM" src="https://github.com/user-attachments/assets/7b3185ea-bf5a-4bae-844a-7ed3444b39b1" />

Toleration modal:
<img width="1512" alt="Screenshot 2024-12-20 at 2 49 05 PM" src="https://github.com/user-attachments/assets/9c759ef6-bb93-43c7-bb55-0e5a53e8354e" />
<img width="1512" alt="Screenshot 2024-12-20 at 2 49 18 PM" src="https://github.com/user-attachments/assets/ea487d5a-4acf-4da1-a745-ff66e3749841" />

Added last modified annotation:
<img width="1512" alt="Screenshot 2024-12-20 at 2 49 52 PM" src="https://github.com/user-attachments/assets/da6ff49f-fdc5-49ea-aba8-61a5b7cc56e5" />

## How Has This Been Tested?

1. Create a hardware profile
2. Fill in data like name, descriptions, node selectors and tolerations
3. Click create
4. Edit that hardware profile
5. Make sure everything is pre-filled correctly when editing
6. Try to edit/remove the node selectors table and tolerations table
7. Update the hardware profile
8. Expand to make sure the update takes effect

## Test Impact

Added cypress tests for the create/edit page

## Request review criteria:

Self checklist (all need to be checked):
- [ ] The developer has manually tested the changes and verified that the changes work
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)

If you have UI changes: 

- [ ] Included any necessary screenshots or gifs if it was a UI change.
- [ ] Included tags to the UX team if it was a UI/UX change.

After the PR is posted & before it merges:
- [ ] The developer has tested their solution on a cluster by using the image produced by the PR to `main`

2024-12-20 19:52 UTC, DaoDaoNoCode commented
@vconzola Could you check the screenshots? Thanks!

2025-01-02 21:23 UTC, vconzola commented
@DaoDaoNoCode A couple comments...

- The section heading for node selectors should be "Node selectors", not "Node resources".
- Once the tables are not empty, change the location of the Add buttons to the right of the section headings as noted in my recent comment in PR #3565 
Otherwise, lgtm.

2025-01-02 21:25 UTC, DaoDaoNoCode commented
@vconzola Just saw your comments in another PR and was about to ask you for the button positions 😄 thanks, I will update them.

2025-01-06 11:10 UTC, dpanshug requested changes

2025-01-06 21:50 UTC, DaoDaoNoCode commented on frontend/src/pages/hardwareProfiles/manage/ManageHardwareProfile.tsx
> +      }
Edited, thanks

2025-01-07 12:01 UTC, dpanshug commented on frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/manageHardwareProfiles.cy.ts
> +  it('create hardware profile', () => {
Can you add test case for checking error when min is greater than max, as well as default? This test case has became too long, maybe you can add that in new case, upto you.

2025-01-07 12:04 UTC, dpanshug commented on frontend/src/pages/hardwareProfiles/manage/ManageHardwareProfileWrapper.tsx
> +export const EditHardWareProfile: React.FC = () => (
```suggestion
export const EditHardwareProfile: React.FC = () => (
```

2025-01-07 12:04 UTC, dpanshug commented on frontend/src/pages/hardwareProfiles/manage/ManageHardwareProfileWrapper.tsx
> +export const DuplicateHardWareProfile: React.FC = () => (
```suggestion
export const DuplicateHardwareProfile: React.FC = () => (
```

2025-01-07 15:43 UTC, DaoDaoNoCode commented on frontend/src/pages/hardwareProfiles/manage/ManageHardwareProfile.tsx
> +  const validFormData = isK8sNameDescriptionDataValid(profileNameDesc);
Yeah, I will maybe still check on the node resources field in case users manually remove the node resources on the cluster annotations.

2025-01-07 17:58 UTC, Gkrumbach07 commented on frontend/src/pages/hardwareProfiles/const.ts
> +      maxCount: '2GiB',
you can look here: https://docs.google.com/document/d/1kB78jtaqlj_-MUBpLVpGOSUUVmbGPs_XuMmCno0ezAU/edit?tab=t.0

2025-01-08 13:43 UTC, pnaik1 commented
@DaoDaoNoCode , I am unsure if this is related to your PR or has been discussed earlier, but while adding `node resource` only the `cpu` and `memory` resource identifier will have the `units` dropdown??


<img width="1139" alt="Screenshot 2025-01-08 at 7 11 27 PM" src="https://github.com/user-attachments/assets/af81ba81-1159-4c17-956b-dca2c27e4b5c" />


what if I want a scenario like this to have unit dropdown??
<img width="1139" alt="Screenshot 2025-01-08 at 7 09 29 PM" src="https://github.com/user-attachments/assets/48e1d960-7ec7-43fd-b80b-582a677268dd" />
to add GIB unit

2025-01-08 14:13 UTC, dpanshug commented
> @DaoDaoNoCode , I am unsure if this is related to your PR or has been discussed earlier, but while adding `node resource` only the `cpu` and `memory` resource identifier will have the `units` dropdown??
> 
> <img alt="Screenshot 2025-01-08 at 7 11 27 PM" width="1139" src="https://private-user-images.githubusercontent.com/99238909/401166271-af81ba81-1159-4c17-956b-dca2c27e4b5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzNDU2MzYsIm5iZiI6MTczNjM0NTMzNiwicGF0aCI6Ii85OTIzODkwOS80MDExNjYyNzEtYWY4MWJhODEtMTE1OS00YzE3LTk1NmItZGNhMmMyN2U0YjVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA4VDE0MDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4ZDk3YzhiNWZjZWFjMzgyYTNhYTUwMzRkMGJkODU4NjBlNjQzMWZhYmY3ZWJhOTJlMmEwZDNmNmViYTQ1YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fFH-WCglGNEsywgze7INRJ7GQdi1RvG71U1NJBiC5W0">
> what if I want a scenario like this to have unit dropdown?? <img alt="Screenshot 2025-01-08 at 7 09 29 PM" width="1139" src="https://private-user-images.githubusercontent.com/99238909/401165713-48e1d960-7ec7-43fd-b80b-582a677268dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYzNDU2MzYsIm5iZiI6MTczNjM0NTMzNiwicGF0aCI6Ii85OTIzODkwOS80MDExNjU3MTMtNDhlMWQ5NjAtN2VjNy00M2ZkLWI4MGItNTgyYTY3NzI2OGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA4VDE0MDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZWQ0ZTQ1NTc4MDJjMzgxMzEyOGJlY2Y1N2U4YzQ4MDYxODAwMjFiZjk1MmYwYTZiNzFkNzUwY2Q2NzIzMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eDZhPsfNSdz3WOYtYJslUnO5p3e1xjMwjtml374uTXg"> to add GIB unit

@pnaik1 its good that you asked, @Gkrumbach07 can you clarify on this? Earlier we only discussed [having unit dropdowns](https://github.com/dpanshug/odh-dashboard/blob/8d3338cb15dd5e37f614c545c14fd1c48f9f2d83/frontend/src/pages/hardwareProfiles/nodeResource/CountFormField.tsx#L26) for CPU and Memory identifier, but in the mocks we can see units with other identifiers also.

2025-01-08 15:00 UTC, vconzola commented
@dpanshug Where in the mocks do you see units on identifiers other than CPU and memory? They shouldn't be there. If you can point me to the mockups where I show this, I'll update them.

2025-01-08 15:42 UTC, dpanshug commented
> @dpanshug Where in the mocks do you see units on identifiers other than CPU and memory? They shouldn't be there. If you can point me to the mockups where I show this, I'll update them.

@vconzola [here](https://www.figma.com/proto/UFhLtsPxoETwd39pnMsASV/Hardware-profiles?node-id=363-9932&node-type=frame&t=pfzT3oPZXNHoHy6t-0&scaling=min-zoom&content-scaling=fixed&page-id=45%3A1342) if you see identifier value is `samsung.com/gddr7`  

![Screenshot 2025-01-08 at 9 10 52 PM](https://github.com/user-attachments/assets/403c532f-4bda-43bd-9777-5acf0e3aad26)

2025-01-08 15:57 UTC, vconzola commented
@dpanshug Ugh! So this is a bit of a problem. I guess I assumed because the label is RAM, you could tell it's a memory resource. But the label is just a label, right, so you ignore it? Is there any way for you to tell from the identifier what type of resource something is? Because for something like memory, without units, the numerical values are kind of meaningless.

2025-01-08 16:01 UTC, DaoDaoNoCode commented
@vconzola hi, the identifier is unique and cannot be changeable, so for the preset `RAM` label and `memory` identifier, you should be able to change the label to `Memory` or anything you like, but the identifier should always be `memory` and that's what we will use in the workbench. For all the other identifiers other than `cpu` and `memory`, we don't need a unit.

2025-01-08 16:35 UTC, Gkrumbach07 commented
Ok I did a quick search and while technically not required, `cpu` and `memory` are not required but highly recommended. Therefore I was wrong in thinking that the we needed a `cpu` and `memory` identifier. We should still set those as the defaults, but have no restriction on having them change any aspect of it. I guess also deleting them?

So @vconzola 
- you are right, they should be a able to change the identifier for the cpu and memory entries
- do you still want to prevent deleting of those two. becuase they technically would be able to if they change the identifier to something other than cpu or ram. As that is what we check for to stop them from deleting

2025-01-08 16:46 UTC, vconzola commented
@Gkrumbach07 My gut tells me we should not allow deleting resources with cpu or ram identifiers. But will that create a conflict if a user adds a new resource (e.g. samsung.com/mem) that's also a memory resource instead of editing the existing resource with ram identifier?

2025-01-08 17:52 UTC, Gkrumbach07 commented
> My gut tells me we should not allow deleting resources with cpu or ram identifiers. But will that create a conflict if a user adds a new resource (e.g. samsung.com/mem) that's also a memory resource instead of editing the existing resource with ram identifier?

@vconzola So the issue is as follows
- user opens form with prefilled `memory` and `cpu` identifiers
- user cannot delete those
- user edits `memory` identifier to something else
- now they can delete it

we can still block them from deleting, but if we allow changing the identifier, they have a work around to deleting it. For ultimate flexibility we can allow them to delete all but maybe adding a special warning if they try to delete cpu or ram

2025-01-08 19:08 UTC, vconzola commented
> allow them to delete all but maybe adding a special warning if they try to delete cpu or ram

@Gkrumbach07 I like that idea. Any idea what happens if they don't have a cpu or ram identifier? That will help inform what the warning should say.

2025-01-08 19:39 UTC, DaoDaoNoCode commented
@pnaik1 OK, after discussion on Slack https://redhat-internal.slack.com/archives/C07C0FNHVPT/p1736352212866699, we will let k8s throw the error when submitting if there is a duplicated k8s name. As for the display name, we allow duplication, and will show a popover next to the name in the table to indicate the k8s name on the cluster for users to better tell different hardware profiles, just like other k8s resources.
As for the unit and default CPU/Memory stuff, we will need to think of a better solution to deal with all the situations instead of arbitrarily creating `cpu` and `memory` identifiers and don't allow users to remove or edit (cc @Gkrumbach07). More discussions will be needed offline, and I will post the final decision here in this PR.

2025-01-09 12:22 UTC, pnaik1 commented
@DaoDaoNoCode thanks rest of the functionality works well 
I have last question here : Aren't we adding a warning when all the hardwareprofile are disabled??

![Screenshot 2025-01-09 at 5 49 46 PM](https://github.com/user-attachments/assets/75137a57-8303-40d7-ada9-594aa4ef453c)

2025-01-09 14:15 UTC, Gkrumbach07 commented
> I have last question here : Aren't we adding a warning when all the hardwareprofile are disabled??

that is going to be handled in a follow up. those are new mocks

2025-01-09 18:02 UTC, Gkrumbach07 commented
> I like that idea. Any idea what happens if they don't have a cpu or ram identifier? That will help inform what the warning should say.

@vconzola It will schedule but it will be very unstable due to it not having any lower or upper resource bounds... so not recommended. I talked with @DaoDaoNoCode and  we determined that if we should allow them to delete and edit the cpu and memory identifiers, but then also add back your hardware profile type dropdown. Then possibly adding a warning for when they are in a state without a cpu and memory in the table

2025-01-10 03:01 UTC, DaoDaoNoCode commented
Alright, I made the following changes after discussion with @Gkrumbach07 and @vconzola 

1. Added a `Resource type` select which defaults to `Other` to the node resource modal. When switching the type to `CPU` or `Memory`, it will change the unit in the size section.
<img width="1512" alt="Screenshot 2025-01-09 at 9 56 25 PM" src="https://github.com/user-attachments/assets/90d94801-1569-4708-9b0e-27d6a7cbfe18" />
<img width="1512" alt="Screenshot 2025-01-09 at 9 58 15 PM" src="https://github.com/user-attachments/assets/b4bb282a-a5a9-45f7-aff5-c5d96460d4d1" />
<img width="1512" alt="Screenshot 2025-01-09 at 9 58 25 PM" src="https://github.com/user-attachments/assets/20292e24-1c3b-41db-b5d3-15202d3cb417" />

2. Enable removing action to the CPU and Memory rows because it's only "Recommended" to have them but not required. The admin has the flexibility to delete them. Also, allow users to edit the identifier for all the resources.
<img width="1512" alt="Screenshot 2025-01-09 at 9 59 46 PM" src="https://github.com/user-attachments/assets/7007d289-7e56-4309-b32e-1e48cbf53a76" />

3. When removing the last CPU type resource or Memory type resource, it will show an alert. (Wording suggestions are welcomed here, and a final revise by content designer will be done after the epic is done)
<img width="1512" alt="Screenshot 2025-01-09 at 10 00 26 PM" src="https://github.com/user-attachments/assets/cfb0146a-a869-4d30-8bd2-b40eeccfafe1" />

2025-01-10 06:00 UTC, pnaik1 commented
/lgtm

2025-01-10 19:22 UTC, Gkrumbach07 approved these changes
looks good

/lgtm

2025-01-10 20:14 UTC, merged