Fix gpu fileread
opendatahub-io/odh-dashboard pull request #691
Opened 2022-10-24 16:49 UTC by maroroman

Adds a timeout to the SAToken Promise to prevent dev_mode issues stemming from #573 

## Description

## How Has This Been Tested?
1. Verify branch works (access api/gpu endpoint) locally `npm run dev`
2. Verify branch works on cluster with ODH when built

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

2022-10-24 16:52 UTC, andrewballantyne commented on backend/src/plugins/kube.ts
> +    if (currentContext === 'inClusterContext') {
nope -- think of this flow. This didn't work before because what happens when you're not `currentContext` of `inClusterContext`?

2022-10-24 16:54 UTC, andrewballantyne requested changes

2022-10-24 16:54 UTC, andrewballantyne commented on backend/src/routes/api/status/statusUtils.ts
> +        saToken,
Why do you need this in the frontend? I didn't see why you needed it in your last PR either...

2022-10-24 16:54 UTC, andrewballantyne commented on backend/src/plugins/kube.ts
> +    saToken = await promiseWithTimeout(getSAToken(), 5000);
This is an odd flow, waiting/racing for a timeout is not a bad practice... but your Promise literally has no way to go forward if you're not onCluster -- why the 5 second delay to starting up in dev?

2022-10-25 11:02 UTC, maroroman commented
Rewrote the PR to just add a condition checking if the app is inCluster and otherwise it just ignores the token.

2022-10-31 16:00 UTC, andrewballantyne commented on backend/src/plugins/kube.ts
> +  }
- What happens if you don't the service account?
- What happens if you don't find one that matches?
- What happens if you find one early?
    - Do you not want to use `.find`?

You make a lot of assumptions about the state of things, and I think you need to handle what-ifs -- what if you don't get it back, what if your list is empty.

2022-10-31 17:05 UTC, maroroman commented
Additional testing revealed this PR is not necessary. Closing.

2022-10-31 17:05 UTC, closed without merging