Add faker for the pass through api to enable regular user testing
opendatahub-io/odh-dashboard pull request #806
Opened 2022-11-24 13:18 UTC by lucferbux

## Description

This PR adds support for impersonating pass through API calls with a regular user token.
The main goal here is just to avoid disabling backend functionality in development which needs special admin roles (admin settings, regular jupyter notebooks, dsg project creation...) but enabling pass-through requests with a regular user token.

## How Has This Been Tested?

To enable this:
1. Get a regular user Openshift token
2. Add the `DEV_TOKEN_AUTH` variable to your env variables file with the regular user's token as value.
3. This way you can replicate some bugs like this:
<img width="1111" alt="Screenshot 2022-11-24 at 14 05 39" src="https://user-images.githubusercontent.com/16117276/203793873-ff84327f-0b52-4318-9f79-ad6c369b780a.png">

## Merge criteria:

- [X] The commits are squashed in a cohesive manner and have meaningful messages.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work

2022-11-24 15:47 UTC, andrewballantyne requested changes
Neat idea. We should probably log a dev ticket, low priority, to handle thinking on how to make the dev experience better all together. Might be able to avoid granting stupid permissions to do this.

This may also just come for free when we kill the old backend.

2022-11-24 15:47 UTC, andrewballantyne commented on backend/src/utils/directCallUtils.ts
> +    if (DEV_TOKEN_AUTH !== '') {
```suggestion
    if (DEV_TOKEN_AUTH) {
```

2022-11-24 15:47 UTC, andrewballantyne commented on backend/src/utils/directCallUtils.ts
> +    //Faker, just to check if pass through works with regular users while having admin rights for the rest of the backend
```suggestion
    // Fakes the call as another user to test permissions
```

2022-11-24 20:21 UTC, lucferbux commented
> Neat idea. We should probably log a dev ticket, low priority, to handle thinking on how to make the dev experience better all together. Might be able to avoid granting stupid permissions to do this.
> 
> This may also just come for free when we kill the old backend.

@andrewballantyne Yes for sure, I'm creating a new ticket for this, thanks for the feedback (resolved in my branch since I was working offline this evening).

2022-12-05 16:20 UTC, andrewballantyne commented on backend/src/utils/constants.ts
> +export const DEV_TOKEN_AUTH = process.env.DEV_TOKEN_AUTH || '';
@lucferbux I think we need to make sure this is not set in DEV_MODE !== true, so we need to still do this ternary.

2022-12-14 20:03 UTC, andrewballantyne commented
Thinking more on this situation -- I wonder if we could set something up that would allow us to start the server with a cluster-admin (aka mimic a service account starting it on cluster) and then somehow making another more basic user to be the one logged in. The one in the top right, the one making all the "oauth" (not really because it does not exist locally) calls, etc, etc

2022-12-15 09:16 UTC, lucferbux commented on backend/src/utils/constants.ts
> +export const DEV_TOKEN_AUTH = process.env.DEV_TOKEN_AUTH || '';
Done, i couldn't commit this, but fixed.

2022-12-15 09:22 UTC, lucferbux commented
> Thinking more on this situation -- I wonder if we could set something up that would allow us to start the server with a cluster-admin (aka mimic a service account starting it on cluster) and then somehow making another more basic user to be the one logged in. The one in the top right, the one making all the "oauth" (not really because it does not exist locally) calls, etc, etc

Yeah, I've been thinking about this too, I think it can be done. There are three main points right now:

* **Pass through API faker**: I think that this PR covers most of it.
* **Mimic local permissions to the same as the Dashboard Serviceaccount:** This will be very helpful to catch all the permission errors we have with permissions in local development.
* **Fake user for backend**: I think this is suuuuper easy to implement, I can have that in this PR if you want @andrewballantyne or maybe in a follow up PR.

2023-01-13 16:06 UTC, lucferbux commented
To sum up, with this PR we are now having:

* Faker for pass-through API k8s calls
* Faker for backend API calls

It would be really nice to support this in the future:
* Ability to mimic dashboard serviceaccount permissions for the backend

What do you think, @andrewballantyne ?

2023-02-03 20:55 UTC, andrewballantyne requested changes
Still testing the functionality -- few code review comments.

2023-02-15 21:12 UTC, DaoDaoNoCode commented
This PR currently covers most of the situations which directly make API calls to k8s resources. However, it could have some problems when making API calls to the external routes (like prometheus), the `Impersonate-User` field doesn't work, it will still use the bearer token of the login user.

2023-02-23 17:33 UTC, lucferbux reviewed
/lgtm

I've checked and it seems that every logic condition to enable is behind the DEV_MODE flag.
Tested it and it's working great, and checked the Prometheus situation, we might wanna check that in the future, but so far I think is the best solution now.

2023-02-23 17:38 UTC, DaoDaoNoCode commented
/lgtm
Self-tested. See if I can approve this PR because I also committed to it.

2023-02-28 10:22 UTC, lucferbux commented
/assign @andrewballantyne

2023-02-28 19:49 UTC, andrewballantyne requested changes
I think we need to do one more iteration to get this into merging state.

Only downfall I see that is not addressed in my comments is when I change the server code, it does not update my client back to a state of understanding that the impersonation was lost. This is probably fine -- we don't do a lot of server dev, and we have https://github.com/opendatahub-io/odh-dashboard/issues/964 coming.

2023-02-28 19:49 UTC, andrewballantyne commented on backend/src/utils/directCallUtils.ts
> +    }
I'm not happy with the way this fails for the impersonated user when calling prometheus. So I started investigating.

Lets just ignore this use-case, and skip this step if we are calling thanos.
```suggestion
    if (isImpersonating() && !url.includes('thanos-querier-openshift-monitoring')) {
      // We are impersonating an endpoint that is not thanos -- use the token from the impersonated user
      // Thanos Querier does not grant basic user access on external routes
      headers = {
        ...kubeHeaders,
        Authorization: `Bearer ${getImpersonateAccessToken()}`,
      };
    }
```

This is related to the bug we had where basic users could not get their own status in the Dashboard, but could get it in OpenShift console. 

After a talk with the OpenShift Console folks, I learned that we were using the wrong endpoint 9091 was a special endpoint for the admin-ish users (essentially those who can list the Namespaces object). 9092 was the endpoint for talking to a namespace-locked endpoint, which basic users could use to query things like their storage value.

It appears we "need to use the thanos tenancy service, which is not exposed through a route" -- which equates to not being something we can do externally -- such as our case, in local development. There may be other ways to go about this, but effectively we can just fallback on our admin during this dev flow, as we know the call is not going to work.

For testing of permissions, we'll just need to make use of hosting it on cluster to test some prometheus things -- which is fairly easy now that all our PRs upload an image to our quay.

2023-03-01 09:25 UTC, lucferbux commented
@andrewballantyne I resolved your comments since @DaoDaoNoCode  update the PR, but I just want to add that we still fall short in one scenario, but I think is no longer relevant.

We still use the primary logged user as the rbac for the backend calls, so we still don't have a `1:1` relation to the dashboard's serviceaccount. This is still an issue if we are developing any backend feature (it might work in local as we have cluster admin but then it won't work deployed because the dashboard role doesn't have those permissions).

It's similar to the prometheus workaround, something that we can easily test now as we can deploy images built by that PR. One easy workaround would be create a user that mimics the same permissions as the dashboard serviceaccount, but I would do it outside this PR in addition of the script that Andrew has for creating users in clusters.

2023-03-01 19:17 UTC, andrewballantyne approved these changes

2023-03-01 19:23 UTC, merged