Modify logout and control panel redirect for project notebooks
opendatahub-io/odh-dashboard pull request #846
Opened 2022-12-08 14:03 UTC by DaoDaoNoCode

## Description

Closes #808 
There is no way to change the text Hub Control Panel, it's hardcoded in JupyterLab https://github.com/jupyterlab/jupyterlab/blob/master/packages/hub-extension/src/index.ts#L74-L80
The logout success prompt will be triggered twice, have no idea why, left a comment and waiting for reviews.

## How Has This Been Tested?

Create a notebook in DSG, login to the notebook, and try to click the logout and hub control panel button.

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2022-12-08 18:13 UTC, andrewballantyne requested changes

2022-12-08 18:13 UTC, andrewballantyne commented on frontend/src/pages/notebookController/NotebookLogoutRedirect.tsx
> +          navigate(`/projects/${namespace}`);
```suggestion
          navigate(`/projects/${namespace}?notebookLogout=${notebookName}`);
```

2022-12-08 18:13 UTC, andrewballantyne commented on frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
> +      notification.success(`Logout workbench successfully`);
RE: my other comment

Remove the search param from the URL here. 
Docs: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/delete

2022-12-08 18:13 UTC, andrewballantyne commented on frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
> +  }, [notebookLogout, notification]);
make a custom hook -- this is all one thing and shouldn't be so inline with a component. Get into the habit of making custom hooks when you have isolated & coupled functionality.

2022-12-08 18:13 UTC, andrewballantyne commented on frontend/src/pages/notebookController/NotebookLogoutRedirect.tsx
> +  }, [
You'll want to cancel this hook too on updates.

2022-12-08 18:20 UTC, andrewballantyne commented on frontend/src/pages/notebookController/NotebookLogoutRedirect.tsx
> +          navigate(`/projects/${namespace}`);
Oops, was rushing over the code -- this is not needed

2022-12-08 19:10 UTC, andrewballantyne commented on frontend/src/pages/projects/screens/detail/useCheckLogoutParams.ts
> +  const [queryParams, setQueryParams] = useSearchParams();
Hah, did not know about this. Neat.

2022-12-08 19:14 UTC, DaoDaoNoCode commented on frontend/src/pages/projects/screens/detail/useCheckLogoutParams.ts
> +      notification.success(`Logout workbench successfully`);
I wanted to, but I can only show the k8s name instead of the display name unless we fetch the Notebook object here.

2022-12-09 14:48 UTC, andrewballantyne requested changes

2022-12-09 14:48 UTC, andrewballantyne commented on frontend/src/pages/projects/screens/detail/useCheckLogoutParams.ts
> +      }
What if it's loaded and you can't find it? Perhaps we put an error case here too? 

Something like:
```
} else if (loaded) {
  notification.error('Error logging out', 'Unable to locate notebook to finalize logout');
  // remove query param
}
```

2022-12-09 15:43 UTC, andrewballantyne commented on frontend/src/api/network/notebooks.ts
> +        'notebooks.opendatahub.io/oauth-logout-url': `${origin}/projects/${projectName}?notebookLogout=${notebookName}`,
```suggestion
        'notebooks.opendatahub.io/oauth-logout-url': `${origin}/projects/${projectName}?notebookLogout=${notebookId}`,
```

This needs to be the k8s name

2022-12-09 15:53 UTC, andrewballantyne commented on frontend/src/pages/projects/screens/detail/useCheckLogoutParams.ts
> +          `Logout workbench "${getNotebookDisplayName(notebook.notebook)}" successfully`,
```suggestion
          `Logged out of workbench "${getNotebookDisplayName(notebook.notebook)}" successfully`,
```

2022-12-09 15:54 UTC, andrewballantyne approved these changes
Baring the one tiny text change, this is good to merge.

/approve
/hold

2022-12-09 15:58 UTC, andrewballantyne commented
/lgtm

2022-12-09 16:18 UTC, merged