Add tooltip to the explore card types
opendatahub-io/odh-dashboard pull request #873
Opened 2023-01-05 19:17 UTC by DaoDaoNoCode

## Description

Closes #863 
Add a tooltip as described in the issue, and updated the CRD as well. At the same time, updated part of the code to make the badge show the correct color that they should be.

<img width="1050" alt="Screen Shot 2023-01-05 at 2 15 36 PM" src="https://user-images.githubusercontent.com/37624318/210862074-c3f26ea5-a30c-4fe9-b74e-3bbbda916c07.png">

## How Has This Been Tested?

Go to the explore page and hover over the type badges.

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2023-01-09 15:21 UTC, lucferbux approved these changes

2023-01-31 20:54 UTC, andrewballantyne requested changes

2023-01-31 20:54 UTC, andrewballantyne commented on frontend/src/components/OdhExploreCardTypeBadge.tsx
> +  } else {
Small nit -- I get what you're doing here works... but I'd recommend actually doing this:

```
if - case A; set tooltip to 'A'
else if - case B; set tooltip to 'B'
else if - case C; set tooltip to 'C'

if !tooltip; return
```
That way if we add another case that doesn't set the tooltip for whatever reason we don't try to render a Tooltip with content.

It's the same thing right now, but it separates the category statements from the return -- so we can manage the fall-through case a bit less "in with the rest"

2023-01-31 20:54 UTC, andrewballantyne commented on frontend/src/components/OdhAppCard.tsx
> +    'm-warning': odhApp.spec.support === 'third party support',
I'm concerned about these support vs category changes -- also any reason they are not an enum?

2023-01-31 20:54 UTC, andrewballantyne commented on frontend/src/components/OdhAppCard.tsx
> +        odhApp.spec.support !== ODH_PRODUCT_NAME ? (
Would not support be "red hat" or "third party support" -- not RHODS or ODH?

2023-01-31 20:54 UTC, andrewballantyne commented on frontend/src/components/OdhExploreCard.tsx
> +    'm-hidden': odhApp.spec.support === ODH_PRODUCT_NAME,
Same question here...

2023-02-10 13:03 UTC, andrewballantyne requested changes
/unhold

2023-02-10 13:03 UTC, andrewballantyne commented on manifests/crd/odhapplications.dashboard.opendatahub.io.crd.yaml
> +                  enum:
Undo this based on the conversation in slack from a few days ago. I'd like to see this make this sprint and they are hesitant about CRD changes due to CRs in flight out there

2023-02-10 13:03 UTC, andrewballantyne commented on frontend/src/types.ts
> +    category?: OdhApplicationCategory;
```suggestion
    category?: OdhApplicationCategory | string; // unbound by the CRD today -- should be the enum
```

2023-02-10 14:33 UTC, andrewballantyne requested changes

2023-02-10 14:33 UTC, andrewballantyne commented on frontend/src/components/OdhExploreCardTypeBadge.tsx
> +  category: OdhApplicationCategory;
You'll need this to also handle a string -- since it's unbounded.

2023-02-10 14:42 UTC, andrewballantyne approved these changes
/hold

Works great, thanks for doing this! Sorry about the CRD back and forth -- didn't know they were so immutable.

If you want to fix the if-statement comment, please do -- I'll reapply the lgtm. If not, just unhold it. It's not critical in anyway.

2023-02-10 14:55 UTC, andrewballantyne approved these changes

2023-02-10 14:58 UTC, DaoDaoNoCode commented
found one issue, hold for a moment.

2023-02-10 15:01 UTC, DaoDaoNoCode commented
@andrewballantyne Can you review it again? I made a small mistake just now but now it's fixed.

2023-02-10 15:09 UTC, andrewballantyne commented
> @andrewballantyne Can you review it again? I made a small mistake just now but now it's fixed.

Good catch -- I missed that.

2023-02-10 15:26 UTC, andrewballantyne approved these changes

2023-02-10 15:44 UTC, merged