Allow users to edit workbench GPU to 0
opendatahub-io/odh-dashboard pull request #886
Opened 2023-01-11 20:30 UTC by DaoDaoNoCode

## Description

Closes #881 

## How Has This Been Tested?

Since I don't have a GPU cluster, I only did some fake tests and checked the Notebook CR, it works.
1. Go to the dashboard config CR, set `notebookController -> gpuSetting: '3'`
2. Go to the spawner page, you will see the GPU number dropdown
3. Select the GPU number
4. Go to check the Notebook CR
5. Edit the workbench and set the GPU to 0
6. Check the Notebook CR again

## Merge criteria:

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2023-01-13 08:33 UTC, maroroman commented
running retest to verify if tests are failing across repo

/retest

2023-01-13 08:36 UTC, maroroman commented
/retest

2023-01-16 22:13 UTC, andrewballantyne commented on frontend/src/api/network/notebooks.ts
> +  existingNotebook.spec.template.spec.affinity = {};
We need to clone this. I missed it during the rapid development of DSG. You're mutating likely state from the context here -- we can't trust variable sources of what is passed to us, let us avoid mutating those.

2023-01-16 22:16 UTC, andrewballantyne commented on frontend/src/api/network/notebooks.ts
> +    delete resources.requests?.['nvidia.com/gpu'];
Ah yeah -- probably shouldn't mutate this either -- can we return an updated set of resources or something instead?

Mutations of variables you are passed has a long history of causing issues weirdly. Imagine a bug in a scenario completely separate of this, 2 months from now. When I do xyz the data just doesn't appear anymore.... or is different than what I did... and I have no idea why. Turns out, it was some function call in a dozen that mutated the variable. Best to always be pure about input so you don't have a headache later.

2023-01-17 14:42 UTC, andrewballantyne commented on frontend/src/api/network/notebooks.ts
> +  const oldNotebook = { ...existingNotebook };
You'll need to use `_.cloneDeep` unfortunately... spreads are shallow copies and thus when you dig into properties like `.spec` that's an object reference -- so you are now mutating the previous object.

2023-01-23 17:44 UTC, andrewballantyne requested changes
Code works good -- minor request to change the type.

2023-01-23 17:44 UTC, andrewballantyne commented on frontend/src/types.ts
> +    'nvidia.com/gpu'?: number;
These are strings in my case 🤔 I wonder if we should make sure to covert to number from the override config setting. It worked on clusters with GPUs I think -- so we should be _fine_ for now.

Could you define a "special type" for GPU?
```
/** 
 * OdhDashboardConfig contains gpuSetting as a string value override -- proper gpus return as numbers
 * TODO: Look to make it just number by properly parsing the value
 */
type GPUCount = string | number;
```
```suggestion
    'nvidia.com/gpu'?: GPUCount;
```

That way we can document it once and look to change it in the future.

2023-01-23 20:01 UTC, andrewballantyne approved these changes

2023-01-23 20:05 UTC, merged