[WIP] Allow GPU serving setting
opendatahub-io/odh-dashboard pull request #935
Opened 2023-02-08 16:02 UTC by cfchase

Allow ServingRuntimes to specify allowed number of GPUs

## Description
I've added an annotation to the ServingRuntime specification in the servingruntimes-configmap.yaml
```yaml
data:
  override-config: |
    apiVersion: serving.kserve.io/v1alpha1
    kind: ServingRuntime
    metadata:
      annotations:
        opendatahub.io/gpu-setting: '1' #same as notebook gpuSetting
```
This is meant as a stopgap feature until full support for GPUs is implemented and tested, but hopefully follows the same development flow for servingruntimes-configs without the annotation.

## How Has This Been Tested?
Change redhat-ods-applications servingruntimes-config to add an annotation to the override servingruntime 

`opendatahub.io/gpu-setting: '1'`
`opendatahub.io/gpu-setting: '5'`
`opendatahub.io/gpu-setting: '0'`
`opendatahub.io/gpu-setting: 'hidden'`
no annotation

Verify the gpu selection shows as expected and test .
<img src="https://user-images.githubusercontent.com/1448375/217579397-b3d8e4f5-1069-4e20-aaed-1dbf30cf4325.png" width="400" />

Configure a model server is spawned with correct limits/requests/affinities

Verify any pods spawned for the model server contain the correct limits/requests/affinities 

Tested on OCP 4.11 with GPU operator installed using live build `quay.io/cfchase/rhods-operator-live-catalog:1.22.0-w7`

- [ ] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ ] The developer has manually tested the changes and verified that the changes work

2023-02-08 20:27 UTC, cfchase commented on frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
> +      requests && limits && min <= parseInt(requests) && parseInt(requests) <= parseInt(limits)
The old check wasn't allowing the resource == limit.  Setting them both the same seems a pretty common use case, but let me know if this seems like a problem

2023-02-09 04:54 UTC, andrewballantyne requested changes
Looks pretty good on face-value -- I'll need to test it tomorrow; maybe @lucferbux can test this in his morning.

I think due to the amount of conflicts we will have -- you should probably merge first and I can go back through and try to fix all my PRs. Otherwise we'll be sharing in the conflicts between my various PRs.

2023-02-09 04:54 UTC, andrewballantyne commented on frontend/src/api/network/notebooks.ts
> -  const tolerations: NotebookToleration[] = [];
FWIW -- we'll have a conflict here -- I moved some of the toleration stuff around in #903.

2023-02-09 04:54 UTC, andrewballantyne commented on frontend/src/pages/modelServing/screens/projects/ServingRuntimeList.tsx
> +    refreshServingRuntimesConfig();
Why do you need to refresh before you open? It should be a relatively up to date set of data...

2023-02-09 04:54 UTC, andrewballantyne commented on frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
> +  const resourceIsSet = (fieldName, min = 1) => {
This is going to conflict with my PR in #937 -- it got a significant overhaul to handle units.

2023-02-09 04:54 UTC, andrewballantyne commented on frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeExpandedField.tsx
>  const ServingRuntimeSizeExpandedField: React.FC<ServingRuntimeSizeExpandedFieldProps> = ({
This component got a significant facelift. You'll probably want to rebase onto #937 to solve this conflict.

2023-02-09 04:54 UTC, andrewballantyne commented on frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx
> +    setData('gpus', parseInt(target.value));
If the field starts with a non-number, you'll get NaN.

Relevant quote from MDN:
> If the first character cannot be converted to a number [...], parseInt returns NaN. Leading whitespace is allowed.

Docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#description

It should be noted that NumberInputs are not immune from showcasing a non number.

2023-02-09 04:54 UTC, andrewballantyne commented on frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx
> +    const target = event.target as HTMLInputElement;
```suggestion
    const target = event.currentTarget;
```

2023-02-09 04:54 UTC, andrewballantyne commented on frontend/src/pages/modelServing/screens/projects/ServingRuntimeTable.tsx
> +              refreshServingRuntimesConfig();
Same Q here -- do we really need to refresh?

2023-02-09 04:54 UTC, andrewballantyne commented on frontend/src/pages/modelServing/screens/projects/utils.ts
> +  servingRuntimesConfig: ConfigMapKind | undefined,
Nit
```suggestion
  servingRuntimesConfig?: ConfigMapKind,
```

2023-02-09 04:54 UTC, andrewballantyne commented on frontend/src/pages/modelServing/screens/projects/utils.ts
> +  console.log('createModelState', ...createModelState);
Debug code...

2023-02-09 04:54 UTC, andrewballantyne commented on frontend/src/pages/modelServing/screens/types.ts
> +  resources: ContainerResources;
We'll need to normalize on this -- I didn't go further than I needed for the type; #937 makes use of `ServingRuntimeResources`

2023-02-09 04:54 UTC, andrewballantyne commented on frontend/src/pages/projects/types.ts
> +  tolerationSettings?: TolerationSettings;
Yeah, I thought of doing this change in #938 -- this will cause a conflict in naming.

2023-02-09 04:56 UTC, andrewballantyne commented
@cfchase I see that this is a WIP -- hopefully it's reasonably done otherwise we're going to have a race of conflicts tomorrow.

2023-02-09 13:52 UTC, cfchase commented
@andrewballantyne I should have removed the WIP last night after I finished testing.   Removed it

2023-02-09 13:54 UTC, cfchase commented
@andrewballantyne nevermind.... WIP back on while I rebase off of yours.

2023-02-09 17:02 UTC, cfchase commented on frontend/src/pages/modelServing/screens/projects/utils.ts
> +  servingRuntimesConfig: ConfigMapKind | undefined,
done

2023-02-09 17:06 UTC, cfchase commented on frontend/src/pages/modelServing/screens/projects/utils.ts
> +  console.log('createModelState', ...createModelState);
done

2023-02-09 17:49 UTC, andrewballantyne approved these changes

2023-02-09 17:56 UTC, merged