Update workbench image recommended tag
opendatahub-io/odh-dashboard pull request #992
Opened 2023-03-06 11:03 UTC by lucferbux

## Description

Fix #990 

Ensure changes on OOTB images with support of n -1 version is working in the UI.

## How Has This Been Tested?

1. Install this live build in your cluster: [quay.io/rh_ee_atheodor/rhods-operator-live-catalog:1.21.0-rhods-6041](http://quay.io/rh_ee_atheodor/rhods-operator-live-catalog:1.21.0-rhods-6041)
2. Add the `opendatahub.io/workbench-image-recommended: 'true'` tag to one of the notebook's images such as 's2i-minimal-notebook:py3.8-v1.3.1'
3. Check that the UI is displaying the recommended label
<img width="453" alt="Screenshot 2023-03-06 at 11 57 22" src="https://user-images.githubusercontent.com/16117276/223092553-c317083d-67bd-4bea-838c-37601771dfca.png">

<img width="1079" alt="Screenshot 2023-03-06 at 11 56 47" src="https://user-images.githubusercontent.com/16117276/223092540-ed936805-14b5-42e2-adb6-e08d96124ae5.png">

## Test Impact

## Request review criteria:

- [X] The commits have meaningful messages (squashes happen on merge by the bot).
- [X] Included any necessary screenshots or gifs if it was a UI change.
- [X] Included tags to the UX team if it was a UI/UX change.
- [X] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [X] The developer has manually tested the changes and verified that the changes work
- [X] The developer has added tests or explained why testing cannot be added (unit tests & storybook for related changes)

2023-03-06 11:04 UTC, lucferbux commented
@kywalker-rh these are the changes for supporting n - 1 version, all seems correct such as the designs you provided.

2023-03-06 13:54 UTC, andrewballantyne commented
You don't sort to the top -- @kywalker-rh is it more important that we keep the version order (from semver) or supersede it when we have a recommended version?

![image](https://user-images.githubusercontent.com/8126518/223129276-0f5f0ac4-16c6-4ef3-a4a7-e9e9652bbec8.png)

2023-03-06 14:29 UTC, kywalker-rh commented
@andrewballantyne To me, recommended should always be at the top. Chances are that will usually coincide with the version order too, but recommended should be at the top and preselected by default.

2023-03-06 18:21 UTC, andrewballantyne requested changes
Yup, so one more item for you to address Lucas. Make sure the sort logic kicks recommended to the top.

2023-03-07 14:59 UTC, andrewballantyne commented
/hold

Holding this until next release to sync up with the image updates as well.

2023-03-13 17:28 UTC, andrewballantyne commented
/unhold

Needs another review -- but can merge now.

2023-03-20 15:53 UTC, lucferbux commented
@andrewballantyne this can be merged now since we are targeting the new release

2023-03-22 12:21 UTC, Gkrumbach07 reviewed
code looks good. just had one question.

2023-03-22 12:34 UTC, lucferbux commented on frontend/src/pages/projects/screens/spawner/spawnerUtils.ts
> +  } else if (b.annotations?.['opendatahub.io/workbench-image-recommended']) {
Yeah, we can add that.

2023-03-23 08:33 UTC, lucferbux commented on frontend/src/pages/projects/screens/spawner/spawnerUtils.ts
> +  } else if (b.annotations?.['opendatahub.io/workbench-image-recommended']) {
Added a `const` since it's the same structure used in the backend, just to have them synced. I agree that this change improves legibility.

2023-03-23 08:34 UTC, lucferbux commented
/assign @andrewballantyne

2023-03-23 11:22 UTC, alexcreasy reviewed
@lucferbux I've eyeballed the code and there's nothing that stands out. I'll run + test it once my cluster has spooled up.

2023-03-23 11:56 UTC, Gkrumbach07 approved these changes
/lgtm

2023-03-23 18:58 UTC, alexcreasy approved these changes
Code looks good to me.
Deployed and tested, the UI changes works as described in the PR.

2023-03-24 16:02 UTC, andrewballantyne approved these changes

2023-03-24 16:23 UTC, merged

2023-03-27 04:54 UTC, shalberd commented
Very nice, enabling both dynamic and less dynamic image versions this way, selectable. This makes obsolete my concerns about GUI support. Plus, the fact that you only use non-SHA digest format in odh-manifests master branch imagestreams is good practice, too, purely from a development perspective.